### ISSUE TITLE
Ability to pull stemcell images from a private image repository

### ISSUE THREAD

**Issue by jbuns** [cloudfoundry-incubator/kubecf#1003]
**Is your feature request related to a problem? Please describe.**
We are hosting our stemcell images from a private image repository and at the moment there is no configuration in kubecf we can set that allows the helm installation process to pull from that private image repository. 

**Describe the solution you'd like**
We would like to have a parameterised configuration we can set in kubecf that allows the helm installation process to pull images from a private image repository.

**Describe alternatives you've considered**
Keep hosting the stemcell images in a public image repository.

**Additional context**
N/A

**Comment by jandubois** [comment]
@jbuns Sorry, I forgot that we had this issue already. In the interest of keeping the issues list manageable I'm closing this issue because #1421 has more details about the proposed implementation. Feel free to re-open if you disagree!

**Comment by jbuns** [comment]
Fine by me!
