### ISSUE TITLE
Use Eirini with buildpaks based on a UBI stack

### ISSUE THREAD

**Issue by jbuns** [cloudfoundry-incubator/kubecf#1008]
**Is your feature request related to a problem? Please describe.**
We want to run kubecf with Eirini that supports a UBI-based stack (rhel) so that we can push apps that uses UBI-based buildpacks. At the moment kubecf with Eirini can only handle sle15-based stack.

**Describe the solution you'd like**
We want a configuration where we can set the desired stack when Eirini is enabled.

**Comment by jandubois** [comment]
@jbuns Are you still planning to implement this feature in a way that can be merged into the kubecf repo?

If not, can we close this issue?

**Comment by jbuns** [comment]
Yeah, we can close this out.
