### ISSUE TITLE
Integrate the bazel replacement scripts in pipeline(s) and catapult

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1010]
## Acceptance Criteria

- [x] all KubeCF pipelines use the new scripts, not `bazel` (https://github.com/cloudfoundry-incubator/kubecf/pull/1111, https://github.com/cloudfoundry-incubator/kubecf/pull/1163)
- [x] catapult no longer uses bazel either (https://github.com/SUSE/catapult/pull/243)
- [x] pipelines are green 🟢
- [x] update docs with instruction on how to build using the new scripts, and remove bazel references (https://github.com/cloudfoundry-incubator/kubecf/pull/1162)
- [x] update also https://kubecf.suse.dev

**Comment by viovanov** [comment]
Blocked by #1009

**Comment by viccuad** [comment]
PR to remove Bazel from Catapult: https://github.com/SUSE/catapult/pull/243. Note that Catapult was not used to build kubecf in CI, so merging this PR has no effect on current CI.

**Comment by viccuad** [comment]
Blocked on https://github.com/cloudfoundry-incubator/kubecf/issues/1095

**Comment by viccuad** [comment]
we should not forget https://kubecf.suse.dev, added to the list

**Comment by viccuad** [comment]
Made minimal changes in kubecf.suse.dev, but opened https://github.com/cloudfoundry-incubator/kubecf-docs/pull/18 for dropping repetition of dev docs and pointing directly to the kubecf repo.

**Comment by viccuad** [comment]
Updated kubecf.suse.dev manually, postponing cloudfoundry-incubator/kubecf-docs#18 to be considered in https://github.com/cloudfoundry-incubator/kubecf/issues/1200.

**Comment by viccuad** [comment]
Card done, closing.
