### ISSUE TITLE
Remove bazel targets from KubeCF

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1011]
## Acceptance Criteria

- [x] remove all build files and resource code (https://github.com/cloudfoundry-incubator/kubecf/pull/1204)
- [x] announce the change on the slack channel
- [x] make sure all pipelines still pass
- [x] build artifacts are correct

**Comment by viovanov** [comment]
Blocked by #1010

**Comment by viccuad** [comment]
PR pipeline obviously passed, master has passed for the merged PR and 2 others after it. Marking that tick as passed.
