### ISSUE TITLE
Versioning common script

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1013]
## Acceptance Criteria

- should fail if it's not in a git repo
- should fail if there's no semver tag available
- version should be calculated as implemented in the quarks project (development versions should include number of commits since the latest tag and the commit `1.0.2-0.gb3f7a0c1`)
- implemented in ruby with tests
- version should be printed to stdout

Existing scripts for calculating versions:
https://github.com/SUSE/scf/blob/develop/make/include/versioning
https://github.com/SUSE/eirinix-helm-release/blob/master/bin/package#L34
https://github.com/cloudfoundry-incubator/quarks-operator/blob/master/bin/include/versioning
https://github.com/cloudfoundry-incubator/quarks-job/blob/master/bin/include/versioning

**Comment by viovanov** [comment]
Once this is done, we should create stories to use it in all projects.

**Comment by viovanov** [comment]
Blocked by #1012

**Comment by viovanov** [comment]
Keep an eye on #1012 for pushing the script in its final location.

**Comment by thardeck** [comment]
Please review https://github.com/SUSE/kubecf-tools/pull/1

**Comment by thardeck** [comment]
https://github.com/SUSE/kubecf-tools/pull/2
