### ISSUE TITLE
Document concourse.suse.dev upgrade process and upgrade

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry-incubator/kubecf#1025]
To avoid debugging Concourse issues that may already be solved (and to stay up to date with security fixes), we need to define a safe, easy and clear process on how to upgrade concourse.suse.dev to latest Concourse version.

## Acceptance Criteria

- The is a documented process on how to upgrade
- The process includes any needed backup and restore to keep old builds around
- If something goes wrong, there should be a documented way to revert to previous version
- The process it tested by upgrading Concourse to the latest version

**Comment by jimmykarily** [comment]
We had to create workers using the helm chart because our internal ECP workers were gone. In the process of doing so we also upgraded the kubernetes cluster to 1.15 and Concourse to 6.4 . This was unplanned so we didn't have time to complete the tasks on this issue (documentation etc). We should leave this open and complete this with some later upgrade.

**Comment by fargozhu** [comment]
@jimmykarily I am closing this issue since we decided to move to GHA quickly. We can reopen later if we think so...
