### ISSUE TITLE
Kubecf pipeline should allow for development copies of itself

### ISSUE THREAD

**Issue by viccuad** [cloudfoundry-incubator/kubecf#1032]
**Is your feature request related to a problem? Please describe.**

Right now it's not possible to deploy a copy of the production pipeline that doesn't interfere with the production one. Also, by disabling some jobs on the copy of the pipeline, it is possible that the cleanup of GKE cluster doesn't get triggered.

Copies of the pipeline are needed, for example if you want to improve the KubeCF production pipeline without testing in production, or want to deploy your own that tests a specific branch. 

**Describe the solution you'd like**

The KubeCF pipeline should:

- [x] Have options to disable publishing artifacts to Github or the release S3 bucket, and to update Github status. (https://github.com/cloudfoundry-incubator/kubecf/pull/1041)
- [x] Work if the list of branches to be tested  is changed (see `$branches` definition in pipeline.yaml.gomplate).
    - Right now, selecting a somewhat normal branch name such as `viccuad-upgrade-clobber`   breaks GKE cluster creation or deletion because the cluster name is too long. (https://github.com/cloudfoundry-incubator/kubecf/pull/1108)
- [ ]  ~Allow partial deployments of the kubecf pipeline, making sure that cluster deletion gets triggered correctly to not forget destroying clusters.~
- [ ] Allow pausing the first triggering job by default, to not waste resources (https://github.com/cloudfoundry-incubator/kubecf/pull/1139)
- [x] Consume and publish intermediate build artifacts to a different s3 bucket than the production one
- [x] #1036 Have documentation on "How do I deploy a copy of the pipeline?"

**Describe alternatives you've considered**
Make the needed changes (chop code, rename vars) to the pipeline definition by hand, which is impractical.

**Additional context**

This arose just in a try to test https://github.com/cloudfoundry-incubator/kubecf/pull/1031

**Comment by viovanov** [comment]
Closing because of #1144
