### ISSUE TITLE
Kubecf docs search doesn't work

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#1034]
**Is your feature request related to a problem? Please describe.**
The search mechanism on [kubecf docs repo](https://kubecf.suse.dev/docs/) is terrible and/or even broken.

**Describe the solution you'd like**
We need to understand how hugo(?) search works and if we can make it better.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mudler** [comment]
This is fixed by now
