### ISSUE TITLE
PRs from forks are not triggering after being approved

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1035]
**Describe the bug**
Even though a PR from a fork is approved the CI pipeline is not triggering.

**To Reproduce**
PR from fork.

**Expected behavior**
CI should trigger

**Additional context**
https://concourse.suse.dev/teams/main/pipelines/kubecf?group=fork-pr

**Comment by jimmykarily** [comment]
More work here: https://github.com/cloudfoundry-incubator/kubecf/pull/1073
