### ISSUE TITLE
Copy secrets for kubecf CI to the public vault instance 

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1045]
## Acceptance Criteria

All the secrets required to run the kubecf pipelines are available in the public vault instance.
https://volt.cap.explore.suse.dev/

**Comment by andreas-kupries** [comment]
- Where are the secrets to put into the vault at the moment ?
  - I see 8 different auth methods, and do not believe that I have credentials for any of them
  - Who has credentials for and/or access to the vault ?

**Comment by andreas-kupries** [comment]
From @mook-as 
> Go to https://github.com/settings/tokens and make a token with scope `read:org`; you can then use it to login to https://volt.cap.explore.suse.dev/ui/vault/auth?with=github (using GitHub as the auth method).

Verified that this works.

@viovanov @thardeck 
It seems that the secrets we wish to move are stored in `suse/cloudfoundry/secure/concourse-secrets.yaml.gpg`, correct ?
Do we have examples of GH actions and/or concourse pipelines using volt secrets already ?
I did not see anything in kubecf, cloudfoundry, cf-ci.

**Comment by andreas-kupries** [comment]
Wrt examples for GHA and concourse, nevermind, I see now that this is out of scope here. The question is only relevant for  #1047 .

@viovanov Please provide me with credentials for the volt which have permissions to create/modify secrets.

Plan is to create a single secret `cf-ci` and fill it with the all the keys+values from the blackbox.

**Comment by andreas-kupries** [comment]
@viovanov Ping 2 : Please provide me with credentials for the volt which have permissions to create/modify secrets.

**Comment by andreas-kupries** [comment]
Talked with Vlad. While no permissions to make new secrets, my token has permission to edit an existing secret (add new version). That worked.

Thanks.

**Comment by andreas-kupries** [comment]
See volt instance now.

**Comment by mook-as** [comment]
I think we're putting too many secrets in there; previously (in concourse), only the secrets used in a pipeline was set (unfortunately baked into the deployed pipeline definition).  Now, all secrets are visible, including things that we don't need in any pipeline / workflow (e.g. the rubygems credentials, which we basically only used for configgin).

Also, `mything` probably shouldn't be there :)

**Comment by andreas-kupries** [comment]
Removed the `mything`. Not something I added (because it does not exist in the concourse-secrets file).

**Comment by viovanov** [comment]
this is done
