### ISSUE TITLE
Release checklist: add announcement to docs

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#1050]
It appears that we have a [blog](https://kubecf.suse.dev/blog/) section on the docs site, which has two release announcement and a… sample post‽ We should either update our release checklist to add an entry there, or delete it completely.

I seem to be dumb — I can't understand the document structure in https://github.com/cloudfoundry-incubator/kubecf/tree/master/doc/release to figure out _which_ is the actual release checklist (there seems to be two overlapping documents plus a template for the GitHub release text).

**Comment by fargozhu** [comment]
I think we should delete the blog section.
