### ISSUE TITLE
use catapult to create gke cluster and have option to set other backends as well in config yaml

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/kubecf#1078]
**Is your feature request related to a problem? Please describe.**
Right now gcp cluster creation is hard coded. We should use catapult/ cap-terraform to create k8s cluster and make it configurable so that we can change backend to any public platform via config.

**Describe the solution you'd like**

- Use catapult/cap-terraform to deploy and destroy k8s. eg: https://github.com/SUSE/cap/blob/master/cap-ci/scripts/deploy_k8s.tmpl#L19, https://github.com/SUSE/cap/blob/master/cap-ci/scripts/destroy_k8s.tmpl#L18
- Use pool to handle kubeconfig and terraform state files. eg: https://github.com/SUSE/cap/blob/master/cap-ci/pipeline.yaml.tmpl#L89-L107
- make backend configurable. eg: https://github.com/SUSE/cap/blob/master/cap-ci/cap-pre-release.yaml#L25-L28
- "Deploy k8s" should be its own job.

**Comment by viccuad** [comment]
https://github.com/SUSE/catapult/pull/223 mimics the current GKE deployment we have on the kubecf pipeline.

**Comment by viovanov** [comment]
Closing because of #1144
