### ISSUE TITLE
Remove code from pipeline definitions and put it in a separate folder

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/kubecf#1090]
Right now our pipeline definition itself contains script/ definitions to perform sub tasks in a job. This makes the pipeline definition difficult to understand and iterate. 
We must move these definition / code / scripts outside of our pipeline definition (just like our variables are kept in config file). 
We should take this route even if we iterate slowly towards `task` workflow.

**Comment by fargozhu** [comment]
@prabalsharma @viccuad closing this one since we all agree to move 100% to GitHub Actions CI.
