### ISSUE TITLE
Contributing document refers to T-shirt sizes but they don't exist

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#1114]
**Describe the bug**
The contributing document refers to T-shirt sizes:

https://github.com/cloudfoundry-incubator/kubecf/blob/31cc18a3bc5f1fec5ee7f2608cd5eb8b24fdee37/CONTRIBUTING.md#how-do-we-estimate

But we no longer use those.

**To Reproduce**
Follow the link.

**Expected behavior**
Document things that are true.

**Environment**
N/A

**Additional context**
None.

**Comment by fargozhu** [comment]
updated by magic ;)
