### ISSUE TITLE
database-0 pod never getting ready

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#1128]
I've seen a number of bug reports on the SUSE mailing lists and chat systems about `database-0` pods not getting ready. I've also observed this in a live setup on a somewhat resource constrains Azure setup, and the issue was clearly that the pod got killed before the database was fully initialized.

The problem is that the liveness probe only has an `initialDelaySeconds` of 30 seconds. After that it tries 3 times to ping the database via `mysqladmin` in 10 second intervals, and after that the pod is restarted:

https://github.com/cloudfoundry-incubator/kubecf/blob/da9480a/deploy/helm/kubecf/templates/database.yaml#L281

I would recommend to increase the initial delay to at least 180s, or maybe even more. This should only be done for the liveness probe; it makes sense for the readiness probe to start after 30s so the pod can become ready earlier.

**Comment by phakkarainen** [comment]
As I do not have any coding background, my comment most certainly is a bit odd, even stupid.

Can this situation not be trapped and an error message given, or even stop processing and fail properly since it's not going anywhere anymore? And pardon, if this is a silly question.

**Comment by jandubois** [comment]
> Can this situation not be trapped and an error message given, or even stop processing and fail properly

Not sure what you mean by "fail properly". Terminating a pod when it seems to be no longer alive is the way to "fail properly" in a stateful set. The controller will then create a replacement pod that will be scheduled again by k8s.

This mechanism exists to deal with pods that fail by "hanging" instead of "crashing". A hanging service will otherwise not be replaced, but also cannot serve any requests, so is effectively a service degradation.

In this particular case it is just that the time allowed for the service to become ready seems to be too small, so the service gets kill even though it didn't actually fail.

**Comment by phakkarainen** [comment]
Hi,

I focus on the big picture, which might not quite suite the container ideology that well.

I mean, when the pod has failed and it has dependencies (not sure which way this is said in English, is depended by others), the process is stuck and will never ever finish, no matter what.

So in this  particular scenario, why is there a timeout, if the pod is critical for others to be able to get started. To me that fights against the container ideology, does it not.

One solution would be to increase timeout, but would it  actually be better to increase the retries? Wouldn't the service (in this kind of sluggish situation) start sooner with shorter timeout with more retries, that longer timeout and less retries. Why are retries limited, what does it give in this particular situation? Not giving up would give a chance.

Or is the reasoning based on the sluggish environment, in which it might actually better to fail than to continue after all?

Pete
________________________________

**Comment by jandubois** [comment]
> Wouldn't the service (in this kind of sluggish situation) start sooner with shorter timeout with more retries, that longer timeout and less retries.

The primary purpose of the liveness probe is not to check if the service has started: it is to detect when a running service stops responding. So kube will check every 10 seconds if the database server is responding. If it doesn't respond 3 times in a row, it decides that "something" is wrong, so kills the pod and schedules a replacement, hoping that the issue causing the service to stall will be resolved.

"Something" could be some rare deadlock in the software itself; or some network issues, or working on a request that causes some massive performance problem.

Not killing the pod means that the service is unavailable (single instance), or underresourced (having non-responsive instances counting against total instance count).

This is all part of what is commonly called the "self-healing" property of the cloud config; pets vs. cattle etc: if something doesn't work, kill it and create a new instance. The cloud equivalent of rebooting your machine.

Now starting up a service is a special case: it may take longer than the regular liveness interval for the service to get ready, especially for the very first start, when the database data has to be created an initialized on persistent storage. That's why we can specify the `initialDelaySeconds`. Otherwise the service might not be able to start up at all, if the pod is always restarted before initialization can finish. But there should still be a max amount of time you are willing to wait before you declare the pod to be non-functional and want to replace it.

So there is some delicate balance to be found, between acceptable delay under higher load, and the longest acceptable outage of the service before it gets restarted.

**Comment by jandubois** [comment]
Kubernetes: Turning things off and back on again, as a Service! 😸

**Comment by phakkarainen** [comment]
Points taken! Thx Jan!

Jan Dubois <notifications@github.com> kirjoitti 19.7.2020 kello 0.19:

﻿

Wouldn't the service (in this kind of sluggish situation) start sooner with shorter timeout with more retries, that longer timeout and less retries.

The primary purpose of the liveness probe is not to check if the service has started: it is to detect when a running service stops responding. So kube will check every 10 seconds if the database server is responding. If it doesn't respond 3 times in a row, it decides that "something" is wrong, so kills the pod and schedules a replacement, hoping that the issue causing the service to stall will be resolved.

"Something" could be some rare deadlock in the software itself; or some network issues, or working on a request that causes some massive performance problem.

Not killing the pod means that the service is unavailable (single instance), or underresourced (having non-responsive instances counting against total instance count).

This is all part of what is commonly called the "self-healing" property of the cloud config; pets vs. cattle etc: if something doesn't work, kill it and create a new instance. The cloud equivalent of rebooting your machine.

Now starting up a service is a special case: it may take longer than the regular liveness interval for the service to get ready, especially for the very first start, when the database data has to be created an initialized on persistent storage. That's why we can specify the initialDelaySeconds. Otherwise the service might not be able to start up at all, if the pod is always restarted before initialization can finish. But there should still be a max amount of time you are willing to wait before you declare the pod to be non-functional and want to replace it.

So there is some delicate balance to be found, between acceptable delay under higher load, and the longest acceptable outage of the service before it gets restarted.

**Comment by satadruroy** [comment]
The resource constraints due to a nested virtualization setup might have precipitated this so lowering the priority.

**Comment by mudler** [comment]
I can confirm it happens for me locally as well in a fresh deployment on kind. Not sure if it's the same issue, but in the database logs I see:

```
│ logs 2020-09-09T07:27:17.631180Z 1 [Note] WSREP: Setting wsrep_ready to true                                                                                                                                    │
│ logs 2020-09-09T07:27:17.631193Z 1 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.                                                                                                        │
│ logs 2020-09-09T07:27:21.168813Z 11 [Note] Access denied for user 'root'@'localhost' (using password: YES)                                                                                                      │
│ logs 2020-09-09T07:27:26.331193Z 12 [Note] Access denied for user 'root'@'localhost' (using password: YES)                                                                                                      │
│ logs 2020-09-09T07:27:31.492765Z 13 [Note] Access denied for user 'root'@'localhost' (using password: YES)   
```

**Comment by jandubois** [comment]
> Not sure if it's the same issue

I think this is a separate issue; this bug is about the database no initializing at all. Your logs indicate that your database is running, but denying you access.

**Comment by satadruroy** [comment]
Can we use a startup probe?  

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

**Comment by andreas-kupries** [comment]
On first reading that sounds like a better fix.
Do we know if the operator supports startup probes ?
(The spec is a QuarksStatefuluSet, so it does go through operator)

@jandubois Your opinion ?

**Comment by jandubois** [comment]
I think StartupProbes were added in Alpha in 1.16 and went to Beta (and enabled by default) in 1.18, so I don't think we can rely on them yet. Please double-check the versions!

**Comment by jandubois** [comment]
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by jandubois** [comment]
@fargozhu We should maintain a list somewhere with improvement ideas linked to each  kube version, so we can revisit any time we increase the minimum supported kube version. We can then decide if we want to create issues for the ideas that now become feasible, or if they have become irrelevant.

Not sure if this should be inside the repo, or maybe just a reference Github issue that we don't expect to ever close. Initial list below:

---

### Kubernetes 1.18

* Use StartupProbe for slow database start [#1128]

**Comment by andreas-kupries** [comment]
Thanks @jandubois . Ok, lets stay with the extended initial delay for the liveness for now.

**Comment by ryzior** [comment]
Hi
I'm having issues with database-0 pod , not sure if I should raise another issue or use this one (since my issue is a bit different )
I was unable to find any relevant information yet and maybe I'm missing some initial env setup?
I'm runing k8s 1.20.1 on ubuntu.
```
 kubectl get pods -n kubecf
NAME                                     READY   STATUS             RESTARTS   AGE
cf-apps-dns-59f9f659f5-kg2jd             1/1     Running            0          8m51s
coredns-quarks-6db68476bd-dvxw6          1/1     Running            0          7m28s
coredns-quarks-6db68476bd-wb7p7          1/1     Running            0          7m28s
database-0                               0/2     CrashLoopBackOff   12         7m8s
database-seeder-a8e75e61ba456096-twfzf   1/2     NotReady           0          7m37s
ig-e5540e5dcfc6e9aa-7xtlg                0/19    Pending            0          3m4s
ig-e5540e5dcfc6e9aa-lk9pg                0/19    Evicted            0          7m17s

```
container logs:
```
k logs database-0 database -n kubecf
Removing pending files in /var/lib/mysql, because sentinel was not reached
Running --initialize-insecure on /var/lib/mysql
total 8.0K
drwxrwxrwx 2 65534 65534 4.0K Jan 11 08:22 .
drwxr-xr-x 1 root  root  4.0K Aug 19 17:45 ..
2021-01-11T08:23:03.543324Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2021-01-11T08:23:03.546531Z 0 [Warning] WSREP: Node is running in bootstrap/initialize mode. Disabling pxc_strict_mode checks
2021-01-11T08:23:03.566633Z 0 [ERROR] **Can't change data directory owner to mysql**
2021-01-11T08:23:03.566664Z 0 [ERROR] Aborting
```
PV is a NFS share (RW permissions confirmed) - this is just a lab setup.
