### ISSUE TITLE
Implement default memory limits

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#1142]
Right now it is possible to override memory limits on a per-container basis, like this:

```
operations:
  inline:
  - type: replace
    path: /instance_groups/name=log-cache/jobs/name=log-cache/properties/quarks?/bpm/processes/name=log-cache/limits/memory
    value: 2G
```

But it is impractical to expect the user to know the list of instance groups and jobs, that needs to be configured, and what a sensible memory limit would be for each.

This request if for:

[ ] collect typical memory requirements for each job, verify them against possible defaults in the `bpm.yml` files, and then include them in kubecf.

[ ] Provide a mechanism in kubecf to globally enable memory limits with the default settings

This request does not cover disk size limits. They are not supported by the bpm model, and not implemented by cf-operator.

## Acceptance Criteria

KubeCF should start and run CATS normally within these limits.
Collect peak values from SUSE's sandbox and add 50% to that.

**Comment by jandubois** [comment]
Not sure why I mentioned disk limits; we probably don't care about them anyways.

But we should think about CPU limits, which also would require additional support from cf-operatior.

**Comment by gaktive** [comment]
@jandubois feel free to update #1155 with more details regarding CPU limits. I hope we don't need disk limits...

**Comment by jandubois** [comment]
> I hope we don't need disk limits...

I hope so too. However, setting limits on ephemeral storage would prevent pods from consuming all local node disk space if some progress goes wild and starts producing extensive amounts of logging.

**Comment by gaktive** [comment]
Documentation would be needed to help set limits.

**Comment by gaktive** [comment]
https://github.com/cloudfoundry-incubator/kubecf/issues/52 is an older relation to map what we had in SCF.

**Comment by viovanov** [comment]
Hi @colstrom - can you please help us out with some peak values for containers?

**Comment by andreas-kupries** [comment]
Note to self 
```
kubectl top pod -n kubecf --containers
POD          NAME       CPU(cores)   MEMORY(bytes)   
database-0   database   196m         236Mi           
database-0   logs       0m           0Mi             
```

The thing to remember here is `--containers`. This causes `top pod` to report usage per container per pod, not simply per pod.
That is what we need to provide resource settings per container.

**Comment by andreas-kupries** [comment]
#  Implemention plan

  - A new global setting `memory_limits`, analogous to
    `high_availibility` can be used to enable/disable the default
    memory limits for the instance-groups and their jobs.

  - Contrary to `high_availibility` the new setting is `true` by
    default.

  - A new config file maps from instance-groups, and jobs to their
    default memory requirements.

  - When the new setting is true a set template loops ingests the
    above mapping and converts it into an ops file for the deployment,
    setting the requested memory limits.

## `values.yaml`

New key `memory_limits` of type boolean, default `true`.
Deploys kubecf with standard memory limits.

## `values.schema.yaml`

New setting `memory_limits: {type: boolean}`, sibling to `high_availability`.

## `config/`

New file `memory.yaml`. The yaml in this file maps the names of
instance groups, and jobs to the default memory limit for that group,
and job.

Example:
```
limits:
  memory:
    log-cache:
      log-cache: 2G
```

## Extension of basic idea to handle to feature flags

Modify the structure of `memory.yaml` to split the set of instance
groups into several classes, namely:

  - `always`,
  - `autoscaler`
  - `credhub`,
  - `diego`,
  - `eirini`,
  - `external_database`
  - `routing_api`

Further modify the template code using the config file to convert only
the applicable classes per the current feature settings.

In other words convert `always` always, choose either `diego` or
`eirini` as per the feature, and all others when their feature is
active.

Example:
```
limits:
  memory:
    autoscaler:
      ...
    credhub:
      ...
    diego:
      ...
    eirini:
      ...
    external_database:
      ...
    routing_api:
      ...
    always:
      log-cache:
        log-cache: 2G
```

## `chart/assets/operations/memory.yaml`

The templating code converting the memory configuration data into ops
instructions for the deployment.

Conditional on `memory_limits` being true.

Current code (Confirmed to work, using limits for `log-cache`, with `diego`).

```
{{- if .Values.memory_limits }}
{{- if $.Values.limits }}
{{- if $.Values.limits.memory }}

{{- range $ig, $jobs := $.Values.limits.memory }}
{{- range $job, $value := $jobs }}
- type: replace
  path: /instance_groups/name={{ $ig }}/jobs/name={{ $job }}/properties/quarks?/bpm/processes/name={{ $job }}/limits/memory
  value: {{ $value }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
```

Code changed for handling of features (untested):

```
{{- if .Values.memory_limits }}
{{- if $.Values.limits }}
{{- if $.Values.limits.memory }}

always

{{- if  .Values.features.eirini.enabled }}
eirini
{{- else }}
diego
{{- end }}

{{- if .Values.features.autoscaler.enabled }}
autoscaler
{{- end }}

{{- if .Values.features.credhub.enabled }}
credhub
{{- end }}

{{- if .Values.features.external_database.enabled }}
external_database
{{- end }}

{{- if .Values.features.routing_api.enabled }}
routing_api
{{- end }}

{{- end }}
{{- end }}
{{- end }}
```

**Comment by jandubois** [comment]
Right now we have a big mess of config schemes in `values.yaml`: we have `features`, we have `settings`, and we have properties at the top level. It is not clear to me yet how we should clean this up.

### `values.yaml`

Right now I would prefer that anything that can be enabled/disabled will be added as `features.memory_limits.enabled` for consistency with other features, but am open to be convinced otherwise.

### `values.schema.json`

Just want to point out that any settings in `config/*` files need to be covered by the schema as well. Otherwise a user cannot override the values. Also `helmlint` will do special acrobatics to subject those config files to schema validation as well (both to make sure we didn't make a mistake, and to make sure that users can override at deployment time).

### `limits` top level property

I've been struggling to think about all the potential future requirements to come up with an extensible data structure:

* Historically we have had instance counts, resource limits and requests, and affinity settings all under `sizing`.

* If we want to have a property just for limits, do we want to group cpu, memory, and ephemeral disk all under the ig/job,
  or do we have a memory limits in one tree, and cpu limits in another?

* And what about requests? Should they be grouped with limits, or have again their own tree?

I can't make up my mind, so I think your proposal is probably good. We can add additional separate trees for other properties as we add them.

I would however propose to add a defaults mechanism like this:

```
limits:
  memory:
    '$default': 128Mi
    log-cache:
      '$default': 386Mi
      log-cache: 2Gi
```

I don't think it makes much sense to have very narrow limits for each container; we really only want to kill them when they leak, not when they use a bit more memory that expected from out load tests. So in many cases a slightly generous default is fine, and we only want to override when we know a specific job/container needs a lots of memory.

I don't know if having both a global and an instance group default make sense, but should not make the template significantly more complex. I use the `$` prefix to make it obvious it is a meta-property and not an ig or job name.

Finally, I prefer to specify sizes in `Mi` and `Gi` (1024^2 and 1024^3) instead of `M` and `G` (10^6 and 10^9), but maybe that is just personal preference.

### Extension to deal with feature flags

I don't like this proposal because it moves configuration settings into template code. I've been thinking about something like this:

```
instance_group_condition:
  credhub: features.credhub.enabled
  diego_api:
    # Only `locket` is enabled under Eirini
    bbs: '!features.eirini.enabled'
```

So each instance group _can_ have a condition, which is either a boolean, a string, or a map. Since a non-existing condition always evaluates to `true` you can just pass this value to `_config.condition` to see if you should process this ig at all or not.

If the value is a `map`, then you have to check each job name against the condition in the map. Again, a missing entry means the job is enabled.

This mechanism allows us to add new features with new jobs/instance groups without requiring changes to the core template logic.

**Comment by andreas-kupries** [comment]
### `values.yaml`

I am ok with changing the name of the key. Although I am not sure if we can call this a feature.

### `values.schema.json`

Ok. The missing entries for the config structure is definitely a bug/oversight on my part. Interestingly enough things worked locally without them when I tried to set requirements on log-cache.

That may have been because of my helm version not recent enough.

So, definitely to fix.

On single vs multiple trees. My current vision was multiple trees, i.e.

```
limits:
  memory:
    ...
  cpu:
    ...
  ...
```

Although now I am thinking that `sizing` might be a better name for the overarching key, simply because it fits better when looking not just at memory, but at memory + cpu + (eph) disk + instance counts. It is mainly the latter which makes me flip to `sizing` here.

Oh, requests ... Requests are also more like a `sizing`, than a limit ...

Hm ...

```
sizing:
  memory:
    ...
  cpu:
    ...
  memory-limit:
    ...
  cpu-limit:
    ...
  ...
```

Or ...

```
sizing:
  <group>:
    <job>:
      limit:
        memory:
	cpu:
      request:
        memory:
	cpu:
	disk:
	count:
```

The nice thing about the separate trees is the handling of the defaults I think. In the unitary tree I threw up above you can do defaults, because the higher layers are mixed.


Ok, with all the examples done ... I am now coming down on the following spec:

```
  limits:
    memory:
      '$default': ...
      log-cache:
        '$default': ...
        log-cache: ...
```

For `cpu` and disk limits we add trees `limits.cpu`, `limits.disk`, ...

For instance groups, cpu, and memory __requests__ on the other hand we add a top-level tree `sizing`, and then make them trees underneath that.

I have no opinion on the narrow-ness of the limits, or what units to use I pulled the `2G` for `log-cache.log-cache` in my example out of thin air.

### Extension to deal with feature flags

> I don't like this proposal because it moves configuration settings into template code.

I agree here, although not for the same reason I think. My proposal switched only igroups, and now found that `routing_api` does some switching of jobs in igroups. As such I came to sort of the same thing you are thinking about, of having conditions, although I was thinking about adding them to the memory tree. And that part is wrong, me forgetting that more trees will likely come, i.e. cpu, which need that too. So you having the conditions in their own tree is definitely correct.

Would that also be a config file ?

Note I will likely need help (docs) on how to use the conditions. ... Never mind. You mention `_config.condition` which looks to be exactly what is needed. Will has to learn more about dispatch by typing however, i.e. map vs bool|string.

**Comment by jandubois** [comment]
> I am ok with changing the name of the key. Although I am not sure if we can call this a feature.

I just go by the made-up rule that anything that can be turned on and off is a `feature`, otherwise it is a `setting`. Both really only exist to keep individual config values from the root...

> Would that also be a config file ?

It could be its own config file, or you could include it in `config/releases.yaml`, as it is somewhat related.

Eventually all config settings for non-CF-deployment releases will be moved out into their own files, but we are not there yet.

**Comment by andreas-kupries** [comment]
From the chat:
> Example how to use _config.condition: https://github.com/cloudfoundry-incubator/kubecf/blob/master/chart/assets/operations/releases.yaml#L9

I prefer separate config file for the conditions. Should we decide to merge things we can do that with a script.

**Comment by jandubois** [comment]
> I prefer separate config file for the conditions. Should we decide to merge things we can do that with a script.

It is purely organizational. They are all merged into `$.Values` at runtime: https://github.com/cloudfoundry-incubator/kubecf/blob/d1e11f6/chart/templates/_config.tpl#L52 (but without overwriting, so user-provided values take precedence).

**Comment by andreas-kupries** [comment]
Spec extension from a question on the chat:

- The `instance_group_condition` tree has to be comprehensive, i.e. contain the full list of groups, and jobs per group.

This is required because with the defaults in the memory tree we cannot range over that tree any more to generate the ops instructions from the entries. We have to range over something which has all the groups and jobs. This then enables us to create ops instructions for all of them, even when the memory has no explicit data.

**Comment by mudler** [comment]
> Not sure why I mentioned disk limits; we probably don't care about them anyways.
> 
> But we should think about CPU limits, which also would require additional support from cf-operatior.

Support for it should be there already :slightly_smiling_face:  https://quarks.suse.dev/docs/quarks-operator/concepts/resources_limit/

**Comment by andreas-kupries** [comment]
PR with tooling (helpers): https://github.com/cloudfoundry-incubator/kubecf-tools/pull/8

**Comment by andreas-kupries** [comment]
Rebased to latest head, bringing in the CF bump. Collapsed history of small fixes.
