### ISSUE TITLE
Update sle stack and create automation for it

### ISSUE THREAD

**Issue by thardeck** [cloudfoundry-incubator/kubecf#1143]
There is no automation in place to update the SLE stack for kubecf.

**Describe the solution you'd like**
There is one pipeline for cflinuxfs3 in the internal concourse and repo to create prs which we should adapt to update sle automatically and move the pipeline and the code to the public instances and public repos.

**Describe alternatives you've considered**
We could manually update the stack but I do not see any reason why not automate it.

**Additional context**
The current cflinuxfs3 update pipline is in the internal repo under `ci/pipelines/update-kubecf-cflinuxfs`. There is also one to update the SLE stack in scf `ci/pipelines/sle15-rootfs-publish`.

**Comment by fargozhu** [comment]
@thardeck can we include GitHub Action work here?

**Comment by thardeck** [comment]
Yes, true, this can be moved to done. It is not perfect like this but should work fine.
