### ISSUE TITLE
PR checking for forks triggered by a comment

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1146]
## Acceptance Criteria

- ability to trigger tests for a PR from a fork using a comment from a person that has write access to the repo (approval from someone with write access could work too)
- PRs without approval or a comment must not be automatically checked

Blocked by #1144

**Comment by mook-as** [comment]
https://github.community/t/github-actions-manual-trigger-approvals/16233/64 has a thing for triggering on approval

**Comment by viovanov** [comment]
Let's use the solution linked by @mook-as

**Comment by fargozhu** [comment]
@viovanov isn't this done when using the `pr-request` label?

**Comment by fargozhu** [comment]
implemented
