### ISSUE TITLE
Upgrade tests in GH Actions

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1147]
## Acceptance Criteria

- PR checking should test upgrade scenarios for KubeCF

Blocked by #1144

**Comment by viccuad** [comment]
From retros, I remember we needed:

- Upgrade from previous latest minor version to release under test.
- Upgrade from previoust latest major version (starting with 2.X) to release under test.
- Upgrade from release under test to release under test.
- Upgrade from release under test to future, non-existent yet, release.

**Comment by mook-as** [comment]
This should be doable now, because the bulk of the GH Actions work is in.

To test things, (in your GitHub fork) label PRs with the `pr-test-trigger` label and the CI action should pick it up.
