### ISSUE TITLE
GH Actions: Cluster pooling

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#1158]
**Is your feature request related to a problem? Please describe.**
Currently, if we use the GitHub Actions based CI, it always creates a new cluster on AKS for a run.  (Actually, two — one for diego, and one for eirini).  Sometimes this leads to us running out of quota since each cluster is 3 nodes × 8 vCPUs each = 24 vCPUs, and we have a quota of 100 per region.

**Describe the solution you'd like**
We should do something like a concourse pool resource, where we limit the total number of clusters in flight at a time.  Maybe make it an actual [GitHub Actions action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) to ensure cleanup?

**Describe alternatives you've considered**
- Manually re-running jobs that fail due to quota issues. This is the status quo, and kind of terrible (though at least re-running things work)

**Additional context**
Currently we also need to manually keep track of Azure resource groups when the pipeline fails _while_ bringing up the cluster (because terraform doesn't always tear down correctly).  Given that the resource group is named after the run, perhaps we can do better and force delete the RG in cleanup…

**Comment by mook-as** [comment]
Related, but not quite the correct thing: [limiting concurrent job runs](https://github.community/t/16844).

**Comment by fargozhu** [comment]
@mook-as are we creating k8s cluster on other public providers than GCP?

**Comment by mook-as** [comment]
@fargozhu Currently we're only creating GKE clusters (at the time the issue of filed, GHA was AKS based).
