### ISSUE TITLE
SUSE buildpack stemcell bumps don't always support latest buildpacks

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#1164]
We have 2 different pipelines that bump buildpacks in kubecf:

1. whenever upstream releases a new buildpack we get a corresponding build for the SUSE buildpack with the latest stemcell at that point in time

2. whenever there is a new release of the SUSE stemcell, all buildpacks bundled in kubecf get rebuilt on the new stemcell and CI will create a PR to update kubecf

The most pressing issue is that the pipeline in step 2 seems to only rebuild the version of the buildpack that is currently listed in kubecf. If there is a pending bump to the buildpack, that has not yet been merged, then this buildpack bump will get broken, unless we revert the stemcell bump for that particular buildpack version.

For example this has happened by merging #1157, which breaks both #1131 and #1135 

```
$ reg tags registry.suse.com/cap-staging/suse-ruby-buildpack
...
SLE_15_SP1-26.7-7.0.0_374.gb8e8e6af-1.8.19.1
SLE_15_SP1-26.7-7.0.0_374.gb8e8e6af-1.8.21.1
SLE_15_SP1-26.8-7.0.0_374.gb8e8e6af-1.8.19.1
SLE_15_SP1-27.1-7.0.0_374.gb8e8e6af-1.8.19.1
```

The whole rebuilding buildpack releases is not really necessary (explained in #1109). And we also don't seem to do it for the upstream buildpacks, but only for the SUSE ones.

So instead of somehow "fixing" this in the pipeline, I would like us to consider the proposal in #1109 

As a first step we could simply stop rebuilding buildpack images for stemcell upgrades. That would solve the immediate problem, but over time we may end up with multiple different stemcell layers in the various releases, which will increase the download times for the images. Therefore I would like the full proposal implemented, building buildpack images on alpine or scratch containers.

**Comment by jandubois** [comment]
As of today, the SUSE buildpacks for `dotnet-core` and `nginx` are behind the versions mandated by cf-deployment-13.9:
```
dotnet-core_buildpack   7          true      false    dotnet-core-buildpack-sle15-v2.3.9.1.zip       sle15
dotnet-core_buildpack   8          true      false    dotnet-core-buildpack-cflinuxfs3-v2.3.12.zip   cflinuxfs3

nginx_buildpack         17         true      false    nginx-buildpack-sle15-v1.1.7.1.zip             sle15
nginx_buildpack         18         true      false    nginx-buildpack-cflinuxfs3-v1.1.11.zip         cflinuxfs3
```

**Comment by jandubois** [comment]
There are no newer versions for the buildpacks:

```
$ reg tags registry.suse.com/cap-staging/suse-dotnet-core-buildpack
SLE-12SP4-15.ga717911-0.234-7.0.0_374.gb8e8e6af-2.3.0.2
SLE_15_SP1-21.3-7.0.0_374.gb8e8e6af-2.3.0.2
SLE_15_SP1-23.1-7.0.0_374.gb8e8e6af-2.3.0.2
SLE_15_SP1-23.15-7.0.0_374.gb8e8e6af-2.3.0.2
SLE_15_SP1-23.16-7.0.0_374.gb8e8e6af-2.3.0.2
SLE_15_SP1-23.17-7.0.0_374.gb8e8e6af-2.3.0.2
SLE_15_SP1-23.18-7.0.0_374.gb8e8e6af-2.3.0.2
SLE_15_SP1-23.19-7.0.0_374.gb8e8e6af-2.3.0.2
SLE_15_SP1-23.19-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-23.20-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-23.21-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-23.22-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-25.1-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-25.2-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-26.1-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-26.2-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-26.3-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-26.4-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-26.5-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-26.6-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-26.7-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-26.8-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-27.1-7.0.0_374.gb8e8e6af-2.3.9.1
SLE_15_SP1-27.2-7.0.0_374.gb8e8e6af-2.3.9.1

$ reg tags registry.suse.com/cap-staging/suse-nginx-buildpack
SLE-12SP4-15.ga717911-0.234-7.0.0_374.gb8e8e6af-1.1.2.1
SLE_15_SP1-21.3-7.0.0_374.gb8e8e6af-1.1.2.1
SLE_15_SP1-23.1-7.0.0_374.gb8e8e6af-1.1.2.1
SLE_15_SP1-23.1-7.0.0_374.gb8e8e6af-1.1.3.1
SLE_15_SP1-23.15-7.0.0_374.gb8e8e6af-1.1.3.1
SLE_15_SP1-23.16-7.0.0_374.gb8e8e6af-1.1.3.1
SLE_15_SP1-23.17-7.0.0_374.gb8e8e6af-1.1.3.1
SLE_15_SP1-23.18-7.0.0_374.gb8e8e6af-1.1.3.1
SLE_15_SP1-23.18-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-23.19-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-23.20-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-23.21-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-23.22-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-23.24-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-25.1-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-25.2-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-26.1-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-26.2-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-26.3-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-26.4-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-26.5-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-26.6-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-26.7-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-26.8-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-27.1-7.0.0_374.gb8e8e6af-1.1.7.1
SLE_15_SP1-27.2-7.0.0_374.gb8e8e6af-1.1.7.1
```

**Comment by thardeck** [comment]
> As of today, the SUSE buildpacks for `dotnet-core` and `nginx` are behind the versions mandated by cf-deployment-13.9:
> 
> ```
> dotnet-core_buildpack   7          true      false    dotnet-core-buildpack-sle15-v2.3.9.1.zip       sle15
> dotnet-core_buildpack   8          true      false    dotnet-core-buildpack-cflinuxfs3-v2.3.12.zip   cflinuxfs3
> 
> nginx_buildpack         17         true      false    nginx-buildpack-sle15-v1.1.7.1.zip             sle15
> nginx_buildpack         18         true      false    nginx-buildpack-cflinuxfs3-v1.1.11.zip         cflinuxfs3
> ```
At least the nginx one was updated on Github now https://github.com/SUSE/cf-nginx-buildpack/releases/tag/v1.1.15.1 , but for .net we should create a card because the pipeline is failing.

**Comment by fargozhu** [comment]
@thardeck the .Net card is #1284

**Comment by fargozhu** [comment]
@viovanov @thardeck can we close this one?

**Comment by thardeck** [comment]
@jandubois so as a work around we need to move the stemcell entry from `defaults` to each buildpack, and update them during the buildpack update or am I missing something?

**Comment by jandubois** [comment]
@thardeck I was under the impression that *all* buildpacks are supposed to be rebuilt automatically whenever a new stemcell is published. It may take a couple of hours, but then everything should continue to work with the latest shared stemcell.

@viovanov would know the details about the pipeline, and how it is configured.
