### ISSUE TITLE
Eirini Persi should use ReadWriteMany by default

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1173]
**Is your feature request related to a problem? Please describe.**
We need multiple app instances to be able to write to the same volume.

**Describe the solution you'd like**
The PVC created by the EiriniX extension should be ReadWriteMany by default.
Should fail fast if the configured storage class does not support ReadWriteMany.

**Comment by mudler** [comment]
just a note to clear things out: this is actually about the broker https://github.com/cloudfoundry-incubator/eirini-persi-broker/blob/master/broker/broker.go#L131  which is creating the PVC, the extension is just mounting them

**Comment by mudler** [comment]
WIP: https://github.com/cloudfoundry-incubator/eirini-persi-broker/pull/8
