### ISSUE TITLE
Spec for ReadWriteOnce in Eirini Persi

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1180]
**Is your feature request related to a problem? Please describe.**
ReadWriteMany storageclasses are not always available.
The kube style of one volume per app replica can be useful.

**Describe the solution you'd like**
There should be a config that allows the user to fallback to ReadWriteOnce, so they can use a StorageClass that doesn't have support for ReadWriteMany.
The plan name or the service name itself should denote the type of storage the user's getting.

**Describe alternatives you've considered**
Not doing this.

**Additional context**
#1173

**Comment by mudler** [comment]
doing this as part of #1173
