### ISSUE TITLE
Allow the rep to configure kernel parameters

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1181]
**Is your feature request related to a problem? Please describe.**
Configuration on the kubelets could cause the following message when trying to run apps:
```
11:45:49.704: [PROXY.0] [2020-07-30 18:45:49.703][70][critical][assert] [source/common/filesystem/inotify/watcher_impl.cc:28] assert failure: inotify_fd_ >= 0. Details: Consider increasing value of user.max_inotify_watches via sysctl
```

**Describe the solution you'd like**
Don't do this:
https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml#L45-L47

This does not exist anymore:
https://github.com/cloudfoundry-incubator/kubecf/blob/11797e25f3f1427f3b061d574eb255b795f23bf3/deploy/helm/kubecf/assets/operations/instance_groups/api.yaml#L164

We should look at these as well:
https://github.com/cloudfoundry-incubator/kubecf/blob/1e3b51ca95dd6469815089c809d1f2747a659a69/deploy/helm/kubecf/assets/operations/instance_groups/router.yaml#L26

https://github.com/cloudfoundry/diego-release/search?q=set_kernel_parameters&unscoped_q=set_kernel_parameters

**Comment by gaktive** [comment]
@mook-as noted this on AWS:

```$ tail /proc/sys/user/max_inotify_*
==> /proc/sys/user/max_inotify_instances <==
128
==> /proc/sys/user/max_inotify_watches <==
8388608
```

Places to look:
https://github.com/cloudfoundry/diego-release/blob/e22fda5d7367e606b20392b732431bf6ce82a164/jobs/rep/templates/set-rep-kernel-params.erb#L24-L26
https://github.com/cloudfoundry-incubator/kubecf/blob/6a25968a58af5e2f5b9809f2cc5373996d92c75c/deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml#L45-L47

**Comment by gaktive** [comment]
Mark also filed https://github.com/envoyproxy/envoy/issues/12383 upstream to ask for a more correct error.

**Comment by andreas-kupries** [comment]
Mainly @viovanov , plus @mook-as 

Questions:
- What was the k8s foundation (minikube, kind, AWS, CaaSP, ...) ?
- What kubecf release/commit was used, what cf-deployment version ?
- What log file contains the assert failure message ?

Is that generally something we should see with minikube (also) ?

----

When you (Vlad) said `This does not exist anymore`, before the reference to

https://github.com/cloudfoundry-incubator/kubecf/blob/11797e25f3f1427f3b061d574eb255b795f23bf3/deploy/helm/kubecf/assets/operations/instance_groups/api.yaml#L164

What does not exist exactly ?

Looking into kubecf commit 25ecfdf34d (current master), file `src/cf-deployment/cf-deployment.yml` I find:
  - IG `api` exists
  - Job `file_server` exists.
  - Release `diego` is version `2.47.0`.
  - Job in that release has the property `set_kernel_parameters` (end of `spec` file).
    https://github.com/cloudfoundry/diego-release/blob/2c9202c470bc6e28c448f6f9ce18356a2461cc7c/jobs/file_server/spec#L83-L85

Ditto all around for job `rep` in IG `diego-cell`.

----

Is the requested solution the removal of all the patch instructions setting all `set_kernel_parameters` properties to `false` ?

**Comment by andreas-kupries** [comment]
Trialed removal of the patches for `router`, `file_server`, and `rep`.
This breaks the containing IGs (`router`, `api`, `diego-cell`), they are not completing their initialization.

**Comment by andreas-kupries** [comment]
The last thing I confirmed Friday was that the writes in the garden init container were visible to the garden job container.

According to @viovanov setting kernel parameters in `rep` is ok because they affect the kernel of the __worker node__ running the entire `diego-cell` group of jobs, and are thus visible to `garden`, like in a BOSH setup.

**Comment by andreas-kupries** [comment]
Confirmed
