### ISSUE TITLE
Investigate regression on CI upgrade job

### ISSUE THREAD

**Issue by viccuad** [cloudfoundry-incubator/kubecf#1190]
**Is your feature request related to a problem? Please describe.**

Since around a week, the upgrade job seems to be failing:
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/upgrade-test-master/builds/58
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/upgrade-test-pr/builds/98

**Describe the solution you'd like**

Make the upgrade job green again, and mark its status as required.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by viccuad** [comment]
The `bosh-pre-start-cloud-controller-ng` pod fails with  `VCAP::CloudController::ValidateDatabaseKeys::EncryptionKeySentinelDecryptionMismatchError`

(see: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/spec/unit/lib/cloud_controller/validate_database_keys_spec.rb#L321-L343)

It may be a legit regression in kubecf. AFAIU the database key gers created on first run, from https://github.com/cloudfoundry-incubator/kubecf/blob/13ffb01dff8ab5eba16da54539b36e3b3b5f758e/deploy/helm/kubecf/values.yaml#L490-L498, which we aren't touching on the CI deployment. 

the failure always happens after a `helm upgrade`. Could it be that when upgrading, there's a recreation of the keys, but a mismatch in passing them?

**Comment by satadruroy** [comment]
FWIW, the raw data backup and restore for CCDB (kubecf cluster 1 -> kubecf cluster 2) also fails with the exact same error.

**Comment by viccuad** [comment]
The regression seems gone after the recent bumps.

But now, diego-cell pod fails with not enough space on the ephemeral storage space of /var/vcap/data/ grootfs. This only happens with upgrades from one version to another, not within the same version (maybe the node fills after fetching the container images of both versions?).

I think we need to either set taints for the GKE deployment, or change the size of the ephemeral_disk for GKE.

**Comment by jandubois** [comment]
> I think we need to either set taints for the GKE deployment, or change the size of the ephemeral_disk for GKE.

Yes, don't you just need a variant of #1285 for this?

**Comment by viccuad** [comment]
For the current regression, we were only missing changing the ephemeral_disk on the upgrade job also. Opened:  https://github.com/cloudfoundry-incubator/kubecf/pull/1308

**Comment by viccuad** [comment]
From concourse CI (but not manual testing when setting `epehemeral_disk`), I get `cannot delete '/var/vcap/data/grootfs/store': Device or resource busy`. Full output:

```
e489f178-bfd4-4839-7fb5-90e6b66055d5:/tmp/build/7c5e83d7/catapult/buildgke # cat /tmp/k9s-screens-root/gke_suse-225215_europe-west3-c_kubecf-pr-upgrade-0-0-152/scf-diego-cell-0-1599648239023777426.log
+ /var/vcap/jobs/garden/bin/bpm-pre-start
find: cannot delete '/var/vcap/data/grootfs/store': Device or resource busy
find: cannot delete '/var/vcap/data/grootfs/': Directory not empty
2020-09-09T10:42:43.100166194Z - running thresholder
The node running this cell doesn't have enough disk space. You requested 60000M but the disk is 59212M in size.

real    0m0.081s
user    0m0.027s
sys    0m0.023s
```

**Comment by viccuad** [comment]
After upgrading cf-operator from 2.4.0 to master, the `cc-deployment-updater` of the scheduler pod gets stuck not ready. On the deployment-updater I get `DatabaseDisconnectError (…) Mysql2::Error: WSREP has not yet prepared node for application use`. Only happens sometimes; a race condition with the state of the database pod after cf-operator prompts changes to the deployment.

It seems to be gone after merging https://github.com/cloudfoundry-incubator/kubecf/commit/3f2dd6780359147ca438e3bf13cbda4387b8917b.

**Comment by viccuad** [comment]
Opened https://github.com/cloudfoundry-incubator/kubecf/pull/1335 and https://github.com/cloudfoundry-incubator/kubecf/pull/1332, with those I'm getting green upgrades locally.

**Comment by viccuad** [comment]
The upgrade job is green, and is being successfully used to gate master.

I consider this card done, so I'm closing it (Nevertheless, this does not mean that regressions on upgrades don't need to be fixed. It seems that the only one around is https://github.com/cloudfoundry-incubator/kubecf/issues/1302).
