### ISSUE TITLE
Install instructions don't wait for operator to be running

### ISSUE THREAD

**Issue by manno** [cloudfoundry-incubator/kubecf#1194]
The install instructions, for example on the Github release page under "Quick Fresh Installation" are missing `--wait`.

```
cf-operator

helm install cf-operator \
  --namespace cf-operator \
  --set "global.singleNamespace.name=kubecf" \
  cf-operator.tgz
```

If users copy both `helm install` commands to fast the install fails:

> Error: Internal error occurred: failed calling webhook "validate-boshdeployment.quarks.cloudfoundry.org": Post https://cf-operator-webhook.kubecf.svc:443/validate-boshdeployment?timeout=30s: service "cf-operator-webhook" not found

Adding `--wait` to the operator install will safeguard against this.

Also
*  the file names contained in the bundle don't match the file names in the install instructions.
* the instructions don't tell the user to create the 'cf-operator' namespace first, helm 3 doesn't create release namespaces by default (`--create-namespace`)
* https://github.com/cloudfoundry-incubator/kubecf/blob/v2.3.0/doc/dev/general.md is missing `--wait`

**Comment by viccuad** [comment]
Thanks for listing the things here :).
I wonder about `--wait` with helm3, last time I tried it was not implemented.

**Comment by fargozhu** [comment]
@manno @viccuad I'll give it a try with the new 2.4.0 version and see how it handles.

**Comment by manno** [comment]
> Thanks for listing the things here :).
> I wonder about `--wait` with helm3, last time I tried it was not implemented.

Looks like it's implemented now: https://github.com/helm/helm/issues/5814

**Comment by fargozhu** [comment]
latest release updated and future ones will contain the --wait flag.
