### ISSUE TITLE
SUSE URLs should use https://

### ISSUE THREAD

**Issue by viccuad** [cloudfoundry-incubator/kubecf#1195]
**Describe the bug**

From Dirk, SUSE URLs for chart dependencies (an all) should use https://, not http:// 

**To Reproduce**

```
git grep "http://.*suse.com"  | tac
stable/kubecf/requirements.yaml:  repository: http://opensource.suse.com/bits-service-release2/
stable/kubecf/requirements.yaml:  repository: http://opensource.suse.com/eirini-release/
stable/kubecf/requirements.lock:  repository: http://opensource.suse.com/bits-service-release/
stable/kubecf/requirements.lock:  repository: http://opensource.suse.com/eirini-release/
```

**Expected behavior**

All urls with https://

**Environment**
 - Others

**Additional context**

**Comment by jandubois** [comment]
The subcharts will be removed in #1179, which will render this particular instance moot. Hopefully #1196 will catch other instances from appearing, so there is nothing left to do for this issue.
