### ISSUE TITLE
Diego cell info does not appear in Stratos

### ISSUE THREAD

**Issue by troytop** [cloudfoundry-incubator/kubecf#1198]
**Describe the bug**
"Cell information for this Cloud Foundry cannot be found." message in stratos instead of Diego cell info (admin view).

**To Reproduce**
Install KubeCF 2.2.2 with Diego enabled and Stratos 3.2.1 or 4.0 RC.

**Expected behavior**
Stratos should show which Diego cell an app instance is running on (app view) and show which apps are running on a given Diego cell (CF admin view).

**Environment**
 - KubeCF 2.2.2
 - on CaaSP 4.2 (on Open Stack) or on EKS
 - nginx-ingress

**Additional context**
Not sure if I've ever seen this working properly with KubeCF. Worked with SCF.

**Comment by gaktive** [comment]
Repro'd on EKS.
