### ISSUE TITLE
PRs to fix patches in their respective upstream projects

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#12]
The following patches should result in PRs to upstream projects.

- [x] [./eirini/opi/jobs/patch_opi_yml.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//eirini/opi/jobs/patch_opi_yml.sh)
- [x] [./eirini/opi/bpm/patch_bpm.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//eirini/opi/bpm/patch_bpm.sh)
- [ ] [./eirini/eirini-loggregator-bridge/bpm/patch_bpm.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//eirini/eirini-loggregator-bridge/bpm/patch_bpm.sh)
- [ ] [./bits/bits-service/jobs/patch_bits_config_yml.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//bits/bits-service/jobs/patch_bits_config_yml.sh)
- [ ] [./singleton-blobstore/blobstore/jobs/patch_blobstore_conf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//singleton-blobstore/blobstore/jobs/patch_blobstore_conf.sh)
- [ ] [./singleton-blobstore/blobstore/jobs/patch_blobstore_pre-start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//singleton-blobstore/blobstore/jobs/patch_blobstore_pre-start.sh)
- [ ] [./singleton-blobstore/blobstore/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//singleton-blobstore/blobstore/ig_resolver/patch_job_mf.sh)
- [ ] [./database/mysql/jobs/patch_pre-start-setup.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//database/mysql/jobs/patch_pre-start-setup.sh)
- [ ] [./api/dotnet-core-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/dotnet-core-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/dotnet-core-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/dotnet-core-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/nginx-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/nginx-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/nginx-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/nginx-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/cloud_controller_ng/jobs/patch_post-start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/cloud_controller_ng/jobs/patch_post-start.sh)
- [ ] [./api/cloud_controller_ng/jobs/remove_tee_output_to_sys_log.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/cloud_controller_ng/jobs/remove_tee_output_to_sys_log.sh)
- [ ] [./api/cloud_controller_ng/bpm/patch_bpm.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/cloud_controller_ng/bpm/patch_bpm.sh)
- [ ] [./api/staticfile-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/staticfile-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/staticfile-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/staticfile-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/php-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/php-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/php-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/php-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/nodejs-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/nodejs-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/nodejs-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/nodejs-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/cc_uploader/jobs/patch_pre-start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/cc_uploader/jobs/patch_pre-start.sh)
- [ ] [./api/routing-api/bpm/patch_bpm.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/routing-api/bpm/patch_bpm.sh)
- [ ] [./api/python-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/python-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/python-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/python-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/java-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/java-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/java-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/java-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/binary-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/binary-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/binary-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/binary-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/go-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/go-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/go-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/go-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/ruby-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/ruby-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/ruby-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/ruby-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./api/r-buildpack/jobs/create_bosh_pre_start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/r-buildpack/jobs/create_bosh_pre_start.sh)
- [ ] [./api/r-buildpack/ig_resolver/patch_job_mf.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//api/r-buildpack/ig_resolver/patch_job_mf.sh)
- [ ] [./diego-api/bbs/jobs/patch_bbs_json.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//diego-api/bbs/jobs/patch_bbs_json.sh)
- [ ] [./uaa/uaa/jobs/patch_uaa.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//uaa/uaa/jobs/patch_uaa.sh)
- [ ] [./uaa/uaa/jobs/patch_pre-start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//uaa/uaa/jobs/patch_pre-start.sh)
- [ ] [./diego-cell/garden/jobs/patch_post-start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//diego-cell/garden/jobs/patch_post-start.sh)
- [ ] [./diego-cell/cflinuxfs3-rootfs-setup/jobs/patch_pre-start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//diego-cell/cflinuxfs3-rootfs-setup/jobs/patch_pre-start.sh)
- [ ] [./diego-cell/rep/jobs/patch_pre-start.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//diego-cell/rep/jobs/patch_pre-start.sh)
- [ ] [./diego-cell/rep/jobs/patch_rep_json.sh](https://github.com/SUSE/kubecf/blob/master/bosh/releases/pre_render_scripts//diego-cell/rep/jobs/patch_rep_json.sh)

Each patch can be marked as complete once a PR has been opened upstream and linked in this issue.

**Comment by viovanov** [comment]
@aduffeck @f0rmiga @mook-as 
Here's an approach - each of the 4 of us do 1/day :)
1 🍺  for each opened PR

**Comment by f0rmiga** [comment]
Opened https://github.com/cloudfoundry-community/eirini-bosh-release/pull/68 and https://github.com/cloudfoundry-community/eirini-bosh-release/pull/69 along with the 2 kubecf ones referenced above.

**Comment by fargozhu** [comment]
I'll group the patches to avoid individual upstream PRs.

**Comment by viovanov** [comment]
We have individual issues.
