### ISSUE TITLE
Have a canonical place for all kubecf docs

### ISSUE THREAD

**Issue by viccuad** [cloudfoundry-incubator/kubecf#1200]
**Is your feature request related to a problem? Please describe.**

Currently, we have docs repeated here in __kubecf/doc__ folder (mainly for devs) and in kubecf.suse.dev (mainly for users).

**Describe the solution you'd like**

Have only 1 canonical place for (each type of) docs, to avoid repetition and getting out of sync. Possible approaches:

1. Move all docs to kubecf repo, use kubecf.suse.dev as a UI to edit them.
    Problem: kubecf master branch is protected, not easy to edit the docs on the file. Same happens if we put kubecf as a submodule of kubecf-docs.
   
2. Move all docs to kubecf-docs repo, with kubecf.suse.dev as UI

3. Move all docs to kubecf repo, with kubecf.suse.dev as UI, without editing capabilities.
   A pity.

**Describe alternatives you've considered**

Status quo.

**Additional context**

**Comment by mook-as** [comment]
I believe we still need different user-facing and developer-facing docs: users are deploying from charts, and won't have access to `make kubecf-apply` etc. (so it wouldn't make sense to share docs there).  There certainly are things that can be shared, of course, and we do need to do a better job of upgrading the user docs; however, I think merging them may be the wrong thing.

**Comment by viccuad** [comment]
I agree that we need different user-facing and developer-facing docs, but I think both of them could live in kubecf-docs repo (option 2).

**Comment by viccuad** [comment]
With the pointers of Jan, I rescind my comment, and I agree with having only user-facing docs on kubecf docs.

**Comment by viccuad** [comment]
On Retro & Planning we agreed on keeping tue current status-quo:
- user-facing docs on kubecf-docs repo served by kubecf.suse.dev
- dev-facing docs checked in cloudfoundry-incubator/kubecf

Closing the issue then.
