### ISSUE TITLE
CI is not building the correct buildpack images

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#1201]
We have updated kubecf to cf-deployment version `13.9.0`, which specifies nginx-buildpack version `1.1.11`.

This buildpack version is erroneously specified in `values.yaml` as `1.1.1`. Maybe because of a typo, but also, there is no image for `1.1.11` on Dockerhub for the latest stemcell (or any). The only versions that get built are `1.1.0` and `1.1.1`.

It's been 2 month since the `1.1.5` release has last been built. That release is used by the currently released version of kubcf:

https://hub.docker.com/r/cfcontainerization/nginx-buildpack/tags?page=1&ordering=last_updated

So why do we keep building `1.1.0` and `1.1.1`? Why did we stop building `1.1.5`. Why did we never build the later releases like `1.1.11`? Or the latest release, which is `1.1.12`?

I wonder if this is related to #1164, but maybe not, as that bug is about SUSE buildpacks, and this one is about cflinuxfs3.

I wonder if implementing #1109 is not a more sensible way to address our various buildpack CI issues than fixing up the current setup.

Since we have no downgraded the nginx-buildpack compared to the previous release, I would consider this a release blocker for the next release.

**Comment by jandubois** [comment]
Same thing seems to have happened to the `r-buildpack`. It was at version `1.1.1` in kubecf-2.3.0 but CI only builds `1.0.13` and `1.1.0`. cf-deployment has it at `1.1.7`, but in the bump it was downgraded to `1.1.0`, which is the latest version we have with the current stemcell.

**Comment by viovanov** [comment]
We should have correct documentation in the [how to bump file](https://github.com/cloudfoundry-incubator/kubecf/blob/master/doc/cf_deployment/bump.md) as part of this issue.

**Comment by jandubois** [comment]
@viovanov has updated the pipelines to build the missing images. Buildpacks have been updated in c09ce9f.
