### ISSUE TITLE
Auto creation of ingress should not include bare domain, just *.domain

### ISSUE THREAD

**Issue by troytop** [cloudfoundry-incubator/kubecf#1205]
**Describe the bug**
Setting `features.ingress.enabled=true` creates two ingress routes/hosts automatically: `mydomain.com` and `*.mydomain.com`
This prevents the admin from using `mydomain.com` for anything else (e.g. the company website, or Stratos UI)

Workaround: Manually edit the ingress once it is created to remove the bare domain entries. This gets overwritten with each `helm update` and has to be repeated.

**Expected behavior**
Expect automatic setup of the `*.domain.com` wildcard for endpoints like `uaa` and `api` but not the basename (which is not required for CF.

**Comment by f0rmiga** [comment]
With Helm 3, the workaround should be kept around: https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches, it shouldn't happen. @troytop Has this behaviour been observed with Helm 3?

**Comment by f0rmiga** [comment]
In any case, I opened PR #1213 to fix this.
