### ISSUE TITLE
concourse.suse.dev: Investigate why concourse-worker statefulset couldn't connect

### ISSUE THREAD

**Issue by viccuad** [cloudfoundry-incubator/kubecf#1211]
**Is your feature request related to a problem? Please describe.**

Problem:

`concourse-worker` statefulset on ns `concourse` was trying to reach TSA at the service `concourse-web` (which doesn't have an sshd listening in tcp 2222), instead of trying reach `concourse-web-worker-gateway:2222`, which does have an sshd listening.
We fixed it by editing the `concourse-worker` statefulset, and pointing the env `CONCOURSE_TSA_HOST` from `concourse-web:2222` to `concourse-web-worker-gateway:2222`.

This may have happened because when upgrading the helm chart to recreate the workers, I mistakenly forgot to `helm update`, therefore I did a downgrade from `6.4.0` to `6.0.0`, which failed with:
```
$ helm upgrade --namespace concourse concourse concourse/concourse --values values.yaml                                                                                                                                                               
UPGRADE FAILED
Error: Service "concourse-web" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
Error: UPGRADE FAILED: Service "concourse-web" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```
And then an upgrade from `6.0.0` to `6.4.1`, which suceeded.

**Describe the solution you'd like**

We need to investigate why this has happened, as we don't want it to happen again if we `helm upgrade`.

**Describe alternatives you've considered**

Uninstall the concourse chart and reinstall cleanly, redeploying the pipelines and losing history.

**Additional context**

**Comment by fargozhu** [comment]
@viccuad I am closing 'cause we all agree to move quickly to GHA and leave Concourse.
