### ISSUE TITLE
Do not generate values.yaml in github actions CI

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/kubecf#1220]
Right now github actions workflow is generating values.yaml. We need to stop doing that. May be add a static values.yaml in tool folder.
https://github.com/cloudfoundry-incubator/kubecf/pull/1217#discussion_r470658355

**Comment by fargozhu** [comment]
@prabalsharma @viovanov I am closing this one 'cause the #1231 contains more detailed information.
