### ISSUE TITLE
grootfs cleanup does not work correctly

### ISSUE THREAD

**Issue by univ0298** [cloudfoundry-incubator/kubecf#1224]
**Describe the bug**
We observed that the contents of /var/vcap/data/store were not cleaned up when a cell pod restarts. This led to garden errors like `guardian.create.volume-creator.image-plugin-create.grootfs.create.groot-creating.making-image.overlayxfs-creating-image.applying-quotas.run-tardis.tardis.set-quota.set-quota.setting-quota-to-project-id-failed` , caused by stale information about projectids being carried over from a previous 'life' of the data directory from a previous pod. 

Looking at the bpm-pre-start-garden container logs we can see an error where the clean did not work correctly in the pre-start

**To Reproduce**
Restart a cell pod and then look at the contents under /var/vcap/data/grootfs of the replacement pod that starts. You will see contents that are older than the lifetime of the new pod, demonstrating that the cleanup did not succeed. You can also look at the bpm-pre-start-garden logs and you will see an error from the find command, saying "paths must precede expression". For example:

```
kubectl -n kubecf logs diego-cell-3 bpm-pre-start-garden
+ /var/vcap/jobs/garden/bin/bpm-pre-start
find: paths must precede expression: bin
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
2020-08-17T16:58:16.630871991Z - running thresholder
2020-08-17T16:58:16.637805608Z - done
real	0m0.059s
user	0m0.026s
sys	0m0.010s
```

**Expected behavior**
After a pod restarts, there should be no error in the bpm-pre-start-garden log and the /var/vcap/data/grootfs contents should all be created since the pod restarted.

**Environment**
 - CF Version: 13.9
 - Component/Plugin Name
 - Others

**Additional context**
Here is the code in question: https://github.com/cloudfoundry-incubator/kubecf/blob/master/bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_pre-start.sh#L18

and here is the change that added this grootfs cleanup: https://github.com/cloudfoundry-incubator/kubecf/commit/3d0562919480c6b40bf09a21221f625f72d46e0c

slack discussion: https://cloudfoundry.slack.com/archives/CQ2U3L6DC/p1597411497472300

**Comment by viovanov** [comment]
should be fixed by #1264
