### ISSUE TITLE
Set up a cron job on the concourse EKS cluster to recycle the workers

### ISSUE THREAD

**Issue by satadruroy** [cloudfoundry-incubator/kubecf#1229]
Concourse worker nodes need recycling every week as they run out of space every ~7 days. We should set up a cron job to clean out the PVCs (`concourse-work-dir-concourse-worker-<n>`) and recycle the pods (`concourse-worker-<n>`) in `concourse` namespace every 7 days.

**Comment by fargozhu** [comment]
@satadruroy I am closing since we all agree to move quickly from Concourse to GHA.
