### ISSUE TITLE
Remove extra things in the values.yaml schema for catapult

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#1240]
**Describe the bug**
In #1202 we're introducing a JSON schema for `values.yaml` to ensure that we have reasonable settings.  Unfortunately, currently `catapult` generates a configuration that trips on the schema (because it adds extra things — probably things that did stuff at some point, or maybe configuration for Stratos?

For now, we're temporarily relaxing the schema for expediency in @d8f30352a307b9fc6e914cd5cb606911f0a4ea43; we should revert that once catapult can generate conforming configuration.  Or if we move to something that isn't catapult that does the same.

**To Reproduce**
Deploy kubecf using catapult-generated configuration.

**Expected behaviour**
Successful deployment.

**Actual behaviour**
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
kubecf:
- kube: Additional property organization is not allowed
- kube: Additional property pod_cluster_ip_range is not allowed
- kube: Additional property registry is not allowed
- kube: Additional property service_cluster_ip_range is not allowed
```

**Environment**
 - CI (https://concourse.suse.dev/builds/33998)
 - catapult SUSE/catapult@782c1af643fa6d03337a26434ddcd7613441774a

**Comment by viccuad** [comment]
This seems to be fixed with the merge of https://github.com/cloudfoundry-incubator/kubecf/pull/1430

**Comment by fargozhu** [comment]
@mook-as can you confirm please and close it if so?

**Comment by mook-as** [comment]
Yep, d8f30352a307b9fc6e914cd5cb606911f0a4ea43 was essentially reverted in #1430; closing.
