### ISSUE TITLE
Set GIT_PAGER=cat inside CI pipelines

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#1248]
For some reason `git` seems to believe to have a semi-functional terminal available when running under concourse.

That way it can hang indefinitely, waiting for input (example from running `httplint` and finding an error):

```
URLS should not start with 'http://' (with excepted domains listed in .http_exceptions)
WARNING: terminal is not fully functional
-  (press RETURN)
```

We don't want to affect developer use of the scripts, so adding `GIT_PAGER=cat` to CI should be the best way to avoid this problem in general, and not just for this particular script.

**Comment by andreas-kupries** [comment]
Is this about the CI definitions under `.github/workflows` ? (Looks to be github actions ?)

**Comment by jandubois** [comment]
> (Looks to be github actions ?)

This was about the concourse pipeline, but it could also apply to Github Actions.

But otherwise, yes, this is about `git diff` or `git grep` using the pager, waiting for the user to press a key before continuing. Under CI it will just hang until the runner times out.

**Comment by andreas-kupries** [comment]
Given our work on switching to GHA I would say we should make this GHA and leave Concourse behind.
