### ISSUE TITLE
No subsets generated for service diego-api endpoints when diego-api is in passive mode

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry-incubator/kubecf#1254]
A classic bosh cf and a kubecf are connected to the same database. Classic bosh cf only has one diego-api VM and kubecf has only one diego-api pod `diego-api-0`.

Steps to reproduce:
1. Classic bosh cf diego-api jobs are started first, so it's in active mode.
2. Then kubecf diego-api-0 pod is started. As it can't get the bbs lock, it's in passive mode.
3. kubecf diego-api-0 pod starts successfully.
4. But kubecf `auctioneer-0` and `scheduler-0` pods fail to start as service address `diego-api.kubecf.svc.cluster.local` (DNS alias for `locket.serivce.cf.internal`) is not accessible. The reason is no subsets generated for service `diego-api` endpoints:
```
# kubectl -n kubecf describe endpoints diego-api
Name:         diego-api
Namespace:    kubecf
Labels:       quarks.cloudfoundry.org/deployment-name=kubecf
              quarks.cloudfoundry.org/deployment-version=1
              quarks.cloudfoundry.org/instance-group-name=diego-api
              service.kubernetes.io/headless=
Annotations:  <none>
Subsets:
Events:  <none>
```
The expected one is like this:
```
# kubectl -n kubecf describe endpoints diego-api
Name:         diego-api
Namespace:    kubecf
Labels:       quarks.cloudfoundry.org/deployment-name=kubecf
              quarks.cloudfoundry.org/deployment-version=1
              quarks.cloudfoundry.org/instance-group-name=diego-api
              service.kubernetes.io/headless=
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2020-08-15T03:52:17Z
Subsets:
  Addresses:          172.17.53.227
  NotReadyAddresses:  <none>
  Ports:
    Name          Port  Protocol
    ----          ----  --------
    cell-bbs-api  8889  TCP
    locket        8891  TCP
Events:  <none>
```

Is this work as designed for passive mode?

**Comment by mook-as** [comment]
As far as I can tell, that's… kind of expected? Sharing the same internal database across two clusters (whether BOSH or KubeCF) isn't expected to work, since as you found out locket uses the database to handle locking.  As the cluster has no available *active* diego-api replicas, it's kind of stuck.

**Comment by JimmyMa** [comment]
I talked with @gu-bin , and I think it's woked as design to have no endpoints for passive diego-api, and only have endpoint for active diego-api Pod. 

Close this issue.
