### ISSUE TITLE
Update pipelines that bump stemcells and buildpacks to update the new locations

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1262]
## Acceptance Criteria

- update the buildpacks (SLE15) bump pipeline to write to the new files
- update the stemcell bump pipeline to write to the new files
- pause the pipelines that bump stuff for SCF
- use https://www.conventionalcommits.org/en/v1.0.0/ structure for prs

**Files**
https://github.com/cloudfoundry-incubator/kubecf/blob/master/chart/config/sle15.yaml

Follow-up of #1086, needed for #1164

**Comment by thardeck** [comment]
https://github.com/cloudfoundry-incubator/kubecf/pull/1315
