### ISSUE TITLE
Make it clear that diego cells should live on tainted nodes

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1287]
Diego cells should not live next to other Kubernetes workloads.
They are privileged, they set kernel parameters and require node disk storage.

## Acceptance Criteria

- [x] there are docs explaining how to set node taints for nodes
- [ ] setting diego cell tolerations is easy (should be set using a key in `values.yaml`)

**Comment by gaktive** [comment]
Can docs rely on https://github.com/cloudfoundry-incubator/kubecf/pull/1264 for help here? Or would other investigation be needed by engineering to flesh this out before they formalize a write-up?

**Comment by jandubois** [comment]
I don't think we have any mechanism for setting tolerations on instance groups. We have #607 open, and even that may require additional support from Quarks before it can be implemented.

**Comment by andreas-kupries** [comment]
Ref cloudfoundry-incubator/kubecf-docs/pull/22 for a tutorial.

**Comment by andreas-kupries** [comment]
Note : @jandubois  thinks
> 1287 is pure user-docs (it is about deploying in production). It should have a corresponding Jira ticket to make sure it gets into the CAP-2.1 docs as well. Please create that Jira ticket.

**Comment by andreas-kupries** [comment]
> That example already shows exactly what you need for diego-cells; you just need to add some docs entry to explain why diego cells need their own dedicated nodes (privileged, kernel parameters, large local emptyDir volumes) and then point to the tutorial Mark already wrote

**Comment by andreas-kupries** [comment]
CAP ticket https://jira.suse.com/browse/CAP-1567

**Comment by mook-as** [comment]
The associated CAP stuff is in https://github.com/SUSE/doc-cap/issues/961 — so there's nothing else left for KubeCF, as far as I can tell. Closing as resolved.
