### ISSUE TITLE
diego-cell pod  does not start completely 

### ISSUE THREAD

**Issue by dheerajinganti** [cloudfoundry-incubator/kubecf#1297]
I took the latest 2.4.0 release and tried to deploy from scratch. However, diego-cell doesn’t start fully with rep-rep container going into crashloop with below error

![image](https://user-images.githubusercontent.com/56450649/92310694-6aa94100-efce-11ea-94c5-117045ad17d8.png)

k8s version: 1.17.7
node os version: CentOS Linux release 7.8.2003 (Core)

**Comment by jandubois** [comment]
I think this is a kernel issue; a recent change to garden-runc-release means it now requires Kernel version 4.5 or later:

https://github.com/concourse/concourse/issues/5711#issuecomment-638224176

I suspect that means you will need to move to CentOS 8 to get kubecf working.

**Comment by jandubois** [comment]
> I suspect that means you will need to move to CentOS 8 to get kubecf working.

Forgot to mention: garden-runc-release is only used by Diego, so if switching to a current Linux kernel is an issue, then maybe you could try switching to Eirini instead.

**Comment by dheerajinganti** [comment]
Thank you.  Yes, I am able to run Eirini with current centos 7.8 version. However strangely. I am unable to pull images from any docker registry. I am able to push apps though with buildpcks. Should I open a new issue for the same?

**Comment by jandubois** [comment]
> I am unable to pull images from any docker registry. [...] Should I open a new issue for the same?

Yes, please!

I can't remember testing docker apps from private repos, but it worked for apps hosted on Docker Hub as long as they used port 8080 to communicate: https://github.com/cloudfoundry-incubator/eirini-release/issues/147

**Comment by dheerajinganti** [comment]
Thank you for the confirmation. This explains why pushing docker images from my private registry is not working with 2.3.0. I am using different port than 8080
For 2.4.0 docker push doesn't work at all. Created an issue #1304 .
