### ISSUE TITLE
api-0 pod is stuck at 31/63 after kubecf upgrade or restart of nodes

### ISSUE THREAD

**Issue by dheerajinganti** [cloudfoundry-incubator/kubecf#1302]
I have been able to reproduce api-0 pod going into crashloop mode consistently when I go for helm upgrade or for some reason I have to restart k8s nodes. In both cases I see the same error with api-0 pod. I re-deploy every-time this happens. Please See below snapshots for logs and state of all pods. I am using Diego with a very simple values files. Am I missing anything, any support/help/links will be helpful.

my environment
k8s version: 1.17.7
node os version: CentOS Linux release 7.8.2003 (Core)
kubecf : 2.3.0

![image](https://user-images.githubusercontent.com/56450649/92501385-185d5f80-f21c-11ea-91a9-6d44fc5ec97d.png)

![image](https://user-images.githubusercontent.com/56450649/92501443-2f9c4d00-f21c-11ea-83ee-e6cc6bb7fbf8.png)

![image](https://user-images.githubusercontent.com/56450649/92501460-37f48800-f21c-11ea-93ef-3952c902c31c.png)

**Comment by fargozhu** [comment]
look similar with #1190

**Comment by viccuad** [comment]
Hello,

Thanks for reporting this. Could you share to which KubeCF version are you upgrading to? I am guessing you are performing an upgrade from 2.3.0 to 2.4.0, correct?

On a related note, this problem seems fixed when upgrading from 2.4 to current master.

**Comment by dheerajinganti** [comment]
I am not trying 2.3.0 to 2.4.0 rather I am on 2.3.0. I have seen this error in below scenarios

- When I restart my k8s worker nodes
- When I change values.yaml file e.g. to enable auto scaler or other configurations.

**Comment by viccuad** [comment]
I deployed a 2.3.0, which then I upgraded enabling autoscaler, and I can reproduce. But what I caught was that at some moment I had 4 ig pods running. I wonder if I upgraded when a previous upgrade was running, and that invalidates my test.

**Comment by dheerajinganti** [comment]
I performed helm upgrade just once. I also saw multiple ig pods starts and they terminate and start other pods. So you see pods restarting multiple times. I also see multiple database seeder Jobs.

**Comment by jandubois** [comment]
> at some moment I had 4 ig pods running

That is https://github.com/cloudfoundry-incubator/quarks-operator/issues/750. I believe the fix is not in 2.3.0 though.

However, it was my understanding that the multiple ig jobs would only cause extended downtime, but eventually everything should still come back up.

**Comment by dheerajinganti** [comment]
Everything doesn't come up since api pod is stuck with encryption error which means cf is totally down.

**Comment by viovanov** [comment]
@dheerajinganti can you try upgrading to 2.4.0 ?

**Comment by dheerajinganti** [comment]
Sure, will try upgrading to 2.4.0 and will post results.

**Comment by satadruroy** [comment]
FWIW, upgrading from 2.2.3 to 2.4.0 (with the corresponding operator upgrades) also results in CLBO for api-0 (with a CLBO for diego-cell as well).

**Comment by fargozhu** [comment]
@dheerajinganti I am closing this one but feel free to reopen if the problem persists.
