### ISSUE TITLE
Eirini is unable to pull docker apps from public registry

### ISSUE THREAD

**Issue by dheerajinganti** [cloudfoundry-incubator/kubecf#1304]
I am using 2.4.0 kubecf and enabled Eirini. I am unable to push any docker images from public registry. Simple redis push fails. I am using below to push redis image.

cf push redis-docker --docker-image redis. 

Looks like docker push is broken which works fine on 2.3.0.

**Comment by viovanov** [comment]
This might be fixed with the latest bump to Eirini. #1296

**Comment by mudler** [comment]
Not blocked anymore as the bump was merged, having a look on it

**Comment by mudler** [comment]
Still failing with current kubecf master (Eirini 1.8.0) 
```
Pushing app redis-docker to org system / space tmp as admin...
Getting app info...
Updating app with these attributes...
  name:                redis-docker
  docker image:        redis
  disk quota:          1G
  health check type:   port
  instances:           1
  memory:              1G
  stack:               sle15
  routes:
    redis-docker.172.17.0.2.nip.io

Updating app redis-docker...
Mapping routes...

Staging app and tracing logs...
Error staging application: Staging error: failed to get image config: failed to fetch image metadata: failed to get image source: pinging docker registry returned: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority
FAILED
```

**Comment by mudler** [comment]
With a base-image which has ca-bundle that error goes away, but latest loggregator-bridge changes now prevents the app to start correctly:

```cf push test-docker --docker-image viovanov/node-env-tiny                                                                                                                                                       
Pushing app test-docker to org system / space tmp as admin...
Getting app info...
Creating app with these attributes...
+ name:           test-docker
+ docker image:   viovanov/node-env-tiny
  routes:
+   test-docker.172.17.0.2.nip.io

Creating app test-docker...
Mapping routes...

Staging app and tracing logs...
   
Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs test-docker --recent' for more information
FAILED
```

The entrypoint is mutated but shouldn't, opened also https://github.com/cloudfoundry-incubator/eirini/issues/112 to have a better way to distinguish applications pushed from docker images with Eirini

**Comment by mudler** [comment]
opened https://github.com/cloudfoundry-incubator/eirini-loggregator-bridge/pull/27 to fix the loggregator-bridge issue

**Comment by dheerajinganti** [comment]
Issue still persist, tested with 2.5.0
Error staging application: Staging error: failed to get image config: failed to fetch image metadata: failed to get image source: unable to retrieve auth token: invalid username/password
above error in spite of providing right docker reg creds. docker pull works fine with the same creds.

Tested with public images, however issue still persist
[API/0] ERR Failed to stage build: failed to get image config: failed to fetch image metadata: failed to get image source: pinging docker registry returned: Get https://registry-1.docker.io/v2/: dial tcp 52.1.121.53:443: i/o timeout
