### ISSUE TITLE
Latest stemcell 27.5 does not work

### ISSUE THREAD

**Issue by thardeck** [cloudfoundry-incubator/kubecf#1356]
The [OBS stemcell](https://build.opensuse.org/package/show/Cloud:Platform:Fissile-Stemcell/fissile-stemcell) was [updated](https://build.opensuse.org/request/show/816074) some time ago but did not build because of the missing new requirement `bosh-cli`. I have linked the missing package to the [dependency repo](https://build.opensuse.org/project/show/Cloud:Platform:Fissile-Stemcell:dependencies) but kubecf does not come up with [newly build stemcell](https://github.com/cloudfoundry-incubator/kubecf/issues/1348).

It might be related to the newly introduced [quarks-container-run](https://build.opensuse.org/request/show/811621).

(Edit by @mook-as: fixed link)

**Comment by mook-as** [comment]
The stemcell appears to work fine locally, except that we do not have a `suse-python-buildpack` image for 1.7.21.1; bumping that back to 1.7.20.1 works for me.

I assume the proper fix is to build a newer buildpack image, though.
