### ISSUE TITLE
Database-seeder pod is not deleted

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#1392]
**Describe the bug**

After deploying kubecf 2.5.0 with success, I proceed to the tear-down of KubeCF 

```
# helm uninstall kubecf --namespace kubecf
```

but I notice that the `database-seeder` is not deleted ever.

```
$ kubectl get pods --namespace kubecf
NAME                                     READY   STATUS      RESTARTS   AGE
database-seeder-25b239b49d162e7c-xhrmr   0/2     Completed   0          28m
```

**To Reproduce**

Deploy kubecf 2.5.0 basic setup (Diego scheduler) using the GitHub bundle and through helm command and uninstall after.

**Expected behavior**

To have the `kubecf` namespace clean of all created resources

**Environment**
- KubeCF Bundle: 2.5.0
- Helm: version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
- GKE: 1.17.9-gke.150

**Additional context**

**Comment by mook-as** [comment]
This will need to be looked at _after_ we merge #1388 as I updated the labels for the job there and also we'd get… _fun_ conflicts otherwise.

**Comment by fargozhu** [comment]
I can't see the issue at least on 2.5.8 so i am closing it.
