### ISSUE TITLE
how do I get started on kind

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#14]
- [ ] prerequisites
- [ ] installation
- [ ] publishing (domains, load balancers, etc.)

**Comment by fargozhu** [comment]
@viccuad have you try it?

**Comment by fargozhu** [comment]
check if the article helps
https://medium.com/@jmpinto/deploying-cloudfoundry-on-a-local-kubernetes-9103a57bf713

**Comment by fargozhu** [comment]
fixes https://github.com/SUSE/kubecf-docs/pull/3
