### ISSUE TITLE
Publishing master builds is failing on concourse

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/kubecf#1412]
**Describe the bug**
Master builds are failing on concourse since 8th September 2020 
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/publish-master/builds/24

**Comment by prabalsharma** [comment]
this makes running cap-pre-release pipelines moot as they are not testing latest master on nightly basis (just an old kubecf bundle).

**Comment by jandubois** [comment]
I think all that is wrong is a missing `v` in the regex in front of the version number.

**Comment by fargozhu** [comment]
@viccuad this should be fixed by #1300 , right?
