### ISSUE TITLE
Unable to deploy KubeCF 2.5.6/7/8

### ISSUE THREAD

**Issue by sourix** [cloudfoundry-incubator/kubecf#1476]
**Describe the bug**
Unable to deploy KubeCF 2.5.6/7/8 on AWS EKS.
The cf-apps-dns pod remains stuck in the pod initialization stage forever.
Describing the pod shows the following log
MountVolume.SetUp failed for volume "client-tls" : secret "var-cf-app-sd-client-tls" not found

**To Reproduce**
Use a simple overrides file for values.yml and deploy cf-operator and kubecf.

#####overrides.yaml######
`
system_domain: <mydomain>
kube:
  storage_class: gp2
credentials:
  cf_admin_password: <strong_pass>
  uaa_admin_client_secret: <yet_another_strong_pass>
features:
  autoscaler:
    enabled: false
`
###########

helm3 install cf-operator \
--namespace cf-operator \
--set "global.operator.watchNamespace=kubecf" \
https://s3.amazonaws.com/cf-operators/release/helm-charts/cf-operator-6.1.15%2B0.g89a56300.tgz

helm3 install kubecf \
  --namespace kubecf \
  --values overrides.yaml \
  ./kubecf-v2.5.6.tgz

**Environment**
 - KubeCF Version 2.5.6
- cf-operator 6.1.15
 - AWS EKS (Kubernetes 1.17.9)
 - OS Image -- Amazon Linux 2
- Container runtime -- docker://19.3.6

**Additional context**
**Please note:- KubeCF 2.2.2 deployment works and always succeeds on the same cluster.**

**Comment by sourix** [comment]
Used the following override `--set "global.singleNamespace.name=kubecf"`
instead of `--set "global.operator.watchNamespace=kubecf"`

With that I'm able to deploy KubeCF 2.5.8

**Comment by AbelNavarro** [comment]
I found exactly the same problem. Thanks for the fix @sourix . I disagree though on closing the ticket without an actual fix. I mean, either documentation or code needs an update.

**Comment by sourix** [comment]
@AbelNavarro I closed the issue because I figured I was using an incorrect override with my deployments. The KubeCF documentation at [https://kubecf.io/docs/deployment/kubernetes-deploy/#deployment](https://kubecf.io/docs/deployment/kubernetes-deploy/#deployment) does provide an example that lists the correct override `--set "global.singleNamespace.name=kubecf"`

**Comment by AbelNavarro** [comment]
I see, I was using old documentation. Thanks for the pointer.
