### ISSUE TITLE
Move BOSH Images to GitHub Registry

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#1489]
**Is your feature request related to a problem? Please describe.**

DockerHub free tier is ending...

**Describe the solution you'd like**

We must move all the BOSH images into GitHub registry by changing the respective [pipelines](https://github.com/cloudfoundry-incubator/quarks-ci/tree/master/pipelines).

**Describe alternatives you've considered**

Paying Docker...nah!

**Additional context**
N/A

**Comment by viovanov** [comment]
The images have been moved, we have to consume them from GHCR now.

**Comment by viccuad** [comment]
Done in https://github.com/cloudfoundry-incubator/kubecf/pull/1581, closing.
