### ISSUE TITLE
Move PXC Images to GitHub Registry

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#1490]
**Is your feature request related to a problem? Please describe.**

DockerHub free tier is ending...

**Describe the solution you'd like**

We must move all the existent PXC images into GitHub registry by changing the respective pipelines.

**Describe alternatives you've considered**

Paying Docker...nah!

**Additional context**

**Comment by fargozhu** [comment]
https://github.com/SUSE/pxc-docker

**Comment by mook-as** [comment]
This will only involve changing the registry location; it will _not_ involve changing the pipeline to be GitHub Actions.

Relevant repository: https://github.com/SUSE/pxc-docker
Relevant pipeline: https://github.com/SUSE/cloudfoundry/tree/master/ci/pipelines/publish-pxc-docker

**Comment by fargozhu** [comment]
Quarks team published today a short guide in how to switch to GHCR.
https://docs.google.com/document/d/1R7xCbYhNCzTa0lEC7wGsw9CcG7xclBGYOZTrmrb2HMg/edit

**Comment by andreas-kupries** [comment]
Notes: @viovanov believes pipeline on `suse.de` (behind firewall) is not required, asks to move that pipeline to `suse.dev`.

**Comment by andreas-kupries** [comment]
Note: in the GHA test it becomes clear why `.de`. The docker file accesses `http://download.suse.de/ibs/SUSE:/SLE-15:/GA/standard/SUSE:SLE-15:GA.repo` which is behind the firewall.

**Comment by andreas-kupries** [comment]
Per discussion on cap-internal going with GHA and/or OBS is non-trivial.
Giving the concourse pipeline another look.

**Comment by andreas-kupries** [comment]
Results so far.

## Requirements

  - Pipeline has to know the GHCR credentials (user, and password).

Then it is just adding/switching to a `docker-image` resource for GHCR.

## Summary

Right now I am trending towards doing 1, storing it like all the other
creds, in the SUSE cloudfoundry/secure/.... The most simple, will
work, give us progress on the ticket.

## Possible solutions

### 1: SUSE cloudfoundry secrets

  - Place the credentials into the cloudfoundry/secure/concourse-passwords.yaml.gpg

  - Resolve when re-flying the pipeline

  - Bad: The password is visible in the pipeline.

### 2: Concourse credential manager

  - Use a github credentials manager as store for the data.

  - Good: The data stays out of the pipeline.

  - Good: The credentials to access to volt are also outside the
    pipeline (part of the CM setup).

  - Bad: The CM for Vault instances supports only kv1.
    Our volt is kv2. We would have to copy all the existing secrets.

### 3: Concourse resource for vault access

  - https://github.com/wfernandes/vault-resource

  - Bad: Supports only kv1 also

### 4: Pipeline step

  - Create a resource to get `vault` cli.

  - Create a pipeline step which uses the above to pull the GHCR
    credentials.

  - Bad: Like with 1 credentials are visible in the pipeline.
    Different to 1 here we expose the Volt credentials, not the GHCR
    credentials. well, that said with Volt creds the GHCR creds are
    only a step away.

  - Bad: This is essentially like 1, with added complexity.

**Comment by andreas-kupries** [comment]
Draft change for the concourse pipeline: https://github.com/SUSE/cloudfoundry/pull/201

TODO: Filling in the credentials.
- Currently unable to reach volt (reach ok now, needs unsealing) to get current cred info
- Editing the concourse-secrets via blackbox-edit fails for me (I can decrypt, encrypt after change then fails).

**Comment by thardeck** [comment]
>     * Editing the concourse-secrets via blackbox-edit fails for me (I can decrypt, encrypt after change then fails).

That usually happens when you are missing a required gpg key or one of them has timed out.

**Comment by andreas-kupries** [comment]
@thardeck Oh, so for decrypt I need only my key, for encryption I need all of them, i.e. for everybody who has (should have) access ? How do I fix this ? (And/or how do I determine which of the possibilities is the issue ?)

**Comment by thardeck** [comment]
> @thardeck Oh, so for decrypt I need only my key, for encryption I need all of them, i.e. for everybody who has (should have) access ?

Exactly.

> How do I fix this ? (And/or how do I determine which of the possibilities is the issue ?)

The admins are listed in `blackbox-admins.txt`. If one has timed out or not in the team anymore you can remove it.

**Comment by andreas-kupries** [comment]
Thank you.

**Comment by andreas-kupries** [comment]
Ok. Should we go with concourse, we can start with PR SUSE/cloudfoundry/pull/201 . Modified the pipeline, plus necessary changes to the concourse secrets.

**Comment by viccuad** [comment]
Thanks for the PR! with that merged, and the pipeline flown,  I think this card can be closed.

See latest job build-pxc-docker run: https://concourse.suse.de/teams/main/pipelines/publish-pxc-docker/jobs/build-pxc-docker/builds/17
