### ISSUE TITLE
Pushing go apps results in failed to upload buildpack cache error

### ISSUE THREAD

**Issue by dheerajinganti** [cloudfoundry-incubator/kubecf#1498]
A simple go app push results into an build cache error, see below. This was working fine earlier with 2.5.4. I get this error only with go apps. Other apps such as nodejs, java and python works fine. 

Starting app webapi in org xxxx / space dev as admin...
2020/10/20 14:32:08 Cleaning cache dir
2020/10/20 14:32:08 Detecting buildpack
2020/10/20 14:31:57 Installing dependencies
-----> Go Buildpack version 1.9.19.1
**WARNING** [DEPRECATION WARNING]:
**WARNING** Please use AppDynamics extension buildpack for Golang Application instrumentation
**WARNING** for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html
-----> Installing godep 80
Download [https://cf-buildpacks.suse.com/dependencies/godep/godep-80-linux-x64-sle15-bfe8ffbb.tgz]
-----> Installing glide 0.13.3
Download [https://cf-buildpacks.suse.com/dependencies/glide/glide-0.13.3-linux-x64-sle15-d3bfaa2c.tgz]
-----> Installing dep 0.5.4
Download [https://cf-buildpacks.suse.com/dependencies/dep/dep-0.5.4-linux-x64-sle15-b7ca802d.tgz]
-----> Installing go 1.15.2
Download [https://cf-buildpacks.suse.com/dependencies/go/go-1.15.2-linux-amd64-sle15-aa2ff608.tgz]
-----> Running: go install -tags cloudfoundry -buildmode pie github.com/xxxxxxx/webapi
go: downloading github.com/gorilla/mux v1.8.0
2020/10/20 14:32:51 Building droplet release
2020/10/20 14:32:51 Creating app artifact
2020/10/20 14:33:16 Upload failed: Status code 500
2020/10/20 14:33:16 failed to upload buildpack cache. Upload failed: Status code 500

Error from api-0  pods:

{"timestamp":"2020-10-20T14:33:11.234572614Z","level":"info","source":"cc-uploader","message":"cc-uploader.droplet.upload.extracting-droplet-upload-uri-key","data":{"session":"55"}}            │
│ {"timestamp":"2020-10-20T14:33:11.234630742Z","level":"info","source":"cc-uploader","message":"cc-uploader.droplet.upload.succeeded-extracting-droplet-upload-uri-key","data":{"session":"55"}}  │
│ {"timestamp":"2020-10-20T14:33:11.234642795Z","level":"info","source":"cc-uploader","message":"cc-uploader.droplet.upload.parsing-upload-uri-parameter","data":{"session":"55"}}                 │
│ {"timestamp":"2020-10-20T14:33:11.234655174Z","level":"info","source":"cc-uploader","message":"cc-uploader.droplet.upload.succeeded-parsing-upload-uri-parameter","data":{"session":"55"}}       │
│ {"timestamp":"2020-10-20T14:33:11.234678664Z","level":"info","source":"cc-uploader","message":"cc-uploader.droplet.upload.uploading-droplet","data":{"content-length":7300981,"session":"55","up │
│ {"timestamp":"2020-10-20T14:33:11.234744782Z","level":"info","source":"cc-uploader","message":"cc-uploader.uploader.uploading","data":{"attempt-number":0,"session":"1"}}                        │
│ {"timestamp":"2020-10-20T14:33:11.492532576Z","level":"info","source":"cc-uploader","message":"cc-uploader.uploader.succeeded-uploading","data":{"attempt-number":0,"session":"1"}}              │
│ {"timestamp":"2020-10-20T14:33:11.492611253Z","level":"info","source":"cc-uploader","message":"cc-uploader.droplet.upload.succeeded-uploading-droplet","data":{"content-length":7300981,"session │
│ {"timestamp":"2020-10-20T14:33:11.492634775Z","level":"info","source":"cc-uploader","message":"cc-uploader.droplet.upload.polling-cc-background-upload","data":{"content-length":7300981,"sessio │
│ {"timestamp":"2020-10-20T14:33:11.492689957Z","level":"info","source":"cc-uploader","message":"cc-uploader.poller.checking-cc-job-status","data":{"attempt-number":0,"session":"2","status":"que │
│ {"timestamp":"2020-10-20T14:33:12.492983744Z","level":"info","source":"cc-uploader","message":"cc-uploader.poller.making-request-to-polling-endpoint","data":{"session":"2"}}                    │
│ {"timestamp":"2020-10-20T14:33:12.655679552Z","level":"info","source":"cc-uploader","message":"cc-uploader.poller.succeeded-making-request-to-polling-endpoint","data":{"session":"2"}}          │
│ {"timestamp":"2020-10-20T14:33:12.655865025Z","level":"info","source":"cc-uploader","message":"cc-uploader.poller.checking-cc-job-status","data":{"attempt-number":1,"session":"2","status":"fin │
│ {"timestamp":"2020-10-20T14:33:12.655900978Z","level":"info","source":"cc-uploader","message":"cc-uploader.poller.cc-job-finished","data":{"session":"2"}}                                       │
│ {"timestamp":"2020-10-20T14:33:12.655929541Z","level":"info","source":"cc-uploader","message":"cc-uploader.droplet.upload.succeeded-polling-cc-background-upload","data":{"content-length":73009 │
│ {"timestamp":"2020-10-20T14:33:12.657205262Z","level":"info","source":"cc-uploader","message":"cc-uploader.build-artifacts.upload.start","data":{"content-length":159392746,"session":"56","uplo │
│ {"timestamp":"2020-10-20T14:33:12.657505592Z","level":"info","source":"cc-uploader","message":"cc-uploader.uploader.uploading","data":{"attempt-number":0,"session":"1"}}                        │
│ 2020/10/20 14:33:16 http: TLS handshake error from 130.147.139.80:58538: EOF                                                                                                                     │
│ {"timestamp":"2020-10-20T14:33:16.663143356Z","level":"error","source":"cc-uploader","message":"cc-uploader.uploader.failed-uploading","data":{"attempt-number":0,"session":"1"}}                │
│ {"timestamp":"2020-10-20T14:33:16.663213575Z","level":"error","source":"cc-uploader","message":"cc-uploader.build-artifacts.upload.failed","data":{"error":"status code: 500\n{\n  \"error_code\ │

**To Reproduce**
Push any sample go app

**Expected behavior**
app should be staged fine without any errors.

**Environment**
 - CF Version : kubecf 2.5.8 eirini enabled. 
 - Component/Plugin Name : Eirini
 - Others

**Additional context**
k8s version: v1.17.7
vmware : vSphere 6.7 update 3
storage drive: vSphere CSI/CPI
mem/cpu: 16GB / 8vCPU
nodes: 1 master/ 3 workers
OS : CentOS Linux release 7.8.2003 (Core)
kernel: Linux 5.8.7-1.el7.elrepo.x86_64

**Comment by jandubois** [comment]
I cannot repro using [go-hello](https://github.com/cloud-gov/cf-hello-worlds/tree/master/go-hello) on kubecf-2.5.8 with Eirini:

This is using the default local minikube setup from this repo:

```
make minikube-start
make cf-operator-apply
FEATURE_EIRINI=1 make kubecf-apply
[wait until all pods are ready]
make cf-login
cd .../go-hello
cf push go-hello
```

<details><summary>Full cf push log</summary>

```
$ cf push go-hello
Pushing from manifest to org suse / space myspace as admin...
Using manifest file /Users/jan/suse/cf-hello-worlds/go-hello/manifest.yml


Deprecation warning: Specifying app manifest attributes at the top level is deprecated. Found: env, random-route.
Please see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.


Using manifest file /Users/jan/suse/cf-hello-worlds/go-hello/manifest.yml

Creating app go-hello in org suse / space myspace as admin...
OK

Creating route go-hello-generous-platypus-fh.192.168.99.254.omg.howdoi.website...
OK

Binding go-hello-generous-platypus-fh.192.168.99.254.omg.howdoi.website to go-hello...
OK

Uploading go-hello...
Uploading app files from: /Volumes/ThunderBlade/suse/cf-hello-worlds/go-hello
Uploading 1.1K, 3 files
Done uploading
OK

Starting app go-hello in org suse / space myspace as admin...
2020/10/22 00:23:26 Installing dependencies
2020/10/22 00:23:37 Cleaning cache dir
2020/10/22 00:23:37 Detecting buildpack
-----> Go Buildpack version 1.9.21.1
**WARNING** [DEPRECATION WARNING]:
**WARNING** Please use AppDynamics extension buildpack for Golang Application instrumentation
**WARNING** for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html
-----> Installing godep 80
Download [https://cf-buildpacks.suse.com/dependencies/godep/godep-80-linux-x64-sle15-bfe8ffbb.tgz]
-----> Installing glide 0.13.3
Download [https://cf-buildpacks.suse.com/dependencies/glide/glide-0.13.3-linux-x64-sle15-d3bfaa2c.tgz]
-----> Installing dep 0.5.4
Download [https://cf-buildpacks.suse.com/dependencies/dep/dep-0.5.4-linux-x64-sle15-b7ca802d.tgz]
-----> Installing go 1.15.3
Download [https://cf-buildpacks.suse.com/dependencies/go/go-1.15.3-linux-amd64-sle15-7f1e6c5e.tgz]
-----> Fetching any unsaved dependencies (dep ensure)
**WARNING** Installing package '.' (default)
-----> Running: go install -tags cloudfoundry -buildmode pie .
2020/10/22 00:24:32 Building droplet release
2020/10/22 00:24:32 Creating app artifact

0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App go-hello was started using this command `./bin/go-hello`

Showing health and status for app go-hello in org suse / space myspace as admin...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: go-hello-generous-platypus-fh.192.168.99.254.omg.howdoi.website
last uploaded: Thu Oct 22 00:23:16 UTC 2020
stack: sle15
buildpack: Go

     state     since                    cpu    memory    disk      details
#0   running   2020-10-21 05:24:58 PM   0.0%   0 of 1G   0 of 1G
```
</details>

**Comment by dheerajinganti** [comment]
@jandubois I tried pushing go-hello and it results into same error. I tried dotnet-core app too and it fails with same error. 
go - fails
dotnet-core - fails
python-flask - success
java - success
ruby-sinatra - success
nodejs - success
--------


OK

Uploading go-hello...
Uploading app files from: /Users/ing08763/src/suse-cf/examples/cf-hello-worlds/go-hello
Uploading 1.1K, 3 files
Done uploading               
OK

Starting app go-hello in org hsop / space dev as admin...
2020/10/22 04:53:46 Cleaning cache dir
2020/10/22 04:53:46 Detecting buildpack
2020/10/22 04:53:35 Installing dependencies
-----> Go Buildpack version 1.9.19.1
**WARNING** [DEPRECATION WARNING]:
**WARNING** Please use AppDynamics extension buildpack for Golang Application instrumentation
**WARNING** for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html
-----> Installing godep 80
Download [https://cf-buildpacks.suse.com/dependencies/godep/godep-80-linux-x64-sle15-bfe8ffbb.tgz]
-----> Installing glide 0.13.3
Download [https://cf-buildpacks.suse.com/dependencies/glide/glide-0.13.3-linux-x64-sle15-d3bfaa2c.tgz]
-----> Installing dep 0.5.4
Download [https://cf-buildpacks.suse.com/dependencies/dep/dep-0.5.4-linux-x64-sle15-b7ca802d.tgz]
-----> Installing go 1.13.15
Download [https://cf-buildpacks.suse.com/dependencies/go/go-1.13.15-linux-amd64-sle15-50a3d09a.tgz]
**WARNING** go 1.13.x will no longer be available in new buildpacks released after 2020-09-03.
See: https://golang.org/doc/devel/release.html
-----> Fetching any unsaved dependencies (dep ensure)
**WARNING** Installing package '.' (default)
-----> Running: go install -tags cloudfoundry -buildmode pie .
2020/10/22 04:54:20 Building droplet release
2020/10/22 04:54:20 Creating app artifact
2020/10/22 04:54:45 Upload failed: Status code 500
2020/10/22 04:54:46 failed to upload buildpack cache. Upload failed: Status code 500

FAILED
Error restarting application: StagingError

TIP: use 'cf logs go-hello --recent' for more information

**Comment by dheerajinganti** [comment]
@jandubois I am able to push go app but only few time like 1 in 4 attempts. I will re-deploy and verify this behavior.

**Comment by dheerajinganti** [comment]
An update, U re-deployed 2.6.1 and I am able to push go apps fine. However for the first time, I did get 500 error while pushing simple go-hello app. But after retrying it all worked fine. will keep a watch and update if I face any further issues with app push.

**Comment by dheerajinganti** [comment]
Closing this issue as I am able to push apps now.
