### ISSUE TITLE
Build artifacts from master are not properly "versioned"

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#1523]
Currently, KubeCF builds `master` based on the last tag it can track on the branch, which is 0.2.0.
After a team discussion, we will move to the following format:

```
0.0.0-<commit_timestamp>.<number_of_commits_on_branch>.<commit_short_hash>
```

- `0.0.0` represents a non-version to satisfy the semantic versioning requirements of Helm packaging.
- `<commit_timestamp>` represents a timestamp in the format `yyyymmddHHMMSS` when the commit was created. This can be parsed from the output of `git show --no-patch --format="%ci" HEAD`. This should be converted to UTC.
- `<number_of_commits_on_branch>` represents the number of commits on the branch. This is the output of `git rev-list --count HEAD`.
- `<commit_short_hash>` represents the short hash of the current commit. This is the output of `git rev-parse --short HEAD`.

**Comment by viccuad** [comment]
Closing as completed; master artifacts with the new format are already landing in https://s3.console.aws.amazon.com/s3/buckets/kubecf-ci.
