### ISSUE TITLE
Need a new type of database other than "embedded_database" and "external_database"

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry-incubator/kubecf#1541]
**Is your feature request related to a problem? Please describe.**
In our environment, control_plane needs to use multiple databases from external Kubecf. Definitely `embedded_database` feature should be disabled. As `external_database` feature can only configure one database, it's not applicable to our environment. Currently we are setting the database information under `properties` in values.yaml for each job. 

In the new version of Kubecf, it forces either `embedded_database` or `external_database` must be enabled for control_plane https://github.com/cloudfoundry-incubator/kubecf/blob/master/chart/config/unsupported.yaml#L19-L25. This prevent us from going forward.

**Describe the solution you'd like**
Add another new database type like `other_database` other than `embedded_database` and `external_database` that can be enabled in values.yaml. In the unsupported.yaml, it can force one of the three database types must be enabled.

**Comment by jandubois** [comment]
Would fixing #1539 solve this issue as well (meaning, can we close this as a duplicate)?

**Comment by gu-bin** [comment]
Sure. Thanks.
