### ISSUE TITLE
Update SLE stacks for KubeCF

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#1598]
I know we have hopes to automate stack bumps in https://github.com/cloudfoundry-incubator/kubecf/issues/1484 but we're out of date and via Trivi, we see that many kubecf components show vulnerabilities. Whether they're relevant or not is in question but the perception issue of people looking to use a private container registry will be raised.

We are also months out of date regardless so we should take care of this pronto in the next kubecf version.

**Comment by thardeck** [comment]
Automation was setup directly after realizing the issue, for example: https://github.com/cloudfoundry-incubator/kubecf/pull/1597/files

The stack update was not shipped with the latest cap release though, that is the remaining issue.

**Comment by gaktive** [comment]
Thanks @thardeck. Do we have an issue to ship the updates?
