### ISSUE TITLE
Get rid of sample_values.yaml

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#1626]
Now that all "hidden" values have been moved to internal config files, I don't think the reasoning from #711 still applies.

The `sample_values.yaml` is now redundant and anyways hard to discover, so I suggest we stop including it.

**Comment by gaktive** [comment]
@troytop what's your take? We don't mention this in the docs but I don't recall if we mention this elsewhere. I'll leave this at the bottom of the icebox for now.

**Comment by troytop** [comment]
Get rid of it. It's currently an empty file anyway (in the SUSE chart).
