### ISSUE TITLE
Find out whether we should remove the cc deployment updater

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1634]
**Is your feature request related to a problem? Please describe.**
The CC deployment updater freezes when the database goes away.
It doesn't die, so it also doesn't recover.
The description of the job in its spec says "experimental" - is this component needed? and how does it work?

**Describe the solution you'd like**

**Describe alternatives you've considered**
- Letting the component be as it is for upstream.
- Using this [port for readiness](https://github.com/cloudfoundry/capi-release/blame/develop/jobs/cc_deployment_updater/spec#L89)

**Additional context**
#1589

**Comment by andreas-kupries** [comment]
See also #1355 and #1595 

Note: Current readiness probe is more like a liveness probe. The current liveness checks only process presence, and the other probe checks that the update loop is actually active, which looks to be stricter, and better than process presence.

**Comment by mook-as** [comment]
Removed in #1637 and upgrade should work after #1632
