### ISSUE TITLE
HA same version upgrades is failing 

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/kubecf#1640]
**Describe the bug**
HA upgrades from https://s3.us-west-2.amazonaws.com/kubecf/kubecf-bundle-v0.0.0-20201127002146.2152.g5ee792f1.tgz to the same version, failed.
`diego-cell-2                                    11/12   Running            22         5h15m`
CI: https://concourse.suse.dev/teams/main/pipelines/cap-nightly/jobs/upgrade-kubecf-diego-aks-ha/builds/1

Klog: s3://kubecf-klog/klog-ci-aks-c8cc0e391aeec16f-12_01_2020-04_43.tar.gz

**To Reproduce**
Deploy kubecf-bundle-v0.0.0-20201127002146.2152.g5ee792f1.tgz with HA enabled and Perform a same version upgrade. Autoscaler was not enabled.

Or use cap-ci to reproduce the same

**Expected behavior**
diego-cell-2 never came up

**Environment**

AKS

**Comment by jandubois** [comment]
@prabalsharma wrote on 🚀:

> it looks like its not a valid scenario
