### ISSUE TITLE
Build custom eirini images in the kubecf pipeline

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#240]
**Is your feature request related to a problem? Please describe.**
Build eirini images in the kubecf pipeline.
https://github.com/SUSE/kubecf/pull/138/files/c905f7cf990aefd2ec21aa0060596ddea1edc57f#diff-8e190b66df231646a528bed8a0145181R106

**Describe the solution you'd like**
Build the images as part of the kubecf pipeline.

**Describe alternatives you've considered**
n/a

**Additional context**
These are custom images to support using an S3 blobstore with eirini.

**Comment by mook-as** [comment]
Does this need to be in the **kubecf** pipeline? Wouldn't it make more sense as a separate one (since AFAIK nothing in the image depends on `kubecf.git`)?

**Comment by viovanov** [comment]
All eirini images are built in our own pipelines.
