### ISSUE TITLE
Use an ssh compatible eirinifs when deploying with Eirini

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#248]
**Describe the bug**
For the Eirini ssh extension to work, the eirinifs used should start the sshd when the application starts. That only happens on this stack for now: https://github.com/SUSE/eirinifs-sle15-release/releases

To get SSH to work with Eirini on kubecf we need to consume this bosh release.

Since this stack is based on SLE, we also need to make sure we got the sle buildpacks as well.

**To Reproduce**
N/A

**Expected behavior**
The operator MUST access the deployed app through SSH (feature parity).

**Environment**
N/A

**Additional context**
N/A

**Comment by f0rmiga** [comment]
Blocked waiting on the SLE buildpacks.
