### ISSUE TITLE
Implement podAntiAffinity for the same STS pods against a node

### ISSUE THREAD

**Issue by satadruroy** [cloudfoundry-incubator/kubecf#254]
on SCF 1.5.1 we noticed that some roles had all their pods scheduled on the same node (e.g. `uaa`, `mysql`). This may have been exacerbated by an erroneous `topologyKey` in the `podAntiAffinity` specification which was looking at `beta.kubernetes.io/os` instead of `kubernetes.io/hostname` but for kubecf we should explicitly specify the `podAntiAffinity` setting rather than leaving it all to the k8s scheduler and risk an extended outage when a node goes down taking with it all instances of a particular role.

**Comment by fargozhu** [comment]
@satadruroy but if I recall @jandubois is mentioning in #141 that we should leave this to k8s scheduler instead.

**Comment by satadruroy** [comment]
I think we have seen replicas from the same statefulset getting scheduled on the same node without any `podAntiAffinity` rules (or with broken rules). After we put in the anti-affinity rules the problem went away. @jandubois  may have been indicating the difficulty of attempting to extend that to cover an even pod spread across multiple zones but I'll let him confirm.

**Comment by jandubois** [comment]
Ant-affinity cannot be used to spread pod across both nodes and zones; you have to choose one topology key.

It will help with the initial distribution, but once every node (or every zone) has a single instance of the selected pod class, the anti-affinity rule will not have any effect on the placement of the remaining pods.

For SCF we do provide podAntiAffinity rules to increase the likelihood of spreading the pods across nodes. It will not help to spread across zones unless you have as many instances as you have zones.

**Comment by gaktive** [comment]
This lack of affinity is impacting people moving from scf to kubecf so need to prioritize this higher as a missing feature.
