### ISSUE TITLE
Continuous Release

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#27]
As a contributor to kubecf, I'd like to get a release as soon as my PRs are merged.

**Comment by fargozhu** [comment]
I think this is related to #20, but maybe more on the praticality side?!

**Comment by f0rmiga** [comment]
Blocked on https://github.com/SUSE/kubecf/issues/104.

**Comment by viovanov** [comment]
Blocked by #20

**Comment by fargozhu** [comment]
This card is too wide and it should be either breakdown in specific ones.
