### ISSUE TITLE
Fix compilation of {brain-tests,cf-mysql,groot-btrfs} release images on the sle15 stemcell

### ISSUE THREAD

**Issue by aduffeck** [cloudfoundry-incubator/kubecf#270]
**Is your feature request related to a problem? Please describe.**
After the switch to the sle15 stemcell three release images were left behind due to compilation issues:

* brain-tests (bundled ruby 2.3 icompatible with libopenssl)
* cf-mysql (bundled ruby 2.3 icompatible with libopenssl)
* groot-btrfs (automake, pkgconfig)

**Describe the solution you'd like**
The releases should be changed so that they compile again by updating the problematic packages. There could also be changes required for the stemcell itself.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fargozhu** [comment]
@aduffeck #370 may have an impact here.
