### ISSUE TITLE
Make Eirini apps work with our DNS

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#284]
**Describe the bug**

Since Eirini apps cannot resolve the DNS records from the kubecf coreDNS instance, credhub.servie.cf.internal becomes unreachable.

**To Reproduce**

Deploy kubecf with Eirini and check that credhub CATS suite doesn't pass.

**Expected behavior**

Eirini apps should be able to resolve the kubecf DNS entries. It may be possible with an EiriniX mutator.

**Environment**

All versions.

**Comment by f0rmiga** [comment]
Blocked by https://github.com/SUSE/eirinix/issues/18 and https://github.com/SUSE/eirini-loggregator-bridge/issues/4.

**Comment by f0rmiga** [comment]
I currently got an Eirinix working for mutating the apps, pointing them to the kubecf custom DNS instances. `credhub` tests fail due to, _apparently_, trying to set an environment variable at runtime. Since k8s doesn't support this behaviour without restarting, I'm in the process of finding out if the failing credhub tests are relevant in the Eirini world.

**Comment by mook-as** [comment]
For some context: there's some experimental code in https://github.com/SUSE/eirini-dns-aliases/tree/f0rmiga/initial-impl (the meat of which is https://github.com/SUSE/eirini-dns-aliases/blob/f0rmiga/initial-impl/pkg/extension/extension.go ).

**Comment by mook-as** [comment]
This is going to involved https://github.com/SUSE/eirinix/issues/40 — eirinix has really old quarks dependencies. (It still refers to `cf-operator` in the import, which makes it not build.)

**Comment by jandubois** [comment]
> (It still refers to `cf-operator` in the import, which makes it not build.)

If you need a quick fix for building it, here is what I did in https://github.com/SUSE/eirini-persi/blob/master/go.mod#L25

**Comment by andreas-kupries** [comment]
Blocked on its PR, which is blocked in turn on #1259 

@mook-as I notice that #1259 is merged. Would this unblock the linked #1275 ?

**Comment by mook-as** [comment]
@andreas-kupries I believe #1275 is currently waiting on https://github.com/SUSE/eirini-dns-aliases/pull/1

**Comment by andreas-kupries** [comment]
Ok then. Marking it as blocked was correct.
