### ISSUE TITLE
Create CI job to test CCDB encryption key rotation

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#299]
**Is your feature request related to a problem? Please describe.**

Following up on https://github.com/SUSE/kubecf/pull/298, we need a job to test the CCDB encryption key rotation.

**Describe alternatives you've considered**

Ideally, this job would run after the first `smoke-tests`, running the errand and asserting that the CCDB key was successfully rotated. Then run `smoke-tests` again.

**Comment by fargozhu** [comment]
@f0rmiga shouldn't this be an explicit test instead?

**Comment by f0rmiga** [comment]
The outcome of doing it on CI is certainly an explicit test.

**Comment by f0rmiga** [comment]
Blocked by https://github.com/SUSE/kubecf/issues/361.

**Comment by f0rmiga** [comment]
If we implement this on the post-publish pipeline, this story is not blocked anymore.

**Comment by andreas-kupries** [comment]
The original PR #400 is subsumed into #401.

**Comment by bikramnehra** [comment]
moving to DONE since the mentioned PR is merged already.
