### ISSUE TITLE
Use scf variable names to allow for easier kubecf upgrade experience.

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#30]

**Comment by gaktive** [comment]
@viovanov may have a solution to convert this via the operator.

**Comment by fargozhu** [comment]
We also need to consider Stratos secrets and configurations compatability when upgrading to V3

**Comment by gaktive** [comment]
Need to keep an eye on #10 to sort out impact on migration plan.

**Comment by gaktive** [comment]
Closing for now since scf migration to kubecf will go through backup/restore cli. Will watch if variable names need to be changed but we can open a new issue if necessary.
