### ISSUE TITLE
HA database configuration for CCDB and UAA

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#312]
**Is your feature request related to a problem? Please describe.**
Though we're pushing admins to use an external database with kubecf in production, for a better out-of-box experience, we need to include an internal database so that early adopters can simply get kubecf operational quickly.

**Describe the solution you'd like**
@troytop can provide more context but perhaps this is simply a case of adding a helm chart to another database. As for which one, I will defer to him.

**Comment by gaktive** [comment]
@viovanov mentioned that @aduffeck is already looking at MariaDB as an option.

**Comment by fargozhu** [comment]
will be fixed by #270

**Comment by f0rmiga** [comment]
@aduffeck I assigned you here based on the comments by @gaktive and @fargozhu.
