### ISSUE TITLE
Test containers restart on failure

### ISSUE THREAD

**Issue by andreas-kupries** [cloudfoundry-incubator/kubecf#324]
**Describe the bug**

When tests like smoke, brain, or cf-acceptance fail their container is restarted.
This is not desirable.

This seems to be a policy inherited indirectly from the quarks-job which creates the job, which creates the pod, the container belongs to.

**To Reproduce**
Run one of the test suites in a way that has them fail.
(For brains and cf-acceptance it seems that just running them at all is enough at the moment).

**Expected behavior**
The failed container should not restart.
I suspect that it is desirable to have the controlling pod to be terminated and deleted.
I suspect that it is desirable to have the controlling job to be terminated and deleted.
The controlling quarks-job however should not be touched.

**Environment**
 - cf-operator-v1.0.3-0.g5dd886a5
 - kubecf 46b5561fff753772645fedcc954134fe7d04e341 (Implies cf-operator above)

**Additional context**

**Comment by f0rmiga** [comment]
@fargozhu Could we schedule this to be fixed in the next sprint, please?

**Comment by viovanov** [comment]
Might need help in the operator.
