### ISSUE TITLE
Change in default max-deploy-size

### ISSUE THREAD

**Issue by IvanHristov98** [cloudfoundry-incubator/kubecf#351]
Currently the size of deployment artifacts, like WAR, EAR, etc., is limited to **8MB** by default. That is relatively small, especially when compared to the size of, for an example a Spring application. I propose changing it to something larger, like for 100~200MB.

This is configured via [nginx ingress annotations](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size).

**Comment by troytop** [comment]
Does the change in #802 fix this for most cases (considering the ingress is configurable after install)?

**Comment by IvanHristov98** [comment]
I think so. It looks better to me now. Closing the issue.
