### ISSUE TITLE
Watch for initial jobs created by cf-operator on CI

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#380]
**Is your feature request related to a problem? Please describe.**

When kubecf is deployed on CI, the scripts don't verify is the initial jobs created by cf-operator succeed. On some cases, the `ig` job could partially succeed, letting some of the following instance groups to be created.

**Describe the solution you'd like**

Watch for the `dm` (desired manifest) and `ig` (instance group) initial jobs.

**Comment by f0rmiga** [comment]
This check should help in cases like cf-operator bumps like this one: https://github.com/SUSE/kubecf/pull/377.

**Comment by fargozhu** [comment]
@f0rmiga I think the #558 would fix this issue. If true then we can close this one.

**Comment by f0rmiga** [comment]
Sure, if we face this again, we can either re-open this or create a new one given that there's not much here.
