### ISSUE TITLE
Enable persi nfs support

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#382]
**Is your feature request related to a problem? Please describe.**
We need to be able to support persistent storage for apps in the case where Eirini isn't in use. Persi is a volume service broker that can tackle this via `mapfs` and `nfs-server`. We have this in scf but it'll be very much needed in kubecf.

Blocking #29

**Comment by gaktive** [comment]
Based on https://github.com/SUSE/doc-cap/issues/144, we'll need to verify how to do this since documentation has run into problems following upstream material.

**Comment by viovanov** [comment]
TODO: 
- [ ] the stemcell should contain the required dependencies for compiling nfs (https://ci.flintstone.cf.cloud.ibm.com/teams/quarks/pipelines/release-images/jobs/build-nfs-volume/builds/5)
- [ ] nfs bosh release image should be green
- [ ] feature flag to enable the nfs instance group
- [ ] brain test passing

**Comment by mook-as** [comment]
Note that IIRC the NFS BOSH release doesn't use BPM yet, and we only support BPM, so we'll need to do some hacking on it anyway (in which case we might as well fix it so we _don't_ need to change the stemcell).

**Comment by mook-as** [comment]
@viovanov Would it be possible to fork https://github.com/cloudfoundry/nfs-volume-release and https://github.com/cloudfoundry/mapfs-release while we get things in gear, so I have  somewhere to PR in-progress things to?  Currently this is necessary as upstream has no BPM support.  I'm also not sure yet how my changes would fare on a BOSH VM based deployment.

**Comment by mook-as** [comment]
Marking Blocked based on quarks-operator dependencies.

**Comment by gaktive** [comment]
Duplicate of #957

**Comment by mook-as** [comment]
@gaktive The issue to do a task can't be a dupe of the PR to fix it, can it‽

**Comment by mook-as** [comment]
To clarify: we're planning on:
- Ignoring persi-NFS for diego.
- Supporting persi in Eirini
  - Via storage classes only
