### ISSUE TITLE
Make Eirini work with external blobstores

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#384]
**Is your feature request related to a problem? Please describe.**

Once Eirini reaches a stable state with KubeCF, we should revisit using external blobstores with it.

**Describe the solution you'd like**

?

**Describe alternatives you've considered**

?

**Additional context**

?

**Comment by gaktive** [comment]
#200 is tied to the Diego solution for the external blobstore. #138 may have some relevance for S3 as an implementation.

**Comment by mook-as** [comment]
The S3 implementation landed via #608 (which was a rebase of #138).  As far as I can tell this feature request is already complete; if we want other specific blobstore backends we should file separate requests for them.
