### ISSUE TITLE
How can we reliably configure Diego cell sizes so they won't fail for OOM conditions?

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#389]
**Is your feature request related to a problem? Please describe.**
On scf, we've heard of at least one environment where after many apps have been pushed already, diego cells are starting to consume more space than a certain threshold which impacts deploying subsequent apps.

It's possible that diego cells are using more space than expected. We do rely on `env.DIEGO_CELL_MEMORY_CAPACITY_MB` and `env.DIEGO_CELL_DISK_CAPACITY_MB` set to `auto` by default in the Helm charts. But it's possible that without `diego.executor.auto_disk_capacity_overhead_mb` exposed, we're running amok with the default of `0` along with the existing settings.

**Comment by jandubois** [comment]
@viovanov Can this issue be closed due to your recent work on the diego-cell volume sizing?

**Comment by viovanov** [comment]
@jandubois yes, #1264 makes this spike unnecessary.
