### ISSUE TITLE
Figure out & document migration path from SCF v2 to kubecf

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#394]
As a user of SCF v2, I would like to:
- follow a step-by-step guide to upgrade to V3
- understand what downtime I should expect

**Comment by viovanov** [comment]
This issue also includes testing the instructions.

**Comment by mook-as** [comment]
Unassigning for now — @btat is writing up docs for SUSE that deals with this; we can just direct people to it or crib bits from it or something once that's done :D

**Comment by mook-as** [comment]
The relevant SUSE docs are [here](https://susedoc.github.io/doc-cap/master/html/cap-guides/cha-cap-upgrade.html#sec-cap-upgrade-export-scf) (that's the draft generated from [here](https://github.com/SUSE/doc-cap/blob/1eea21b4376b0d36ef644cb5d5906376d04e0efd/xml/cap_admin_upgrade.xml#L78)).

**Comment by viovanov** [comment]
@mook-as a link from the kubecf docs to the suse docs should be enough
