### ISSUE TITLE
Concourse Pipeline Metrics

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#395]
**Is your feature request related to a problem? Please describe.**

Currently, there're no metrics regarding the Concourse pipeline/jobs and that makes it hard to propose any changes that would eventually improve the performance.

**Describe the solution you'd like**

Concourse itself can emit metrics regarding the builds that would be consumed by an operator like Prometheus or Datadog. 
These metrics can be used to produce useful dashboards to highlight the areas to improve and/or if the "improvements" are making any difference.

**Describe alternatives you've considered**

None.

**Additional context**

https://concourse-ci.org/metrics.html

![Screen Shot 2020-02-19 at 09 42 06](https://user-images.githubusercontent.com/904062/74816807-22f5ed00-52fc-11ea-813a-2e1a1d63b113.png)

**Comment by viccuad** [comment]
For obtaining precise information we need to refactor a bit the pipeline so each job has separate ancillary CI tasks (import kubeconfig, etc), and kubecf tasks (download kubecf images, deploy, test, etc).

It seems that concourse's REST API only gives you duration of the full job, but one can scrape duration info from tasks from the pop-over they have: (in our case would be `deploy`, `test-cats`, etc)

![concourse_popup](https://user-images.githubusercontent.com/2196685/78651158-3cf58a00-78c0-11ea-95fd-8e5ac83c1f5b.png)

It would be nice also to default to airgapped deployments to reduce network time skews, and use the same HW (ideally baremetal) to reduce processing & IO skews.

**Comment by fargozhu** [comment]
closing this one since we are moving away from Concourse to GitHub Actions CI.
