### ISSUE TITLE
Move Gitlab Pipeline to Concourse

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#397]
**Is your feature request related to a problem? Please describe.**

Gitlab pipeline is always getting stuck due to a lack of workers. This could be fixed but since the price model is changing and we have Concourse resources available around then we should move the pipeline into it.

**Describe the solution you'd like**

Make sure that whatever is happening on Gitlab pipeline is replicated on Councourse, like:

1. Linting
2. Run the same tests that we are running today on Gitlab
3. Publish the artifacts to S3 bucket
4. Cleanup all Gitlab references on KubeCF repository

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mudler** [comment]
Can we close this?
