### ISSUE TITLE
Introduce feature_flag for credhub

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/kubecf#399]
**Is your feature request related to a problem? Please describe.**
It can be seen as a problem. For my kubecf setup I do not required `credhub`. Removing credhub requires to tweak different files, making the override complicated.

**Describe the solution you'd like**
I would like to have a `feature_flag` in the chart `values.yaml` , that can enable/disable credhub depending on the needs.

**Describe alternatives you've considered**
I new template(ops-files)  that unify all credhub related configuration, and that is applied only if the `feature_flag` is set to true.

**Additional context**
None

**Comment by f0rmiga** [comment]
This should respect the `features.credhub.enabled` Helm property.

**Comment by f0rmiga** [comment]
Closing this as resolved in https://github.com/cloudfoundry-incubator/kubecf/pull/411.
