### ISSUE TITLE
Stratos Console only showing 1 of 2 diego cells (because of missing metrics)

### ISSUE THREAD

**Issue by troytop** [cloudfoundry-incubator/kubecf#407]
**Describe the bug**

Stratos Console only showing 1 of 2 diego cells.

Paraphrased from @nwmac 

If I look in Prometheus, I only get one series for the metric 

`firehose_value_metric_rep_capacity_remaining_containers` - e.g.

```
firehose_value_metric_rep_capacity_remaining_containers{bosh_deployment="kubecf",bosh_job_id="diego-cell-0",bosh_job_name="diego-cell-loggr-forwarder-agent",cloud_foundry="https://api.10.86.2.34.xip.io",environment="wss://doppler.10.86.2.34.xip.io:443",instance="metrics-f-exp-service-0.metrics.svc.cluster.local:9186",job="cf-firehose",origin="rep",unit="Metric"}
```

There should be a series for each Diego Cell... so I'll assume this is a KubeCF bug/issue

Possibly unrelated, but important: The metadata for KubeCF is empty - if you go to /v2/info - name, build, support, description, version are all empty 

**To Reproduce**
Install kubecf-v0.0.0-e7534b6 using cf-operator-2.3.0+0.g27a91cdf with at least 2 diego cells, then deploy console-helm-chart-3.0.0-rc.1-cf818986f (or probably any version of Stratos). Second diego cell will not appear in any Stratos views. and 

**Expected behavior**
We should see all diego cells in Stratos

**Comment by gaktive** [comment]
@troytop to repro with more recent KubeCF & Stratos and update this issue.

**Comment by gaktive** [comment]
Repro'd with KubeCF 2.2.3 and Stratos 4.0.1 RC1: https://github.com/cloudfoundry-incubator/kubecf/issues/1198
Also seen on another environment with 5 Diego cells, though showing only diego-0.
