### ISSUE TITLE
Ameliorate buildpack file paths

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#412]
**Is your feature request related to a problem? Please describe.**
The [buildpack file paths](https://github.com/SUSE/kubecf/blob/master/deploy/helm/kubecf/assets/operations/instance_groups/api.yaml#L21-L42
) in their current form are hardcoded and therefore requires ongoing maintenance especially during bumps.

**Describe the solution you'd like**
A typical buildpack path looks like following:

`/var/vcap/pacakages/nodejs-buildpack/packages/nodejs-buildpack-cflinuxfs3/nodejs_buildpack-cflinuxfs3-v1.7.9.zip`

where the version is coming from cf-deployement yaml. So we can have a ops file similar to https://github.com/SUSE/kubecf/blob/master/deploy/helm/kubecf/assets/operations/buildpacks/set_suse_buildpacks.yaml which will interpolate the builldpack version from cf-deployment to set the filepath.

**Describe alternatives you've considered**
An alternate option is to create a bazel target which will get the filepath directly from the buildpacks' bosh release.

**Comment by jandubois** [comment]
File paths have been eliminated in #1202
