### ISSUE TITLE
CI Badge for master

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#420]
**Is your feature request related to a problem? Please describe.**
A passing/failing badge for master in the project's README

**Describe the solution you'd like**
Same badge we've had so far, but pointed to Concourse. We'll likely need some code to get the last commit of master and get its status from Concourse, since the pipeline checks both PRs and master.

**Describe alternatives you've considered**
Not using a badge.

**Additional context**
n/a

**Comment by jimmykarily** [comment]
We can deploy this: https://github.com/jimmykarily/github_branch_status
