### ISSUE TITLE
Support custom KubeCF CI pipelines for development work.

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#430]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy way to deploy and test changes(esp CI related) in our [concourse pipelines](https://github.com/cloudfoundry-incubator/kubecf/tree/master/.concourse). Directly making changes in [pipeline.yml](https://github.com/cloudfoundry-incubator/kubecf/blob/master/.concourse/pipeline.yaml) is error prone and it might lead to unwanted changes in production pipelines and also runs a risk of secrets leaking.

**Describe the solution you'd like**
Ideally developers should be able to deploy their own custom pipelines to test any changes. Here are some roadblocks including but not limited to:

- Better support for customizing concourse resources such as s3 buckets, GitHub repositories/branches etc.
- Support for forked repos.
- Better secret management.

As a side note, the size of [pipeline.yml](https://github.com/cloudfoundry-incubator/kubecf/blob/master/.concourse/pipeline.yaml) is becoming too big therefore we must look at breaking down things before it becomes unmanageable. 

**Describe alternatives you've considered**
We need to brainstorm over various approaches before coming up with final solution.

**Comment by jimmykarily** [comment]
The post difficult thing when deploying a copy of a pipeline is to make sure you won't publish any artifacts in final locations or pollute the commit status of any commits on GitHub. I suggest as a first step to use some erb condition as a quick switch to disable all publishing (of artifacts, commit statuses etc). 

This particular pipeline has one hard dependency which is the EKCP setup (we need something to give us clusters for testing). For now, we can reuse the same EKCP node for our "debugging" pipelines since we have enough capacity.

**Comment by viccuad** [comment]
I have achieved local testing by not using a pipeline.
Example, run smokes against a checked out kubecf, by building it first:
```
$ cd catapult
$ SCF_OPERATOR=true \
   SCF_LOCAL=/home/vic/suse/kubecf \
   KUBECF_TEST_SUITE=smokes \
   make scf-build tests-kubecf
```
Another example, you can git bisect kubecf locally against tests and stratos, eg:

```
$ git clone git@github.com:SUSE/catapult.git
$ git clone git@github.com:cloudfoundry-incubator/kubecf.git
$ cd kubecf
$ git bisect start
$ git bisect good foo
$ git bisect bad bar
$ git bisect run cd ../catapult && \
   SCF_OPERATOR=true \
   SCF_LOCAL=/home/vic/suse/kubecf \
   KUBECF_TEST_SUITE=smokes \
   make scf-build tests-kubecf stratos
```
Granted, catapult ui could be streamlined, and we definitely need a `make kcf` or the like that has the correct default options for kubecf. But I see value on using it locally for testing. I think the examples are pretty self-explanatory, and there's no need for 600 lines pipeline yaml just to run a test.

These examples with `make k8s` are creating a local kind cluster, but one can easily use any external cluster by unknown backend (colleages are already using it successfully):

```
$ BACKEND=imported CLUSTER_NAME=foo make k8s
(creates buildfoo)
$ BACKEND=imported CLUSTER_NAME=foo make scf-build blablabla
```

or by importing a known backend:
```
$ BACKEND=eks CLUSTER_NAME=foo make kubeconfig
(creates buildfoo)
$ BACKEND=eks CLUSTER_NAME=foo make scf-build blablabla
```

**Comment by bikramnehra** [comment]
@viccuad I agree with your suggestion on using catapult for local testing and something like `make kcf` as it would facilitate testing of `kubecf` components imitating how end-users will be using it e.g: using helm to deploy things. However, I am not sure if that would be enough as you can see in the issue description one of the highlighted point is to test changes in pipeline(s) itself. 

In theory, we can swap `ekcp` with a local kind cluster config and also deploy concourse locally though we feel it might be an overkill at this point.

Following action items were discovered during an initial discussion with @jimmykarily and @mudler:
- Having a configuration mechanism(e.g: config file) which will provide some level of customization for developers.
- Breaking down [pipeline.yml](https://github.com/cloudfoundry-incubator/kubecf/blob/master/.concourse/pipeline.yaml) in smaller more manageable chunks.

**Comment by viccuad** [comment]
> However, I am not sure if that would be enough as you can see in the issue description one of the highlighted point is to test changes in pipeline(s) itself.

That's a valid concern, I stepped over it.

> In theory, we can swap ekcp with a local kind cluster config and also deploy concourse locally though we feel it might be an overkill at this point.

For the product-release pipeline (and kubecf pipeline) we want, post 2.0, to add a pool system based on a git repo to create, consume, and release clusters (ala cf-ci). Particularly CaaSP, AKS, EKS, GKE clusters. Both humans and pipelines should be able to consume clusters from it, and it will allow horizontal scaling of the jobs for all k8s types. That may ease testing changes and pipelines themselves.

**Comment by bikramnehra** [comment]
@viccuad @jimmykarily @mudler @mook-as: To start things, should we create stories for the action items I described above? We can pull those in current and subsequent sprints.

> Following action items were discovered during an initial discussion with @jimmykarily and @mudler:
> 
> * Having a configuration mechanism(e.g: config file) which will provide some level of customization for developers.
> * Breaking down [pipeline.yml](https://github.com/cloudfoundry-incubator/kubecf/blob/master/.concourse/pipeline.yaml) in smaller more manageable chunks.

**Comment by jimmykarily** [comment]
@bikramnehra I created these 2:

- https://github.com/cloudfoundry-incubator/kubecf/issues/442
- https://github.com/cloudfoundry-incubator/kubecf/issues/443

cc @fargozhu

**Comment by bikramnehra** [comment]
Closing in favor of following action items.
