### ISSUE TITLE
Uninstalling KubeCF leaves database-seeder behind

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#439]
**Describe the bug**

Following up on https://github.com/cloudfoundry-incubator/kubecf/pull/393, the `database-seeder` pod created by the quarks job during the bootstrapping phase is left behind after KubeCF is deleted.

**To Reproduce**

1. Install KubeCF.
2. Delete KubeCF.

**Expected behavior**

The pod for the `database-seeder` job is left behind in the `Complete` state, I'd expect the pod to be deleted with the QuarksJob and the Job resources that created it.

**Environment**

Latest master. https://github.com/cloudfoundry-incubator/kubecf/tree/4dc4256f0b57c5624f84f0d2222d52fc8390f403.

**Additional context**

It is _possible_ that the bug is with the QuarksJob controller, rather than with KubeCF.

**Comment by fargozhu** [comment]
@viovanov @manno can you give your feedback about if the bug is on cf-operator

**Comment by viovanov** [comment]
@fargozhu we'll have to check - can you please open an issue there and link it?
