### ISSUE TITLE
Use the Eirini helm chart instead of the BOSH release

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#47]
**Is your feature request related to a problem? Please describe.**
We'd like to use Kubernetes-native components where available.

**Describe the solution you'd like**
Instead of converting the Eirini BOSH release through the CF Operator, use its helm chart.

**What is the impact?**
We wouldn't need to support the Eirini BOSH release anymore.

**How to measure it?**
Everything should work as before.

**Comment by c0d1ngm0nk3y** [comment]
We have done the same as a "spike" and you can find the result here: https://github.com/akhinos/kubecf-external-eirini. There is a README.md with the changes we had to apply to make it work.

* Changes to `kubecf`, e.g. install `bits` but not eirini
* Changes to the `eirini-release`, e.g. make `registry_address` and `registry_port` configurable via helm
* Usage of `shalm` (https://github.com/kramerul/shalm) to install the helm charts (`cf-operator`, `kubecf`, `eirini`) to address dependencies, e.g. timing, secrets that have to be "smuggled", ...

**Comment by f0rmiga** [comment]
@HeavyWombat is working on this.

**Comment by viovanov** [comment]
#477 deals with this
