### ISSUE TITLE
[regression] Ingress does no longer work

### ISSUE THREAD

**Issue by phil9909** [cloudfoundry-incubator/kubecf#475]
**Describe the bug**
`kubecf-credhub-0` and `kubecf-uaa-0` are in `CrashLoopBackoff` because container `cf-cli-6-linux-*-internal-security-group-setup` crashes when using ingress (with globally valid certificate).

RCA:
- [setup_internal_security_group.sh](https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/assets/scripts/jobs/cf-cli-6-linux/setup_internal_security_group.sh) failes.
- `credhub.yaml` and `uaa,yaml` set the `CF_API_CA_CERT` env to the router CA.
https://github.com/cloudfoundry-incubator/kubecf/blob/c60006d131c0339b947733c95f52f5fbc5496a11/deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml#L57-L65
https://github.com/cloudfoundry-incubator/kubecf/blob/c60006d131c0339b947733c95f52f5fbc5496a11/deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml#L57-L65

**To Reproduce**
Deploy kubecf with ingress enabled and valid certificate configured.

**Expected behavior**
kubecf should boot normally.

**Environment**
master @ https://github.com/cloudfoundry-incubator/kubecf/commit/c60006d131c0339b947733c95f52f5fbc5496a11

**Workaround**

I created a workaround in our fork. https://github.com/akhinos/kubecf/commit/c40ba44d9cef94782336701929961a886be34c97
The `CF_API_CA_CERT` env won't be set, if  ingress is enabled (`.Values.features.ingress.enabled=true`). I'm not sure if this is correct in all cases.

Should I open a PR for this or is there a better solution?

**Comment by f0rmiga** [comment]
https://github.com/cloudfoundry-incubator/kubecf/issues/480 should also fix this.

**Comment by phil9909** [comment]
> #480 should also fix this.

I think so

**Comment by f0rmiga** [comment]
@phil9909 I'm working on this.

**Comment by cmoulliard** [comment]
Can you share your `values.yaml` file passed to helm to configure `kubecf please` ?
Do you also configure the `externalIP` when you use ingress ? 
@phil9909
