### ISSUE TITLE
Use the SUSE eirinifs

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#476]
**Is your feature request related to a problem? Please describe.**

In order to have SSH with Eirini, we need to use https://github.com/SUSE/eirinifs-sle15-release.

**Describe the solution you'd like**

Consume the `eirinifs-sle15-release` and set the appropriate properties to make it work. `cf ssh` should work with Eirini apps.

**Additional context**

This is a follow-up from https://github.com/cloudfoundry-incubator/kubecf/pull/464.

**Comment by f0rmiga** [comment]
The commit on SCF for reference on adding it: https://github.com/SUSE/scf/commit/d9edcc41a48d6a2a500ab5791df062bbb47d83b7.

**Comment by viovanov** [comment]
This needs to work with the helm chart.
We shouldn't need the rootfs patcher.

**Comment by fargozhu** [comment]
https://github.com/cloudfoundry-incubator/bits-service-release/blob/master/docker/eirini-rootfs-downloader/eirini-rootfs-downloader.sh#L62

**Comment by jimmykarily** [comment]
This is how upstream is downloading the eirinifs: https://github.com/cloudfoundry-incubator/bits-service-release/blob/master/docker/eirini-rootfs-downloader/eirini-rootfs-downloader.sh#L62 (just for reference)

**Comment by jimmykarily** [comment]
PR to make the eirinifs downloading optional: https://github.com/cloudfoundry-incubator/bits-service-release/pull/41/files

We used a bits pod which had the eirinifs vendored in and it works fine.

**Comment by viovanov** [comment]
Current state:

- [ ] opi
- [x] route_collector
- [x] route_pod_informer_image
- [x] route_statefulset_informer_image
- [x] staging_reporter_image
- [x] recipe-downloader
- [x] recipe-executor
- [x] recipe-uploader
- [x] event_reporter_image
- [x] event-reporter
- [x] metrics_collector_image
- [ ] eirinifs
- [ ] bits

We still need to build the the opi image, and inject the eirinifs in the bits image
