### ISSUE TITLE
Add routing-api instance_group with a feature_flag

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/kubecf#486]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For some of our CF instances, we do not use the `routing_api` job. Therefore it would be good for us to implement a feature_flag in KubeCF, were the charts user, can enable/disable this.

**Describe alternatives you've considered**
We can have many overrides on top of KubeCF to do this, but it will be a more elegant solution to have this directly in KubeCF, also for future users, were they do not require the routing_api instance_group.

**Additional context**
None. If we agree on this issue, I would like to propose this via a PR.

**Comment by f0rmiga** [comment]
I don't see an immediate benefit in doing this from the description of the issue. Could you expand a bit more? What happens if I disable it? Do I need to replace it with something else?

**Comment by qu1queee** [comment]
as mentioned in the routing-api [docs](https://github.com/cloudfoundry/routing-api#cf-routing-api-server), this is used for exposing an API to register routes. For internal clients we have `nats` and we do not have external ones. Therefore I think if is removed, it will have none effect. 

Also, `kubecf` make this `routing-api` job an instance-group, basically a new pod, any reasons behind that implementation?

**Comment by f0rmiga** [comment]
The reason for extracting the `routing-api` from the `api` instance group is because it only does active-passive HA mode, not active-active like the rest of the `api` jobs. For the same reason, we created the `auctioneer` instance group.

**Comment by f0rmiga** [comment]
If it makes sense to simply remove it, let's have the option!

**Comment by qu1queee** [comment]
Working on this in https://github.com/qu1queee/kubecf/tree/qu1queee/486

**Comment by mook-as** [comment]
If I remember things correctly, `routing-api` is required to have working TCP routing? (At least, I think that's why we originally included it in… scf? Stackato? Something.)  For clusters that don't require that, it might make sense to disable it (assuming my memory is correct).  However, as far as I know `cf-deployment` doesn't allow it to be disabled either? Not that necessarily dictates whether it should be disable-able in kuebcf…

**Comment by qu1queee** [comment]
@mook-as you brought a really good point. I think if routing-api is disabled, then the `tcp-router` needs also to be disabled. 

>However, as far as I know cf-deployment doesn't allow it to be disabled either? Not that necessarily dictates whether it should be disable-able in kuebcf…

I think that does not mean it cannot be removed, is just the base YAML, but you can do many overrides, of course, only if we all agree.

**Comment by viovanov** [comment]
@qu1queee can this be closed now because #544 was merged?
