### ISSUE TITLE
Refactor and migrate suse-buildpacks release image CI to kubecf

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#488]
**Is your feature request related to a problem? Please describe.**
Parent Issue: #220

Current Location: https://github.com/SUSE/cf-ci/tree/develop/kubecf-build-pipelines/buildpacks

We need to migrate the pipeline definition for `suse-buildpacks` pipeline over to https://github.com/cloudfoundry-incubator/kubecf/tree/master/.concourse

**Describe the solution you'd like**
Make appropriate changes as part of the migration and verify that the pipeline is being successfully deployed.

Use Gomplate instead of ERB.

**Comment by bikramnehra** [comment]
@mudler @jimmykarily would we have enough resources on https://concourse.suse.dev/ to build release images? The build process is suppose to run on concourse containers similar to `concourse.suse.de` as you will already be aware.

**Comment by jimmykarily** [comment]
I think is should be ok. If it's not we should make it so. That pipeline should run in the public accessible concourse.
