### ISSUE TITLE
Generating cf-operator charts with bazel does not specify a version

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/kubecf#495]
**Describe the bug**
When running ` bazel build //deploy/bundle:cf_operator_chart` , the generated tgz have none version.
```sh
$ bazel build //deploy/bundle:cf_operator_chart
INFO: Analyzed target //deploy/bundle:cf_operator_chart (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //deploy/bundle:cf_operator_chart up-to-date:
  bazel-bin/deploy/bundle/cf-operator-{version}.tgz
INFO: Elapsed time: 0.602s, Critical Path: 0.40s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```
The above is missleading, while I would expect this version to indicate what charts version from the cf-operator is the kubecf using.

**To Reproduce**
Re-run the above bazel target from inside kubecf repo.

**Expected behavior**
A proper versioned file, e.g. `bazel-bin/deploy/bundle/cf-operator-3.2.tgz`

**Environment**
 - CF Version
 - Component/Plugin Name
 - Others

**Additional context**

**Comment by f0rmiga** [comment]
This got fixed on https://github.com/cloudfoundry-incubator/kubecf/pull/494. This target exists to be used in the bundle. Both files inside the bundle don't have the version in the name.

**Comment by qu1queee** [comment]
thanks a lot!, closing this issue
