### ISSUE TITLE
PRs to fix patches in *eirini-loggregator-bridge* upstream project

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#502]
./eirini/eirini-loggregator-bridge/bpm/patch_bpm.sh

**Comment by fargozhu** [comment]
relates with #12

**Comment by mudler** [comment]
I'll try to have a look. But before accumulating even more fixes, we need to get rid of https://github.com/cloudfoundry-community/eirini-bosh-release/pull/74 as causes issues with current KubeCF Eirini deployments and  https://github.com/cloudfoundry-community/eirini-bosh-release/pull/72 . 

The last one changes how components are started, which basically touches the same code parts of this patch
