### ISSUE TITLE
Confirm kubecf works on Kube 1.17

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#531]
**Is your feature request related to a problem? Please describe.**
Since Kubernetes 1.17 is available and a couple implementations exist already, including SUSE's CaaS Platform 4.1.2, we should verify that kubecf works on that version.

**Comment by viccuad** [comment]
Note that CaaSP 4.1.2 is still 1.16 (see [release notes](https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4/#_changes_in_4_1_2)).

**Comment by f0rmiga** [comment]
Better catch any issue related to 1.17 earlier than later. I _think_ I had a couple of servers with k8s 1.17 a month-ish ago. I'll confirm this soon.

**Comment by f0rmiga** [comment]
This PR on cf-operator is related to a k8s cluster I currently have running 1.17.4 version: https://github.com/cloudfoundry-incubator/cf-operator/pull/885.

**Comment by f0rmiga** [comment]
After the fix on cf-operator, this seems to work just fine.
Once the cf-operator bump is merged here, we can close this issue.
