### ISSUE TITLE
Add upgrade from previous kubecf to CI

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#535]
**Is your feature request related to a problem? Please describe.**
Based on an error spotted during upgrade tests, which involved a change in variable names, we should ensure kubecf users are able to upgrade without issue. Therefore, we should add a test to the CI for an upgrade from `N-1` to `N` to make sure we catch things that could eventually go into documentation.

**Comment by viovanov** [comment]
This should test from latest published release -> current master.

**Comment by jimmykarily** [comment]
Working on it here: https://github.com/cloudfoundry-incubator/kubecf/tree/add_upgrade_test

**Comment by f0rmiga** [comment]
@jimmykarily I see that the logic is implemented on Catapult. Could you link the work there so we can review that the logic is enough to keep this issue closed? I have some particular concerns about this upgrade story.

**Comment by jimmykarily** [comment]
@f0rmiga there was no new functionality implemented in catapult. The only new code is here: https://github.com/cloudfoundry-incubator/kubecf/pull/664/files . I just used known and working catapult targets to deploy the latest stable release and then upgrade to the given commit.

**Comment by jimmykarily** [comment]
One thing that may not be clear: the new concourse task relies on the catapult exit status which is non-zero when the deployment fails.
