### ISSUE TITLE
Use helm repo when installing cf-operator

### ISSUE THREAD

**Issue by manno** [cloudfoundry-incubator/kubecf#542]
The cf-operator has a helm repo at https://cloudfoundry-incubator.github.io/quarks-helm/.

Please update documentation and such, to use that repo, instead of S3.

ping @fargozhu 

[#171741424](https://www.pivotaltracker.com/story/show/171741424)

**Comment by fargozhu** [comment]
@manno we are deploying cf-operator from the kubecf bundle which contains the cf-operator version supported on that specific kubecf release.

@f0rmiga would make sense to pull cf-operator from helm repo instead of s3 bucket?
