### ISSUE TITLE
Unable to install on IBM Cloud IKS (IBM Kubernetes Service) - need specific installation guide

### ISSUE THREAD

**Issue by ylecleach** [cloudfoundry-incubator/kubecf#555]
@fargozhu 
**Describe the bug**
I am trying to deploy KubeCF on IBM Cloud 's IBM Kubernetes Service (IKS) for 2 weeks but without any success. I am following installation procedure, but I am not able to find the proper configuration (values.yaml) to deploy kubecf 101. I have tried on  kube 116 and 117. 

I am also relying on this [important file](https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/values.yaml) to help me configure the values.yaml, but it would need more examples contextualized : on AWS, on GCP, on Azure, on IBM Cloud.

**To Reproduce**
1) get a fresh instance of IKS on IBM Cloud (116 or 117) - ex: 2 nodes of 4 vCPU - 16 Gb RAM

2) configure the values.yaml

```
bash-3.2$ cat values.yaml
system_domain:  kubecf.card-4c.com

kube:
  service_cluster_ip_range: 172.30.0.0/16
  pod_cluster_ip_range: 172.21.0.0/16
  psp:
    default: mypsp
  storage_class: ibmc-block-bronze
features:
  eirini:
   enabled: true

the DNS is operational : 
```
ping kubecf.card-4c.com
PING kubecf.card-4c.com (169.50.36.146): 56 data bytes
64 bytes from 169.50.36.146: icmp_seq=0 ttl=49 time=14.203 ms
64 bytes from 169.50.36.146: icmp_seq=1 ttl=49 time=15.460 ms

I have tried to remove the following restrictive PSP but without solving my installation issue 
```
kubectl get clusterrolebinding | grep psp
kubectl delete clusterrolebinding privileged-psp-user
kubectl delete clusterrolebinding restricted-psp-user

```
bash-3.2$ cat mypsp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mypsp
spec:
  privileged: true  #  allow privileged pods!
  # The rest fills in some required fields.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'

I have also installed successfullu IKS Block Storage plugin, and used the storage_class ibmc-block-bronze, it seems to be working fine, no error.

3) download and unzip the 1.0.1 bundle, configure the KUBECONFIG, then

kubectl create ns cf-operator
helm install cf-operator \
  --namespace cf-operator \
  --set "global.operator.watchNamespace=kubecf" \
   cf-operator.tgz

helm install kubecf --namespace kubecf --values values.yaml kubecf.tgz

**Expected behavior**
````
Every 2,0s: kubectl get po -n kubecf                                                                                                                                                      MacBook-Pro-de-Yves.local: Wed Mar 25 08:14:58 2020

NAME                                            READY   STATUS       RESTARTS   AGE
kubecf-adapter-0                                0/4     Init:5/9     16         8h
kubecf-api-0                                    0/15    Init:30/63   15         8h
kubecf-bosh-dns-59cd464989-slmsk                1/1     Running      0          8h
kubecf-bosh-dns-59cd464989-vf7vb                1/1     Running      0          8h
kubecf-cc-worker-0                              0/4     Init:5/9     16         8h
kubecf-credhub-0                                0/6     Init:7/13    16         8h
kubecf-database-0                               1/2     Running      1          8h
kubecf-database-seeder-44b092e7c9a356d8-j9wnz   1/2     Running      0          8h
kubecf-diego-api-0                              0/6     Init:5/14    16         8h
kubecf-doppler-0                                0/9     Init:7/16    16         8h
kubecf-log-api-0                                0/7     Init:6/13    16         8h
kubecf-nats-0                                   4/4     Running      0          8h
kubecf-routing-api-0                            0/4     Init:5/10    16         8h
kubecf-scheduler-0                              0/8     Init:8/17    16         8h
kubecf-singleton-blobstore-0                    0/6     Init:6/11    16         8h
kubecf-uaa-0                                    0/7     Init:8/15    16         8h**Environment**

 - CF Version
1.0.1

 - Component/Plugin Name
KubeCF installation

 - Others

I have seen the following error in kubecf-database-0 pod :
````
I AM kubecf-database-0 - 172.30.159.86
Warning: resolveip is deprecated and will be removed in a future version.
resolveip: Unable to find hostid for 'kubecf-database-repl': host not found
I am the Primary Node

Events:
  Type     Reason     Age                  From                   Message
  ----     ------     ----                 ----                   -------
  Warning  Unhealthy  32s (x3178 over 8h)  kubelet, 10.215.10.45  Readiness probe failed: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Additional context**
```
helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8+IKS", GitCommit:"c6910e70b932ed9ffe5baedade2274a72925660f", GitTreeState:"clean", BuildDate:"2020-03-13T14:13:41Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Thank you for your help.
Note : IBM also propose on IBM Cloud a Cloud Foundry Enterprise Environment (CFEE), fully managed, with an EIRINI option at installation time. Not tried at this time.

**Comment by danielvaughan** [comment]
I am also trying to do this but I am not making many changes to values.yaml. I have got this far:

```
NAME                                            READY   STATUS             RESTARTS   AGE
kubecf-adapter-0                                4/4     Running            0          27h
kubecf-api-0                                    0/15    Init:30/63         54         27h
kubecf-bits-0                                   0/6     Init:8/15          54         27h
kubecf-bosh-dns-59cd464989-bb5mz                1/1     Running            0          27h
kubecf-bosh-dns-59cd464989-jhtkt                1/1     Running            0          27h
kubecf-cc-worker-0                              0/4     Init:5/9           54         27h
kubecf-credhub-0                                0/6     Init:7/13          54         27h
kubecf-database-0                               1/2     Running            3          27h
kubecf-database-seeder-3c08718ce5da7166-wf8h9   1/2     Running            0          27h
kubecf-diego-api-0                              4/6     CrashLoopBackOff   267        26h
kubecf-doppler-0                                0/9     Init:7/16          54         27h
kubecf-eirini-0                                 9/9     Running            163        27h
kubecf-log-api-0                                0/7     Init:6/13          54         27h
kubecf-nats-0                                   4/4     Running            0          27h
kubecf-router-0                                 0/5     Init:5/11          54         27h
kubecf-routing-api-0                            0/4     Init:5/10          54         27h
kubecf-scheduler-0                              0/8     Init:8/17          54         27h
kubecf-singleton-blobstore-0                    0/6     Init:6/11          54         27h
kubecf-tcp-router-0                             0/5     Init:5/11          54         27h
kubecf-uaa-0                                    0/7     Init:8/15          54         27h
```

**Comment by f0rmiga** [comment]
@qu1queee Did you ever get it deployed with the embedded database on IKS?

Also, I wonder if this issue is related to https://github.com/cloudfoundry-incubator/kubecf/pull/567.

**Comment by fargozhu** [comment]
@ylecleach  @danielvaughan I am closing this issue. Feel free to reopen or open a new one if you get blocked at some point.
