### ISSUE TITLE
URL without info about image registry

### ISSUE THREAD

**Issue by rohitsakala** [cloudfoundry-incubator/kubecf#556]
**Describe the bug**
All the images listed under the `releases` section of the kubcf manifest should have info about docker registry, stemcell info. Some images sections do not have those.

**To Reproduce**
`bazel run //rules/helm:template.sh`

**Environment**
 - KubeCF master

**Additional context**
Release section shoud not have image info like these :

```
- name: bpm
  sha1: e7d474c3a205fa4438ea5a60d3b59479939163aa
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.7
  version: 1.1.7
- name: bosh-dns-aliases
  sha1: b0d0a0350ed87f1ded58b2ebb469acea0e026ccc
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.3
  version: 0.0.3
```

**Comment by jandubois** [comment]
This issue is no longer present.
