### ISSUE TITLE
Environment dependent flaky database startup

### ISSUE THREAD

**Issue by andreas-kupries** [cloudfoundry-incubator/kubecf#566]
**Describe the bug**

On a slow(? (*)) system it is possible for the `kubecf` database pod to get stuck and not reach the running state. Initial investigation shows that the server process somehow started on a broken mysql data directory, tries to recover and fails to reach a working state where other components can reach it and log in. At that point the cluster-to-be is hosed as many parts require a working database service to fully start or run.

**To Reproduce**

This is a difficult to reproduce issue as it seems to require a relatively slow foundation for some reason.

**Investigation Result**

The deeper investigation shows the following sequence of operations:

- The database pod starts, its containers start.
- The command `mysqld --user=mysql --datadir=/var/lib/mysql --initialize-insecure` is run to initialize the data directory.
- The command aborts with no output (*). It leaves a partially initialized data directory behind.
- The failed container is restarted. Multiple times. Each run of the initialization seems to get a bit further in completing the directory. (From the logs added during the debugging).
- At some point however the command creates the `/var/lib/mysql/mysql` directory before it aborts.
- At this point the initialization is still not complete, however because the above directory is used as the sentinel/flag for completion the next restart bypasses initialization and starts the server instead.
- At this point the server finds a partially initialized data directory. It manages to partially recover from that, but not fully. In the end the server is not usable and not ready, and everything else in the cluster waiting for the database cannot make progress any longer.

(*) It was never determined why the command aborts in the slower environment (HDD backing the minikube). It was never seen in an environment where minikube was backed by an SSD.

**Expected behavior**

Proper server startup

**Projected Solution**

Given that the initialization makes progress on each container restart it is assumed that the initialization will reach completion at some point. It seems to be only the ill-chosen sentinel which prevents that from happening. Using a different sentinel file and explicitly creating it only when initialization has completed should make things work.

Pull request containing this solution is https://github.com/cloudfoundry-incubator/kubecf/pull/567

**Comment by mudler** [comment]
I think that's the issue we have been experiencing @jimmykarily . The odd thing is we can reproduce this in one machine with 100% ratio

**Comment by andreas-kupries** [comment]
As bad as the problem is, I am also so glad that I am not the only one seeing this.

**Comment by andreas-kupries** [comment]
The proposed ticket #567 is merged with slight tweaks. This is therefore done.
