### ISSUE TITLE
Consume latest eirini-loggregator-bridge

### ISSUE THREAD

**Issue by mudler** [cloudfoundry-incubator/kubecf#575]
**Is your feature request related to a problem? Please describe.**
The eirini-loggregator-bridge fix is merged in the eirini-bosh-release https://github.com/SUSE/eirini-loggregator-bridge/issues/4 , we should at least bump to the latest to avoid pod crash loops https://github.com/cloudfoundry-community/eirini-bosh-release/pull/74

**Describe the solution you'd like**
Bump eirini-bosh-release in the meantime that we cannot consume the Eirini native chart

**Describe alternatives you've considered**
Not bumping it is not an option, as otherwise we stuck with https://github.com/SUSE/eirini-loggregator-bridge/issues/4

**Comment by f0rmiga** [comment]
I guess we need to bump the whole eirini-bosh-release, right?

**Comment by mudler** [comment]
Yup! but if we do https://github.com/cloudfoundry-incubator/kubecf/issues/578 first, we don't need to use the bosh release necessarily. We could just avoid to consume the jobs from the bosh release and create a separate pod for the extensions (ssh, persi, persi-broker and loggregator-bridge)

**Comment by fargozhu** [comment]
I would prefer to wait and avoid the bosh release...

**Comment by mudler** [comment]
Closing, as it was fixed when https://github.com/cloudfoundry-incubator/kubecf/pull/681 was merged, but not valid anymore since we don't consume anymore the eirini bosh release.
