### ISSUE TITLE
 Eirini-loggregator-bridge is missing logs

### ISSUE THREAD

**Issue by mudler** [cloudfoundry-incubator/kubecf#576]
**Describe the bug**
https://github.com/SUSE/eirini-loggregator-bridge/issues/6

**To Reproduce**
Deploy Kubecf with latest eirini-loggregator-bridge code

**Expected behavior**
Logs shouldn't be lost, but at most be delayed because with the EiriniX bump, the watcher implementation is bookmarked.

**Comment by gaktive** [comment]
Looking for an update @mudler when you get a chance :)

**Comment by mudler** [comment]
I think we can close this, I've bumped the dependencies in EiriniX here: https://github.com/SUSE/eirinix/pull/31 which includes a bunch of fixes also regarding watchers. The fix isn't in KubeCF yet as the bosh-release was removed as part of the Eirini native chart integration, so we have to wait for https://github.com/cloudfoundry-incubator/kubecf/pull/771 to be in
