### ISSUE TITLE
Don't consume Eirini extensions from the bosh-release

### ISSUE THREAD

**Issue by mudler** [cloudfoundry-incubator/kubecf#578]
**Is your feature request related to a problem? Please describe.**
To include changes from Eirini extensions, we need to bump the eirini-bosh-release

**Describe the solution you'd like**
With KubeCF, there is no need to consume eirini-bosh-release jobs, but they can be native components. This would help integrating the extensions with #465 

**Describe alternatives you've considered**
Keep using the eirini bosh release

**Additional context**
Needs #653 and #652 and #477 
See #577

**Comment by fargozhu** [comment]
depends on #477

**Comment by mudler** [comment]
It doesn't necessarily, we can still consume eirini as-is from the bosh release, and avoiding to consume the extensions job
