### ISSUE TITLE
spike: support for include_container_networking tests

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/kubecf#596]
**Is your feature request related to a problem? Please describe.**
Not a problem but I think KubeCF does not have support for container networking. It would be interesting to understand the reasons, and mainly to know what are the next steps to do for having this support.

**Describe the solution you'd like**
None currently.

**Describe alternatives you've considered**
none

**Additional context**
Yes, this would be required for having full CF parity.

**Comment by f0rmiga** [comment]
I guess we need to enable https://github.com/cloudfoundry-incubator/kubecf/blob/2cf693c261b95fbb5f32e56f392876b8bea30390/deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml#L29-L30.

**Comment by qu1queee** [comment]
I think is more than that, we should come up with a list of things we actually require, e.g:
- releases
- instance groups
- variables

**Comment by qu1queee** [comment]
More context on this, https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-diego/builds/164#L5e84c8c5:11425:11527 shows that when we enable:
- `include_container_networking`
- `include_service_discovery`
- `include_security_groups`
all related tests, failed.

**Comment by f0rmiga** [comment]
I'll label this as a bug because it reduces the compatibility with the default cf-deployment features.

**Comment by viovanov** [comment]
We have to test to see what happens when we enable this feature and report back.

**Comment by troytop** [comment]
This is a blocker for using internal domains, which are a very useful feature (and in the CFCD curriculum). https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#internal-domains

**Comment by sourix** [comment]
I agree with @troytop . We use internal domains and container-to-container networking extensively in classic cloud foundry and would be great to have this supported in KubeCF.

**Comment by viovanov** [comment]
This will be done as part of #776
