### ISSUE TITLE
suse-dotnet-core buildback bump broken 

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#599]
**Describe the bug**
I noticed that the [suse-dotnet-core-buildpack](https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/values.yaml#L95-L101) is not getting bumped, it seems like the pipeline which bumps it is broken for some reason and needs more investigation.

**To Reproduce**
Check the pipeline.

**Expected behavior**
The buildpack must be bumped similar to other buildpacks.

**Environment**
 - CF Version: NA
 - Component/Plugin Name: Buildpacks
 - Others

**Additional context**
NA

**Comment by mudler** [comment]
We have to adapt the pipeline to build the dotnet-sdk `3.x` series, already working on it for CAP

**Comment by bikramnehra** [comment]
@mudler I filed this issue originally for `kubecf-buildpacks` pipelines which I noticed is broken for `dotnet-core` on https://github.com/SUSE/cf-ci/blob/develop/kubecf-build-pipelines/buildpacks/tasks/create_pr.sh

**Comment by bikramnehra** [comment]
@mudler I just fixed the above issue, may be you can review: https://github.com/SUSE/cf-ci/pull/373

**Comment by mudler** [comment]
Sorry, we confused this with the issue we have to build newer bosh-releases of dotnet, will create another card for it, thanks!

**Comment by bikramnehra** [comment]
https://github.com/SUSE/cf-ci/pull/373 merged and generated: https://github.com/cloudfoundry-incubator/kubecf/pull/676
