### ISSUE TITLE
Allow affinity to be set for the instance group pods

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#606]
**Is your feature request related to a problem? Please describe.**

Not necessarily, but it can become a problem on some production systems that want to direct the pods to specific affinity.
Setting the `affinity` also helps the k8s scheduler to do a better job.

**Describe the solution you'd like**

Have a clear way to pass the pod `affinity` to the instance group pods.

**Describe alternatives you've considered**

**Additional context**

If the cf-operator doesn't yet support this, it must be implemented there first.

**Comment by fargozhu** [comment]
@f0rmiga I would say that this is a _pure_ cf-operator implementation. Am I wrong?

**Comment by f0rmiga** [comment]
Well, there's a cf-operator side of it, but we need to expose the API to set it on KubeCF.

**Comment by gaktive** [comment]
Some connection to https://github.com/cloudfoundry-incubator/kubecf/issues/254 regarding affinity, which has a higher priority now based on production environment observations.
