### ISSUE TITLE
Document how to run (smoke) tests from a helm deployment

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#618]
**Is your feature request related to a problem? Please describe.**
People are asking on Slack on how to run smoke tests to validate the cluster after deploying from the helm chart release (i.e. not via a dev tree using bazel). We should document that.

**Describe the solution you'd like**
We should document (maybe in [kubecf-docs](https://github.com/cloudfoundry-incubator/kubecf-docs/blob/master/content/en/docs/Reference/tests.md)?) on how to do that.

It would probably be something like:
`kubectl patch qjob kubecf-smoke-tests --namespace kubecf --type merge --patch '{ "spec": { "trigger": { "strategy": "now" } } }'`
(But by the time we document this, we would have cf-operator 4.0.0, so the qjob will be named `smoke-tests`.)

**Describe alternatives you've considered**
We might also want to consider shipping the smoke test as a [helm test](https://helm.sh/docs/topics/chart_tests/).  This would not apply to CATS / brains.

**Additional context**
* https://github.com/cloudfoundry-incubator/kubecf/issues/545#issuecomment-608602647
* https://cloudfoundry.slack.com/archives/CQ2U3L6DC/p1585940337094600

**Comment by jandubois** [comment]
This would also be much more obvious if we had a script for this, like in the proposed bash replacement for bazel: https://github.com/cloudfoundry-incubator/kubecf/blob/ab6026b7dbc88fabde68a8acb92a9c4a435d61b3/scripts/testing-smoke.sh

**Comment by f0rmiga** [comment]
@jandubois This is not a discussion about Bazel. Keep it in the right thread.

**Comment by f0rmiga** [comment]
Also, this ticket is about documentation, not scripting the whole testing flow.

**Comment by jandubois** [comment]
Dude, you need to chill down!

The whole issue came up because the command to run smoke tests is completely obfuscated by bazel. If it was exposed as a script, you would not have to document is separately, beyond pointing to the script.

*Readable* code can help out when documentation is out of date or incomplete...

**Comment by viovanov** [comment]
This should be done from the point of view of a user of kubecf (not a developer working on kubecf).

**Comment by mook-as** [comment]
https://kubecf.suse.dev/docs/reference/tests/ and https://kubecf.suse.dev/docs/reference/layout/testing/ has docs for a developer to run the tests (via `bazel`).

**Comment by viccuad** [comment]
I'm currently looking into running them as `helm test`. For completeness, here is the docs to trigger the smoke-tests job as a user, to be pushed into kubecf-docs in case I fail to add `helm test`:

```
# Smoke tests

KubeCF's helm chart ships the Cloud Foundry smoke tests, packaged inside of a
deployment's instance group, so they can be run against said deployment.

## Enabling Smoke tests

To enable them in your KubeCF deployment add the following into values.yaml:

    ---
    # values.yaml

    testing:
      smoke_tests:
        enabled: true

If you did this on an already deployed KubeCF release, remember to upgrade your
deployment with:

    $ helm upgrade kubecf --namespace kubecf --values values.yaml

(See the docs for upgrading your KubeCF deployment).


## Triggering Smoke tests

The smoke tests are run by a CF-Operator qjob (a wrapper on Kube jobs). That job
is defined to not trigger automatically by default. To start it, patch the job
with trigger strategy "now":

    $ kubectl get qjob --namespace scf --output name 2> /dev/null | grep smoke-tests
    quarksjob.quarks.cloudfoundry.org/smoke-tests


    $ kubectl patch quarksjob.quarks.cloudfoundry.org/smoke-tests \
             --namespace kubecf --type merge --patch \
             '{ "spec": { "trigger": { "strategy": "now" } } }'

This will start the job, which creates a `smoke-tests-<id>` pod. Inside that
pod, there's a container called `smoke-tests-smoke-tests` with the test run.

You can, as usual, see the resulting logs from the smoke-tests pod with:

    $ kubectl logs -f smoke-tests-614496c133797980-bm2g4 --namespace scf \
              --container smoke-tests-smoke-tests
    Running smoke tests...
    Running binaries smoke/isolation_segments/isolation_segments.test
    smoke/logging/logging.test
    smoke/runtime/runtime.test
    [1592406628] CF-Isolation-Segment-Smoke-Tests - 4 specs - 7 nodes SSSS SUCCESS! 13.717155722s
    [1592406628] CF-Logging-Smoke-Tests - 2 specs - 7 nodes S• SUCCESS! 36.291956367s
    [1592406628] CF-Runtime-Smoke-Tests - 2 specs - 7 nodes S• SUCCESS! 30.456607562s

    Ginkgo ran 3 suites in 1m21.517660359s
    Test Suite Passed

The pod will exit with a return code of `0` if successful, and other if not.
```

**Comment by viccuad** [comment]
Tried to add the smoke-tests in `helm test`, but failed. Looked for a way to save the smoke-tests instance group from cf-deployment as autorerrand (instead of manual errand) in `templates/tests/` , but I can't find a way. The alternative that I see is to start a hackish pod using `templates/tests/` , and from that pod do a kubectl patch  with trigger strategy now.

Running them as part of `helm test` can go to another card.

Opened the following to just document on kubecf.suse.dev how to run them as a user:

https://github.com/cloudfoundry-incubator/kubecf-docs/pull/16

**Comment by mook-as** [comment]
Merged in https://github.com/cloudfoundry-incubator/kubecf-docs/commit/89970269698661487da909ff285209f57ae68671 and visible in https://kubecf.suse.dev/docs/tutorials/run-smoke-tests/
