### ISSUE TITLE
The logs container on test pods prevents them from getting cleaned up

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#620]
**Describe the bug**

cf-operator injects the `logs` container on the tests pods that prevents them from running to completion.

**To Reproduce**

Run any of the tests...

**Expected behavior**

The pods should not contain the `logs` container.

**Environment**

All.

**Comment by viovanov** [comment]
Probably needs some work in the cf-operator.

**Comment by mook-as** [comment]
This interacts badly with #324 (and we should fix this after that).

**Comment by viovanov** [comment]
Ping @qu1queee
