### ISSUE TITLE
Conventional Commits & Release Notes Automation

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#624]
**Is your feature request related to a problem? Please describe.**

A way to enforce better commit messages to follow what was proposed [here](https://github.com/cloudfoundry-incubator/kubecf/blob/master/doc/architecture/decisions/0002-git-commit-messages.md) and shaping it with [best practices](https://www.conventionalcommits.org/en/v1.0.0/).

**Describe the solution you'd like**

Automation through a [bot](https://probot.github.io/apps/semantic-pull-requests/).

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by jimmykarily** [comment]
I see the benefit of using conventional commits. I don't know how easy it is to do in practice. I can see myself forgetting all about it and then having to rewrite git history to make the bot happy.

**Comment by fargozhu** [comment]
@jimmykarily you may have to edit only the pull request summary.

**Comment by fargozhu** [comment]
It will be applied only to the pull request message and not to the commits.
