### ISSUE TITLE
CATs docker tests are failing

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/kubecf#625]
**Describe the bug**
When enabling the `include_docker` tests for CATs, all docker tests fail.

**To Reproduce**
See https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-diego/builds/164#L5e84c8c5:11425:11527

**Expected behavior**
Tests should be passing.

**Additional context**
None

**Comment by f0rmiga** [comment]
So, I get success when I enable the feature with `cf enable-feature-flag diego_docker`.

```
Ran 3 of 213 Specs in 79.165 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Flaked | 1 Pending | 209 Skipped


Ginkgo ran 1 suite in 1m19.391493533s
Test Suite Passed
```

@viovanov Do we want this feature enabled by default?

**Comment by viovanov** [comment]
@f0rmiga yes, let's enable it by default
FYI @troytop

**Comment by f0rmiga** [comment]
I'll make it enabled by default as part of this issue, then.

**Comment by troytop** [comment]
Do not change the diego_docker default setting in KubeCF. We should keep it disabled by default as long as cf-deployment does. Please instead change the test to run a `cf enable-feature-flag diego_docker` before executing the relevant tests.
