### ISSUE TITLE
Seeder job for external databases

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#629]
**Is your feature request related to a problem? Please describe.**

Currently, there's no shortcuts to seeding an external database. Doing it should be as simple as setting a boolean value on `values.yaml`.

**Describe the solution you'd like**

Add the `features.external_database.seed` property to control whether the seeder should run or not.

https://github.com/cloudfoundry-incubator/kubecf/blob/d7bc0ef05b947d74f0769fa00365fc5c848e0ad3/deploy/helm/kubecf/values.yaml#L262-L264

```diff
    external_database:
+     seeder:
+       enabled: false
+       admin:
+         username: ~
+         password: ~
      enabled: false
      require_ssl: false
```

A job should be set up to seed the database using the `admin` credentials.

**References on SCF**

https://github.com/SUSE/scf-helper-release/blob/master/jobs/database-seeder/templates/pre-start.erb
https://github.com/SUSE/scf-helper-release/blob/master/src/database-seeder/main.go
https://github.com/SUSE/scf/blob/develop/container-host-files/etc/scf/config/role-manifest.yml#L686-L696

**Comment by gaktive** [comment]
This was doable in SCF.

**Comment by gaktive** [comment]
If the credentials aren't specified, we shouldn't fail. We should assume the user created the databases manually.

**Comment by troytop** [comment]
Instructions or a helper script would suffice, and certainly be better than nothing.

**Comment by satadruroy** [comment]
Instructions for setting up an external DB are currently in docs (may need some cleanup as it's not entirely clear which db names it's referring to - should be the `name` keys under each database). 

https://documentation.suse.com/suse-cap/2.0.1/single-html/cap-guides/#id-1.3.4.4.14.6

**Comment by mook-as** [comment]
#1388 merged; this is now waiting on me to finish writing the documentation before we close.
