### ISSUE TITLE
Support for custom eirini staging images.

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#640]
**Is your feature request related to a problem? Please describe.**
Currently we using hard-coded values for eirini-staging images: https://github.com/cloudfoundry-incubator/kubecf/pull/608/files#diff-8e190b66df231646a528bed8a0145181R151. We must add the ability to customize it like all the other releases.

**Describe the solution you'd like**
The values must not be hard-coded and come from: https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/values.yaml like other releases.

**Additional context**
We must keep a track of using appropriate images that are compatible with current eirini release being used.

**Comment by viovanov** [comment]
This is no longer required, we have #744 for this.
