### ISSUE TITLE
Facing issue while pipeline trying to start : upload failed: ./1586408459-1122f6179bc8f51f2167eb8cb69bb83f65f467dc.json to s3://kubecf-ci/build-queue/1586408459-1122f6179bc8f51f2167eb8cb69bb83f65f467dc.json An error occurred (AccessDenied) when calling the PutObject operation: Access Denied 

### ISSUE THREAD

**Issue by mukulk2020** [cloudfoundry-incubator/kubecf#642]
I am trying to deploy the concourse pipeline in local ubuntu machine with below commands

./fly -t target set-pipeline -p kubecf
fly -t target up -p kubecf
kubecf pipeline deployed successfully but when it start it showing below error
"upload failed: ./1586408459-1122f6179bc8f51f2167eb8cb69bb83f65f467dc.json to s3://kubecf-ci/build-queue/1586408459-1122f6179bc8f51f2167eb8cb69bb83f65f467dc.json An error occurred (AccessDenied) when calling the PutObject operation: Access Denied".

Please suggest where is the problem ?
[kubecf-screenshots.docx](https://github.com/cloudfoundry-incubator/kubecf/files/4454262/kubecf-screenshots.docx)

**Comment by f0rmiga** [comment]
It seems like it tries to upload the file to our S3 bucket as an intermediary step between jobs.
We will need to provide a nicer way to replace these values by one that you control.
@jimmykarily Could you help with this? I'll leave it for you to create a story for the templating part if you believe it's necessary.

**Comment by jimmykarily** [comment]
You can use the config.yaml file to point it to a different bucket.
Docs here: https://github.com/cloudfoundry-incubator/kubecf/tree/master/.concourse#pipeline-development.
Sample config.yaml file here: https://github.com/cloudfoundry-incubator/kubecf/blob/master/.concourse/config.yaml.sample

**Comment by f0rmiga** [comment]
@jimmykarily Thanks!
@mukulk2020 I'll close this issue for now. Please, don't hesitate in opening it again if the documentation doesn't work for you.
