### ISSUE TITLE
Helm chart for Eirini Extensions

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#652]
**Is your feature request related to a problem? Please describe.**
Helm chart for the Eirini Extensions

**Describe the solution you'd like**
Helm chart that deploys all eirini extensions.
No feature flags required.

**Additional context**
#578 #653

It needs `SUSE/eirinix-helm-release`

**Comment by mook-as** [comment]
It looks like we don't have docker images for the Eirini extensions yet (eirini-logging, eirini-ssh ×2, eirini-loggregator-bridge, eirini-persi, eirini-persi-broker).

I guess I'll add a concourse pipeline definition in [SUSE/eirinix-helm-release](https://github.com/SUSE/eirinix-helm-release) and build docker images there (all pretty simple, as they're all standard-looking golang programs), and then do the helm chart from there?  Alternatively, we can have build stuff in each extension repo instead (with proper releases or something), but I'm not sure if we can use [GitHub package registries](https://github.com/features/packages) (at a minimum, we'll need to keep a copy for provenance purposes, and can't build with [GitHub actions](https://github.com/features/actions/), I think?).

@viovanov / @f0rmiga: let me know if you have any alternative ideas.

**Comment by f0rmiga** [comment]
@mook-as I'd put the pipeline definition for build the images on SUSE/eirinix-helm-release. We can do it with TravisCI, which is simple and we have that enabled for the SUSE org.

**Comment by f0rmiga** [comment]
Also, you want to avoid the GitHub package registry, as it requires authentication for downloading the images, even if they are public.

**Comment by mook-as** [comment]
Conclusion from out-of-band discussion is that _building_ images on TravisCI isn't a great idea due to provenance reasons; so we will need to build on concourse to ensure all the bits come from hardware under our control.  We can still do tests via TravisCI, but we don't need that for this task.

And from [Thulio's comment](https://github.com/cloudfoundry-incubator/kubecf/issues/652#issuecomment-613011915) the GitHub registry is out.

**Comment by mook-as** [comment]
https://github.com/SUSE/eirinix-helm-release/pull/1 created to build the docker images.
Now working on the helm chart.

**Comment by mook-as** [comment]
Actual chart review now in https://github.com/SUSE/eirinix-helm-release/pull/3

**Comment by viovanov** [comment]
this looks like it's done
