### ISSUE TITLE
CI pipeline for building and publishing the EiriniX helm chart

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#653]
**Is your feature request related to a problem? Please describe.**
Concourse pipeline for building the EiriniX helm chart

Should publish the helm chart tar.gz as an asset on the github releases page.

**Additional context**
#578 #652

**Comment by mook-as** [comment]
Blocked on #652 (because there's nothing to make a CI pipeline for yet).

**Comment by mook-as** [comment]
Note to self: need to make sure we tag the images correctly (as in, not just `latest`).

**Comment by viovanov** [comment]
@mook-as #652 is done - is this unblocked now?

**Comment by mook-as** [comment]
Yep, this is unblocked (and I'm working on it).

**Comment by mook-as** [comment]
Ooops, the CI built the chart and pushed to S3… and didn't update any `index.yaml` anywhere, so it wasn't _published_ in any way that we could consume from kubecf.

Reading the original description, I guess I should put it on github releases somewhere, instead. Will figure out the requisite credentials.  In that case, I'll also make GitHub (pages) be a helm repository.

**Comment by mook-as** [comment]
The helm chart updating is having issues: when the chart is updated (because the docker images changes, for example), the GitHub release is updated but it's not triggering a helm repo index rebuild.  Hopefully fixed in https://github.com/SUSE/eirinix-helm-release/pull/8.
