### ISSUE TITLE
Not possible to reproduce KubeCF pipelines as SUSE/cf-ci-pools.git is private

### ISSUE THREAD

**Issue by danielvaughan** [cloudfoundry-incubator/kubecf#661]
**Describe the bug**
It would be good to be able to reproduce the concourse build pipelines in another environment however as SUSE/cf-ci-pools.git is a private repo this is not possible.

**To Reproduce**
Attempt to run the concourse pipelines in the .concourse directory without knowing a git hub private key that has access to SUSE/cf-ci-pools.git.

**Expected behavior**
SUSE/cf-ci-pools.git  could be public and if that is not possible create instructions for how to reproduce a compatible project.

**Environment**
 - Using v1.0.1 of KubeCF

**Additional context**

**Comment by f0rmiga** [comment]
Related to https://github.com/cloudfoundry-incubator/kubecf/issues/665.

**Comment by fargozhu** [comment]
I am closing this one in favor of #665
