### ISSUE TITLE
Use weave in CI so we can run the internetless suite

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#671]
**Is your feature request related to a problem? Please describe.**
We don't have a way to run the internetless test suite.

**Describe the solution you'd like**
Use weave in CI so we can control network traffic.

**Describe alternatives you've considered**
n/a

**Additional context**
#144 
https://github.com/SUSE/catapult/issues/161

**Comment by viovanov** [comment]
This has to be supported in EKCP

**Comment by viccuad** [comment]
Closing, this is not relevant anymore; we use GKE on GH Actions and Concourse for CI. And with https://github.com/SUSE/catapult/pull/317 GKE uses Calico and networkPolicies to configure the airgap for cats internetless, which will be leveraged for GH Actions in https://github.com/cloudfoundry-incubator/kubecf/issues/1148.
