### ISSUE TITLE
CI is being flooded by PRs to bump buildpack stemcells and versions

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#706]
**Describe the bug**

For every new stemcell that comes out, there's a pipeline that bumps all the SUSE buildpacks. This is causing CI to be way too busy for those automated PRs and not handling the human-opened ones properly.

**To Reproduce**

Look at the history of PRs and their statuses.

**Expected behavior**

The pipeline should open a single PR for bumping the stemcells. It still should open separate PRs for bumping the buildpack versions.

**Environment**

CI

**Comment by bikramnehra** [comment]
moving this to in progress as its being handled as part of: https://github.com/cloudfoundry-incubator/kubecf/issues/488
