### ISSUE TITLE
Bundles should contain a sample values.yaml with commented defaults

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#711]
**Is your feature request related to a problem?**

Users should be able to use a values.yaml without actually overriding anything.
It's tempting to grab values.yaml from the chart and start editing, but using the same file in a future release wouldn't work well.
A user could grab a values.yaml from the bundle that has all values commented out, except for the mandatory ones.

**Describe the solution you'd like**
- each bundle should contain a sample-values.yaml with the optional keys commented out.
- the yaml file contains comments for each key, that contain:
  - a description of the key
  - a markup that indicates whether the key is mandatory, optional, or invisible
- the file is linted so that all keys have a comment like this

**Describe alternatives you've considered**
Documentation, but that doesn't help anyone.

**Additional context**

**Comment by mook-as** [comment]
See also: #736

**Comment by andreas-kupries** [comment]
Fixed with https://github.com/SUSE/bits-service-release/pull/4 in bits.
Still needed: kubecf update.
Handing back to @mook-as
