### ISSUE TITLE
Integration of Kube native UAA into KubeCF

### ISSUE THREAD

**Issue by rohitsakala** [cloudfoundry-incubator/kubecf#730]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Integrating Kube-Native UAA as sub helm chart. 

*Problem - How to deploy UAA as kube resources ?*
UAA docker image is provided by the UAA team. [0]
UAA is deployed as a Deployment resource.
UAA configuration is stored in a Secret resource which is mounted as a file. 

*Problem - How does UAA handle tls termination ?*
We need to add envoy proxy as a side container to act as tls termination proxy.

*Problem - How does UAA get updated when configuration changes ?*
CF-Operator will provide this functionality. Whenever a configmap/secret changes, the referenced Deployment,Sts gets updated. [1]

*Problem - What if the UAA CA certificates are rotated ?*
No problem, since var-uaa-ssl secret is mounted by envoy container. So, when a rotation occurs to this secret, the cf components as well as UAA get updated.

*Problem - What happens when other configuration such as JWT signing key, UAA client secrets get rotated ?*
These values are stored as secrets in KubeCF. When these are rotated, the cf components get updated but we need to figure out a way to udpate the UAA configuration stored in the secret.

[0] https://hub.docker.com/r/cfidentity/uaa
[1] https://www.pivotaltracker.com/story/show/172404604

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by viovanov** [comment]
This needs to be behind a feature flag.

**Comment by mook-as** [comment]
See https://github.com/cloudfoundry/uaa#running-the-uaa-on-kubernetes / https://github.com/cloudfoundry/uaa/tree/develop/k8s for info.

We'll need to think about upgrades.

**Comment by mook-as** [comment]
Current status:
- I have a spike going at [my fork/marky/native-uaa](https://github.com/cloudfoundry-incubator/kubecf/compare/master...mook-as:marky/native-uaa); it's not ready for review. (I'll push it to the upstream repo for review.)
  - It's rather hacky, and has quite a few missing things:
    - Need to handle config better: currently I'm stealing the BDPL-based UAA instance group's OAuth clients list.
    - As a first step it only handles ingress-based clusters.  Will need a route registrar.
      - This may get resolved at some point if we move to istio as well (see #860).
- It'll require quarks-operator 5.0 (to be able to point `uaa.service.cf.internal` at non-BDPL-based things).  That means it depends on #1049.

**Comment by mook-as** [comment]
Now that operator 5.0 landed, we can progress forward.

- I'm still stealing the BDPL's UAA configs.
- Added a route registrar; seems to work for now.
- Flipping from BOSH-UAA to native-UAA is busted, because of https://github.com/cloudfoundry-incubator/quarks-operator/issues/1023 — the old UAA QuarksStatefulSet (and therefore pod) doesn't go away, so things start getting conflicted.

**Comment by mook-as** [comment]
Finding more issues with operator (because this is a weird new way of using it); filed https://github.com/cloudfoundry-incubator/quarks-operator/issues/1043

**Comment by jandubois** [comment]
There is no longer a plan to move to native components from cf4k8s. kubecf will continue to use bosh releases from cf-deployment.
