### ISSUE TITLE
Improvements to bits/eirini helm chart

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#733]
List of things we should help implement in the upstream helm chart for bits:

- [ ] [bits] expose the registry using a `nodePort` (M)
-  [ ] [bits] don't use secrets in a `ConfigMap` (see [here](https://github.com/cloudfoundry-incubator/bits-service-release/blob/master/helm/bits/templates/bits.yaml#L65) ) (S)
-  [ ] [eirini] full registry address should be configurable in eirini (including port) (S)
- [ ] [eirini] remove rootfs patcher (and find out what it does) (XS)
- [ ] [eirini & bits] ability to set arbitrary labels/annotations for `Deployments` and `StatefulSets` (M)

**Comment by fargozhu** [comment]
for the rootfs patcher https://github.com/cloudfoundry-incubator/eirini/blob/master/rootfspatcher/patcher.go

**Comment by mook-as** [comment]
> ability to set arbitrary labels/annotations for Deployments and StatefulSets

This is for the eirini component pods (not the deployed apps)
So that
1. We can group all kubecf components together.
2. Restart them as their input config changes.

**Comment by viovanov** [comment]
This was split into #792 #793 #794 #795 #796
