### ISSUE TITLE
Detailed documentation for each value in values.yaml

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#736]
**Is your feature request related to a problem? Please describe.**
Lack of documentation in `values.yaml`

**Describe the solution you'd like**
Just like in SCF, each value has a comment.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mook-as** [comment]
https://github.com/cloudfoundry-incubator/kubecf/pull/1056 added to start on the documentation (and to ensure we don't add any new ones lacking comments).  Will still leave this open though, as that doesn't include all the sub-chart knobs.

**Comment by mook-as** [comment]
Closing this as good enough: if we want more, we could consider writing a schema for the file instead.
