### ISSUE TITLE
cfdot job does not work on kubecf

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#738]
**Describe the bug**

[cfdot](https://github.com/cloudfoundry/cfdot) is a commandline interface to the Diego BBS API. I wanted to use it to investigate why an app remained in a `starting` state, but no instances got scheduled.

`cfdot` is supposed to be installed by the cfdot job from diego-release into at least the `diego-cell` instance group, but potentially all other diego related ones too.

It uses a [pre-start](https://github.com/cloudfoundry/diego-release/blob/develop/jobs/cfdot/templates/pre-start.erb) script to copy [shell setup](https://github.com/cloudfoundry/diego-release/blob/develop/jobs/cfdot/templates/setup.erb) code to `/etc/profile.d`, which in turn sets up some config variables and puts the `/var/vcap/packages/cfdot/bin` directory on the `PATH`.

**To Reproduce**

Connect to the `diego-cell` pod and verify that neither `/etc/profile.d/cfdot.sh` nor `/var/vcap/packages/cfdot/bin/cfdot` exist.

**Expected behavior**

I don't see a way for the init container running the pre-start script to push the setup script into `/etc/profile.d`.

I would suggest that both (an updated) `cfdot.sh` script as well as the `cfdot` tool itself be copied to `/var/vcap/data/cfdot/bin`. The user will then have to run `source /var/vcap/data/cfdot/bin/cfdot.sh` to get a configured `cfdot` on the `PATH`.

**Additional context**

`cfdot` is purely a debugging tool used by developers (and admins) to investigate problems with the Diego scheduler. It is not used during normal operation, and is not accessible to regular CF users.

**Comment by andreas-kupries** [comment]
Looking through the `cf-deployment.yaml` the `cfdot` job is run in three instance groups:
  - scheduler
  - diego-api
  - diego-cell

**Comment by andreas-kupries** [comment]
PR = #975
