### ISSUE TITLE
Building Eirini SLE images

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#744]
**Is your feature request related to a problem? Please describe.**

- `eirini/opi` (overridable with `.Values.opi.image` and `.Value.opi.image_tag`)
- `eirini/event-reporter` (overridable with `.Values.opi.event_reporter_image`
and `.Values.opi.event_reporter_image_tag`)
- `eirini/metrics-collector` (overridable with
`.Values.opi.metrics_collector_image` and `.Values.opi.image_tag`)
- `eirini/bits-waiter` (overridable with `.Values.opi.bits_waiter_image` and
`.Values.opi.image_tag`)
- `eirini/rootfs-patcher` (overridable with `.Values.opi.rootfs_patcher_image`
and `.Values.opi.image_tag`)
- `eirini/route-collector` (overridable with
`.Values.opi.route_collector_image` and `.Values.opi.image_tag`)
- `eirini/route-pod-informer` (overridable with
`.Values.opi.route_pod_informer_image` and `.Values.opi.image_tag`)
- `eirini/route-statefulset-informer` (overridable with
`.Values.opi.route_statefulset_informer_image` and `.Values.opi.image_tag`)
- `eirini/staging-reporter` (overridable with
`.Values.opi.staging_reporter_image` and
`.Values.opi.staging_reporter_image_tag`)

The repository that has the code and pipeline definitions to build the
upstream images seems to be this one:
https://github.com/cloudfoundry-incubator/eirini-ci/tree/master/pipelines

**Describe the solution you'd like**
Build SLE images for KubeCF for consistency.

**Extra context**

The following images are already being built.

```
eirini/recipe-downloader
eirini/recipe-executor
eirini/recipe-uploader
```

**Comment by jimmykarily** [comment]
[Somehow](https://github.com/cloudfoundry-incubator/eirini-ci/blob/master/pipelines/dhall-modules/jobs/create-go-docker-images.dhall#L25) the dockerfiles here are being used: https://github.com/cloudfoundry-incubator/eirini/tree/master/docker .

**Comment by jimmykarily** [comment]
If an image is "FROM scratch" do we care to rebuild on SLE? E.g. https://github.com/cloudfoundry-incubator/eirini/blob/master/docker/bits-waiter/Dockerfile#L8

**Comment by jimmykarily** [comment]
Created a PR to make the base image configurable in the upstream Dockerfiles: https://github.com/cloudfoundry-incubator/eirini/pull/91

A command like the following, issued form the root directory of the eirini repository, builds the opi image with a SLE base:

```
docker build -t opi-sle . -f docker/opi/Dockerfile \
  --build-arg GIT_SHA=$(git -C . rev-parse HEAD) \
  --build-arg baseimage="registry.opensuse.org/cloud/platform/stack/rootfs/images/sle15:latest"
```

**Comment by jimmykarily** [comment]
Most of the upstream images are built `FROM scratch`. We will do the same so we probably won't need the above PR. Still left to do:

```
- opi image is built on ubuntu because of this: https://github.com/cloudfoundry-incubator/eirini/commit/d0587acbc1523247051f35a4099016942410a12                                               
- there are images which we don't know if we should build or not (e.g. inside the opi directory there is an init directory with a Dockerfile)                                                 
- We need to build the bits pod image (with the Dockerfile in the bits-service-release) and inject the eirinifs in that                                                                       
- Make sure there is other image based on anything other than "scratch"
- Integrate all the above images in kubecf and test
- Cleanup any not needed PRs (e.g. the baseimage build arg in the eirini repo, if we end up using "FROM scratch")
```
