### ISSUE TITLE
Image list for eirini images

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#745]
**Is your feature request related to a problem? Please describe.**
All the eirini images should be present in `image_list.json`.

**Describe the solution you'd like**
Alter the build so it contains all the images mentioned in #744 .

**Comment by jimmykarily** [comment]
We need to take care of the downloader,executor and uploader images too: https://github.com/cloudfoundry-incubator/eirini-release/blob/master/helm/eirini/templates/configmap.yaml#L20
