### ISSUE TITLE
Helm packaging fails if git revision starts with `0`

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#766]
**Describe the bug**
If the git commit hash starts with `0`, then `bazel build //deploy/helm/kubecf` fails with:
> `Error: Version segment starts with 0`

**To Reproduce**
1. Make commits until the git commit hash starts with `0`
2. Run `bazel build //deploy/helm/kubecf`

**Expected behavior**
Build completes successfully.

**Environment**
- Kubecf [master](https://github.com/cloudfoundry-incubator/kubecf/commit/1699ccd2728df2a5735596047c990e447cd0513f) + a local commit that happens to start with `0` (`0266605f…`)

**Additional context**
- [`package.tmpl.rb`](https://github.com/cloudfoundry-incubator/kubecf/blob/1699ccd2728df2a5735596047c990e447cd0513f/rules/helm/package.tmpl.rb#L65) makes the version `v0.0.0-0266605f` (or something like that).
- This appears to not work; see https://github.com/helm/helm/issues/7064

We may want to change it to `v0.0.0-g0266605f` or something like that, similar to `git describe` output (where a `g` prefix ensures that identifier does _not_ count as numeric).

**Comment by viovanov** [comment]
Might be fixed by #1010

**Comment by mook-as** [comment]
Still present in [one of my runs](https://github.com/mook-as/kubecf/runs/883079157?check_suite_focus=true) for the GitHub Actions spike, which is only using the new make based thing, so probably not.

**Comment by jandubois** [comment]
The problem should only happen when the commit id is fully numeric **and** starts with a `0`, which is not allowed by semver. It is enforced at https://github.com/Masterminds/semver/blob/60c7ae8/version.go#L582-L585

This issue should go away when we switch to using https://github.com/SUSE/kubecf-tools/blob/main/versioning/versioning.rb, which will have a leading `g` before the commit id.

@viovanov Are we going to move the `kubecf-tool` repo to the `cloudfoundry-incubator` org? I don't think we should use the script while the repo is still in the `SUSE` org.
