### ISSUE TITLE
Make c2c networking work

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#776]
**Is your feature request related to a problem? Please describe.**
c2c networking is not enabled in KubeCF.

**Describe the solution you'd like**

- [x] implement a CoreDNS plugin that replaces the bosh dns adapter
- [ ] enable the CATS group for c2c networking
- [x] support in Quarks

**Describe alternatives you've considered**
n/a

**Additional context**
This will likely require more containers with extra privileges and support in Quarks for more BOSH DNS features.

**Comment by fargozhu** [comment]
@viovanov do we have any use cases to support this spike?

**Comment by viovanov** [comment]
@fargozhu this is a feature of CF that has many usecases, and is also requested by our IBM friends
ping @qu1queee

**Comment by smoser-ibm** [comment]
@viovanov this would be the last missing  piece for us regarding a CF Bosh ->  K8s migration. Can we bump the importance of this maybe ?

**Comment by qu1queee** [comment]
This is on my radar, trying to find someone from our side to help, I dont have too much bandwidth for this atm.

**Comment by viovanov** [comment]
@JimmyMa can you please add a comment here with your setup and your findings?

**Comment by mook-as** [comment]
This is expected to run (and fail) on minikube.

**Comment by viovanov** [comment]
We need to implement an "App DNS" as described below:

![app dns diagram](https://docs.google.com/drawings/d/e/2PACX-1vTWqgVvy2_tGJ4I3jisuw6IvWxM8Jt3B6_eRV_FabhC2tY_CyC0mUbOMJ7FhXYglBygJVx2yMEfEiGz/pub?w=1465&h=653)

**Comment by viovanov** [comment]
Ping @JimmyMa ⬆️
@f0rmiga is starting work on that app dns server

**Comment by f0rmiga** [comment]
A few notes based on our call:
- A patch to the `silk-cni` job is most likely needed to be able to get the k8s svc cluster IP from the injected env var to be used by the Garden Container `/etc/resolv.conf`. We have done similar patches in the past, so it should be simple.
- Configuring the Apps DNS to use the Quarks DNS as the upstream server might be tricky unless we make the Apps DNS a BOSH-release and let the quarks-operator do the magic to point its `/etc/resolv.conf` to the Quarks DNS. That's not going to be my first attempt but I'll certainly fall back to this approach to avoid doing any clever tricks that might compromise future maintainability.
- The Apps DNS should contain a CoreDNS plugin that calls the Service Discovery Controller.

**Comment by f0rmiga** [comment]
For the Apps DNS configuration file, we don't actually need to use `/etc/resolv.conf` as upstream, we can just generate the CoreDNS configuration that resolves the Quarks DNS svc IP during the Apps DNS initialization.

**Comment by f0rmiga** [comment]
For the Apps DNS plugin to talk to the Service Discovery Controller, it uses mTLS, so it's easier if we just call the `service-discovery-controller.service.cf.internal` as all the certs are generated for this common name already. For that, we can use a custom resolver for the Go HTTPS client used by the svc discovery client. This is doable because at this point we already know the Quarks DNS IP address (see my previous comment).

**Comment by smoser-ibm** [comment]
@andrew-edgar ^^ for your awareness (and to make sure its not impacting your merge-DNS solution you build for us). I don't think it does, but want your awareness and confirmatio

**Comment by viovanov** [comment]
I've changed this issue so now it tracks the work that we're doing to make c2c work.

**Comment by viovanov** [comment]
> * onfiguring the Apps DNS to use the Quarks DNS as the upstream server might be tricky unless we make the Apps DNS a BOSH-release and let the q

@f0rmiga the Quarks DNS Kube Service should be available before the Apps DNS is started.
That means you can use the env var for it in the Apps DNS. Is there anything else missing?

**Comment by f0rmiga** [comment]
First PR for apps-dns: https://github.com/SUSE/kubecf-apps-dns/pull/1.
