### ISSUE TITLE
Publish the helm chart to upstream kubernetes/charts

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#78]

**Comment by loewenstein** [comment]
@viovanov This issue refers to https://github.com/helm/charts as 'kubernetes/charts' or is that another chart repository I am not aware of?

**Comment by fargozhu** [comment]
@viovanov can you please add more detailed information to the description section.

**Comment by viovanov** [comment]
This should go to hub.helm.sh.
We'll get a new repo called `kubecf-helm.
We already do this in the [quarks operator release pipeline](https://github.com/cloudfoundry-incubator/cf-operator-ci/tree/master/pipelines/cf-operator-release/tasks)

**Comment by Akayeshmantha** [comment]
Hi @viovanov  @mudler  so the ci scripts should go inside the Kube-cf project or the new repo. The new repo is to store the build artifacts ?

**Comment by viovanov** [comment]
https://github.com/cloudfoundry-incubator/kubecf-helm is ready for PRs

**Comment by viovanov** [comment]
this is a duplicate of #1492
