### ISSUE TITLE
bits: expose the registry using a nodePort

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#792]
**Is your feature request related to a problem? Please describe.**
We don't expose the internal eirini registry publicly.
We want to expose it using a nodeport, so the nodes can easily reach it.
Right now we're using our own service for this.

**Describe the solution you'd like**
The upstream bits helm chart should allow exposing its service using a NodePort

**Comment by andreas-kupries** [comment]
@viovanov Questions

>  We don't expose the internal eirini registry publicly.

Is that true ? 
The bits helm chart (BHC) has a `services.loadbalanced` property.
While the default is `false` (causing no type to be set, making it `ClusterIP`),
in the `kubecf`this is set to `true`, giving service `bits` the `type: LoadBalancer`.
Is that not fully exposed ?

>  Right now we're using our own service for this.

Which service is that, and where?

**Comment by viovanov** [comment]
@andreas-kupries the service we use is here:
https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/templates/eirini.yaml#L54-L68

it should be part of the bits chart

**Comment by andreas-kupries** [comment]
Thanks.

**Comment by andreas-kupries** [comment]
PRs:
  - bits: SUSE/bits-service-release/pull/7
  - kubecf: #1022

**Comment by andreas-kupries** [comment]
Blocked by #1179 as work on that can/will make this here moot.

**Comment by jandubois** [comment]
> Blocked by #1179 as work on that can/will make this here moot.

#1179 has been merged and includes the ingress service inside the `bits` mixin. I believe there is nothing left to do here.
