### ISSUE TITLE
bits: don't use secrets in a ConfigMap

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#793]
**Is your feature request related to a problem? Please describe.**
We shouldn't expose secrets in ConfigMaps.

**Describe the solution you'd like**
The ConfigMap [here](https://github.com/cloudfoundry-incubator/bits-service-release/blob/master/helm/bits/templates/bits.yaml#L65) should be converted to a secret.

**Comment by andreas-kupries** [comment]
@mook-as I reviewed the PR and approved. I cannot merge it however, per ` The base branch restricts merging to authorized users. ...`. Do you know who can ? @viovanov maybe ?

**Comment by andreas-kupries** [comment]
Reopened for the kubecf PR

**Comment by mook-as** [comment]
I'll make the PR after #862 lands to avoid conflicts (on the digest in `requirements.lock`); unfortunately that one is blocked due to CI (#864).
