### ISSUE TITLE
eirini: full registry address should be configurable(including port)

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#794]
**Is your feature request related to a problem? Please describe.**
Eirini doesn't allow a full address to the image registry to be specified.
It concatenates it based on various settings.

**Describe the solution you'd like**
A user should be allowed to set the exact full address of the registry (including port).

**Comment by mook-as** [comment]
@viovanov I assume this is talking about [`opi.registry_address`](https://github.com/SUSE/eirini-release/blob/b71bd3d9f19913caee43aa39a2a99eb265fd0978/helm/eirini/templates/configmap.yaml#L11-L17)?

**Comment by andreas-kupries** [comment]
Eirini PR merged. Back to Mark for the kubecf version bump of this.
