### ISSUE TITLE
eirini & bits: ability to set arbitrary labels/annotations for Deployments and StatefulSets

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#795]
**Is your feature request related to a problem? Please describe.**
Upstream helm charts don't allow setting arbitrary labels and annotations for their deployments, statefulsets and pods.
We need this in order to control annotations for quarks operator restart behavior, and for identification labels.

**Describe the solution you'd like**
A user should be able to annotate and label the deployments, stses and pods of the upstream helm charts.

**Comment by andreas-kupries** [comment]
Lets start slowly ... Bits Release ...

### bits templates - Current kube objects and labels/annotations

|Name		|Kind		|Notes					|
|---		|---		|---					|
|<tls_secret_name>|Secret	||
|bits		|ConfigMap	|					|
|bits		|Deployment	|template labels, fixed (`name=bits`)	|
|bits		|Service	|annotations (flag: service.externalDNS)|
|bits-registry	|Ingress	|labels, fixed (`release`, `heritage`)	|
|		|		|annotations (toYAML: ingress.annotations)|
|bits-service	|PodSecurityPolicy|	annotations, fixed|
|bits-service	|ServiceAccount	||
|bits-service-psp|Role		||
|bits-service-psp|RoleBinding	||

### Proposal

  1. Per the description only the `bits` __Deployment__ has to be changed.
     All other objects are ignored.
     That said, adding and/or extending labels and annotations to everything else should be trivial.
  2. Extend `.Values.global` with keys `labels`, and `annotation`.
     Both new keys take a mapping/dictionary/hash as their value.
     Default for both is the empty hash `{}`.
  3. Extend the deployments `spec.template.metadata.labels` with `{{ toYaml .Values.global.labels | indent 8 }}` to interpolate the user's values.
  4. Add `spec.template.metadata.annotations` to the deployment and `{{ toYaml .Values.global.annotations | indent 8 }}` as well, to interpolate the user's values.

It is now possible to declare arbitrary labels and annotations in a values.yaml, via the `global.labels` and `global.annotations` keys. This is interpolated into the proper location of the target chart, with `toYaml` ensuring the proper syntax and quoting.

@f0rmiga @viovanov Thoughts ? Reactions ? Counters ?

**Comment by andreas-kupries** [comment]
Eirini release looks to be as simple as well.

### eirini templates - current kube objects of interest

|Name		|Template	|Kind		|Notes							|
|---		|---		|---		|---							|
|eirini		|deployment.yaml|Deployment	|template labels, fixed (name, eirinifs_version)	|
|eirini-events	|events.yml	|Deployment	|template labels, fixed (name) 				|
|eirini-metrics	|metrics.yaml	|Deployment	|template labels, fixed (name) 				|
|eirini-routing	|routing.yaml	|Deployment	|template labels, fixed (name) 				|
|eirini-staging-reporter|staging-reporter.yaml|Deployment|template labels, fixed (name)			|

Table reduced, ignored all the uninteresting objects.

Generally no statefulsets found, nor pods.

There is a Daemonset (`loggregator-fluentd`), unsure if that counts.

Same general proposal for introducing arbitrary labels and annotations.

**Comment by andreas-kupries** [comment]
Implementation branches:

  - https://github.com/andreas-kupries/bits-service-release/commits/kubecf-795/arbitrary-labels-and-annotations
  - https://github.com/andreas-kupries/eirini-release/commits/kubecf-795/arbitrary-labels-and-annotations

Note: These are in personal forks for the releases. No PR made for them yet.

**Comment by andreas-kupries** [comment]
Pull requests:

  - https://github.com/cloudfoundry-incubator/bits-service-release/pull/40
  - https://github.com/cloudfoundry-incubator/eirini-release/pull/161

@viovanov Please have a look.

**Comment by andreas-kupries** [comment]
Addressed Vlad's comment about missing the deployments, and just handling the pods.
This is now as ready as it can be.
And in the hands of upstream.

**Comment by andreas-kupries** [comment]
SUSE PR for the bits part = https://github.com/SUSE/bits-service-release/pull/2

**Comment by andreas-kupries** [comment]
SUSE PR for the eirini part = https://github.com/SUSE/eirini-release/pull/1

**Comment by viovanov** [comment]
These are now available in the SUSE dev releases
