### ISSUE TITLE
 Remove the rootfs patcher

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#796]
**Is your feature request related to a problem? Please describe.**
The upstream eirini helm chart uses a "rootfs patcher" to download newer versions of the rootfs.

**Describe the solution you'd like**
We can't download things from the internet like this, so we should not be using the patcher.
There is [a setting](https://github.com/cloudfoundry-incubator/eirini-release/blob/master/helm/eirini/templates/rootfs-patcher.yml#L1) to disable it.
After doing so, also check to see what it does for upgrading apps to the new version of a rootfs, and create a new story, detailing if we need to implement a Job that does something similar on KubeCF upgrades.

**Comment by andreas-kupries** [comment]
Draft PR made for this: #801 

Planning to test local using minikube SA, verify that job is gone, and that smoke works.

**Comment by andreas-kupries** [comment]
Minikube testing ok. confirmed that job and service account are gone (and present without the change).
Smoke has one test failure, same independent of the change. As such smoke is considered working.

**Comment by andreas-kupries** [comment]
# Eirini Notes

These notes came out of investigating the rootfs patcher and its operation.

## Summary

  - The patcher just patches statefulsets, changing the labels on the
    sts itself and its pod template (rootfs version to use).

  - This change triggers redeployment through the standard sts
    controller. The generic Eirini mechanism for app deloyment
    involved in that then uses the new rootfs version, and also
    (apparently) (triggers to) pulls the necessary image.

  - To avoid this internet access see if we can
      - prefill whatever store is used with the necessary image,
      - and if that then prevents the actual download.

  - Not seeing the need for a new KubeCF specific job.

    Eirini is a sub chart of KubeCF AFAIK/CT.

    We should be able to run a `helm upgrade` on the KubeCF chart
    which does not change anything in KubeCF itself, only in Eirini.

## General architecture

Eirini apparently uses two namespaces, `.Release.Namespace` and
`.Values.opi.namespace`, for its control plane, and the applications,
respectively.

The control plane contains Eirini's deployment and associated pods,
etc. The other is where the statefulsets for applications deployed via
Eirini are placed and run. Properly separated from the control plane.

## Rootfs

All cloundfoundry applications are based on a rootfs image which
contains the basic tooling shared across all. This is separate from
buildpacks and the image they will use/insert for the specific kind of
application (php, python, ...).

Eirini provides its own set of rootfs images, outside of
cloudfoundry's `cflinuxfsNNN`, or SUSE's opensuse/sle images.

See `cloudfoundry-incubator/eirinifs` for the repository and releases.

I have not determined yet if the images for the Eirini chart come with
a baked-in rootfs tarball matching the initial/default version.

Even so, AFAICT from descriptions given Eirini will certainly pull a
rootfs tarball from the net (github) when it does not have the
requested version. This likely involves the `bits` service.

## Rootfs Version

The version of the rootfs to use for applications managed by Eirini is
specified via `.Values.global.rootfs_version`. The current default
`v75.0.0`. The most current release is `v150.0.0`.

This information is templated into the Eirini kube definitions and
from there into various config files, command line arguments,
etc. This means that the version is pretty much baked into the running
processes in one kind or other.

## Updating the Rootfs version

Given the information in the preceding section changing/updating the
rootfs version to use involves a `helm upgrade`. In other words, set
`.Values.global.rootfs_version` to a new value, then `helm upgrade`
the __entire__ Eirini deployment. This restarts all the necessary
pods/processes of the control plane which will then contain/know the
new version.

An application started after this upgrade is given the new version,
and the system retrieves the tarball from the internet as part of
that. The limitation of this is that it only updates the Eirini
control plane, and only affects applications started after.

Existing applications are __not__ touched. Further, restarting, even
restaging such will not make a difference. The rootfs version is baked
into the statefulsets representing them, and a simple restart/stage
does not change that.

## Patcher

The patcher comes in to patch(sic) the limitation mentioned in the
preceding section.

It is a job which is run when Eirini is deployed, or upgraded. During
initial deployment this job does not matter, it will not find any
application to modify and thus simply ends.

Of the job's two containers the init container only ensures that
Eirini's `bits` service/deployment exists and is ready. As it will be
needed to pull/store the new tarball for the new version.

The action container talks to the application namespace, locates the
statefulsets, i.e applications, and modifies the labels for
statefulset and pod template to contain the new rootfs version.

Any application/statefulset from before the upgrade to the new version
will see an actual change, thus the sts controller will terminate the
existing pods of the application, and then restage and redeploy new
pods. In contrast to the simple restage (see preceding section)
however the changed label ensures that the new rootfs version is now
used, as desired.

## KubeCF

It is my understanding that Eirini is deployed as a sub chart of KubeCF.

That means, should I understand helm correctly, that a `helm upgrade`
of KubeCF can be used to perform an upgrade of Eirini as well, or just
of Eirini. Dependent on which `.Values` are modified.

IMHO if we can solve the rootfs image download done by Eirini then
nothing speaks against using the standard rootfs patcher coming with
Eirini.

## Issues

### Internet access

The patcher does not pull anything by itself. It simply triggers a
redeployment of applications using the old version, in a manner which
then causes the regular Eirini staging/deployment mechanisms to pull
the new rootfs image from the world.

If we wish to prevent this internet access as part of a rootfs version
change I believe that we should investigate how the rootfs image is
pulled and stored, and if we can prefill the store (`bits` ?) with the
image needed before triggering the `helm upgrade`.

### bits-waiter --namespace misdocumentation

This is the command used by the patcher's init container to check and
wait for the bits service to be present and ready.

As the bits service is part of the control plane is has to access the
namespace `.Release.Namespace`. 

This is configured correctly in command line, role, and role binding.

Contrariwise, the application sources incorrectly claims that the
associated `--namespace` option references the
`Namespace where eirini runs apps`.

This is only a nit where the option is misdocumented. Use and
configuration are all ok.

**Comment by andreas-kupries** [comment]
Note #806

**Comment by andreas-kupries** [comment]
@f0rmiga @viovanov 

Thulio mentioned in the standup that the eirinifs in use is distributed as part of the kubecf setup, right ?

So in normal operation there will not be an update of the eirinifs version ... And we do not plan to update the eirinifs between kubecf releases ?

So version updates for eirinifs would match (be synced to) kubecf releases ? ...

If yes ... I still don't believe we would need our own rootfs patcher ... A kubecf release with an eirinifs bump could simply activate the eirini rootfs patcher during the update, then deactivate it again after it has down its thing. I.e. the `helm upgrade ...` to the new kubecf version would actually be multiple commands instead of single.

Thoughts ?

**Comment by andreas-kupries** [comment]
Closing this now, #808 is the followup to look into the underlying download issue
