### ISSUE TITLE
Bazel targets to wait for the deployment

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#799]
**Is your feature request related to a problem? Please describe.**
When running tests (and when manually deploying), we often need to wait for the helm deployment to complete; for example, we need to wait for cf-operator to complete before deploying kubecf.  It would be nice if we could centralize this code, to ensure that (for local development and for CI) we do the waiting correctly.

**Describe the solution you'd like**
A bazel target we can run that will wait until the deployment is complete.
Something like `bazel run //dev/cf_operator:wait` and `bazel run //dev/kubecf:wait`

**Describe alternatives you've considered**
Local shell scripts. Everybody has one, they're all different, and they're all terrible ;)
e.g. https://github.com/cloudfoundry-incubator/kubecf/compare/vladi-actions-test?diff=unified has an implementation (of sorts) using GNU parallel.

**Additional context**
Was looking at https://github.com/cloudfoundry-incubator/kubecf/compare/vladi-actions-test?diff=unified for unrelated reasons, and got annoyed enough to write this up.

**Comment by jandubois** [comment]
Is there a reason why `helm install|upgrade ... --timeout 600 --wait` cannot be used?

**Comment by mook-as** [comment]
Only that `bazel run //dev/cf-operator:apply` doesn't use it, and as far as I know we can't do it after-the-fact.

**Comment by f0rmiga** [comment]
@jandubois 
There's a bunch of resources that cf-operator creates that Helm won't track. If I'm not mistaken, cf-operator still doesn't implement the status for the readiness of the BDPL, which is what Helm would use to determine if the installation is complete.

**Comment by jandubois** [comment]
> If I'm not mistaken, cf-operator still doesn't implement the status for the readiness of the BDPL, which is what Helm would use to determine if the installation is complete.

Oh, I didn't know that.

I think this would be the right way to implement this though, as the operator should be able to tell when the deployment is done. It feels wrong to replicate this functionality outside of the operator, where is can get out-of-sync with implementation changes.

**Comment by viovanov** [comment]
superseded by #1020
