### ISSUE TITLE
nginx.ingress.kubernetes.io/proxy-body-size too small

### ISSUE THREAD

**Issue by troytop** [cloudfoundry-incubator/kubecf#802]
When setting up KubeCF with nginx-ingress, the default proxy body size is 8 MB. 

This appears to be set here:

https://github.com/cloudfoundry-incubator/kubecf/blob/c7d75ac2ecbfa6ba22b05d5e0a8a7e52a38fb312/deploy/helm/kubecf/templates/ingress.yaml#L54

This prevents `cf push` from being able to deploy all but the smallest applications. The default should be large enough to include a mid-sized Java jar file (spring music is ~48MB). Suggest 64MB as a default and a configuration option in the helm values.yaml to set this explicitly.

**Comment by f0rmiga** [comment]
There's a mix of a bug and a feature as part of this issue.

The default value should be put here:
https://github.com/cloudfoundry-incubator/kubecf/blob/6acd84c104f10fcfb1e6eeaee22f08314b17023f/deploy/helm/kubecf/values.yaml#L248-L254

Meanwhile, you can specify:

```
features:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
```

**Comment by troytop** [comment]
It's nice that it can be overridden (either in values.yaml or directly in Kubernetes), but I would like the default much larger. The default setting should allow for typical Java applications to be deployed.
