### ISSUE TITLE
Configurable bits images

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#807]
PR to fix https://github.com/cloudfoundry-incubator/bits-service-release/issues/42
The images have to be configurable, so we can use our own, based on a SUSE base

**Comment by viovanov** [comment]
Images built in #744 will be used with these new configurable values.

**Comment by andreas-kupries** [comment]
PR = https://github.com/cloudfoundry-incubator/bits-service-release/pull/43

Untested. Looks like a trivial change tough.

**Comment by andreas-kupries** [comment]
Tested locally with help from @jimmykarily . Redirected bits dependency to local modified chart, and added image decls to the bits section of the kubecf chart. Good/Bad image refs have the startup behave as expected, i.e. green, vs `ErrImagePull`.

Ready for review.

**Comment by andreas-kupries** [comment]
SUSE PR = https://github.com/SUSE/bits-service-release/pull/1

**Comment by viovanov** [comment]
Available in the SUSE dev release
