### ISSUE TITLE
Eirini - Make download locations configurable - Followup to: Remove the rootfs patcher #796

### ISSUE THREAD

**Issue by andreas-kupries** [cloudfoundry-incubator/kubecf#808]
**Describe the bug**

The description of #796 claims that  __The upstream eirini helm chart uses a "rootfs patcher" to download newer versions of the rootfs.__

That is not quite true. The rootfs patcher only changes application's labels to the new version. It is the general eirini app deployment code which reacts to the change by (possibly) downloading the newly referenced version of the rootfs, as part of re-deploying the changed app(s).

And the problem there is not that the download happens in general, but that the locations all the things are retrieved from are fixed. Thus forcing a general internet connection, a bad thing for air-gapped installations.

**Expected behavior**

As such, it is requested to investigate the internals of eirini, to determine where downloads happen, how the locations are fixed, and to then make these locations configurable through the eirini (or bits) chart, enabling users (like the kubecf chart) to redirect any downloads initiated by eirini to local servers in the air-gapped environment, thus preventing access to the outside.

And with that issue fixed we can enable the rootfs patcher again too, as it performs an important operation.

**Additional context**

See also #806, which might be another incarnation of the same problem.

**Comment by andreas-kupries** [comment]
Reference https://github.com/cloudfoundry-incubator/bits-service-release/blob/master/docker/eirini-rootfs-downloader/eirini-rootfs-downloader.sh#L62

From https://github.com/cloudfoundry-incubator/kubecf/issues/476#issuecomment-618499401

**Comment by viovanov** [comment]
We already bundle the eirinifs in the bits image, so this isn't needed anymore.
