### ISSUE TITLE
File upstream issue/pr against Eirini to set fsGroup

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#812]
#782 is working around the issue of not having write access to PVCs, and not having root access to `chmod` the mount point.

SUSE/eirini-persi#25 implements this on the persi side, but has to guess as to the correct GID for the running user. It would be much better if `runAsGroup` and `fsGroup` would already be set by Eirini, so they don't have to be (guessed) and added by the admission controller.

**Comment by viovanov** [comment]
We haven't seen instances where this is required anymore.
