### ISSUE TITLE
Don't prefix eirinix resources

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#817]
**Is your feature request related to a problem? Please describe.**
Resources are already namespaced using a namespace, we don't need the prefix (same reason we removed the prefix from everything else).

**Describe the solution you'd like**
Don't use the release name here: https://github.com/SUSE/eirinix-helm-release/blob/master/chart/templates/_helpers.tpl#L31

**Comment by andreas-kupries** [comment]
PR = https://github.com/SUSE/eirinix-helm-release/pull/11

**Comment by mook-as** [comment]
Back to @andreas-kupries now that [the helm repo](https://opensource.suse.com/eirinix-helm-release/index.yaml) has `0.0.0-10+g3df5bb4`

**Comment by andreas-kupries** [comment]
Ok. kubecf PR coming up ASAP.

**Comment by andreas-kupries** [comment]
kubecf PR = https://github.com/cloudfoundry-incubator/kubecf/pull/862
