### ISSUE TITLE
eirini-persi-broker: should use default storage class when unspecified

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#819]
# Status

# Linked Pull requests

  - #1077
  - https://github.com/SUSE/eirinix-helm-release/pull/12
  - https://github.com/SUSE/eirini-persi-broker/pull/6

# Testing

See https://github.com/cloudfoundry-incubator/kubecf/issues/819#issuecomment-649841863

# Post review actions

After positive review and testing of these PRs merging has to be done from the bottom up:

  1. First merge the broker code changes, i.e. https://github.com/SUSE/eirini-persi-broker/pull/6
     This should trigger CI to regenerate all the relevant docker images.
  2. After that the chart changes, i.e. https://github.com/SUSE/eirinix-helm-release/pull/12, should be mergable.
     :warning: I do not know if it will be necessary to bump version numbers and/or tags.
     This may trigger CI to regenerate a downloadable chart. I do not know for sure.
     We certainly will have to get a new version number for the chart, which is needed by the next step.
  3. Now we can update #1077 with the updated chart, and then merge.
     The instructions for updating sub charts are found in `doc/Contribute.md`.

# Description

**Is your feature request related to a problem? Please describe.**
Currently, when using the eirini persi broker, we _must_ specify a storage class.  This is unwieldy for deployment using helm charts, as we cannot rely on the `DefaultStorageClass` admission plugin to give us something sensible.

**Describe the solution you'd like**
- The broker should create a PVC with no storage class (which is distinct from a PVC with an empty string storage class) when no storage class is specified.
- The eirinix helm chart should default to having no storage class specified.

**Describe alternatives you've considered**
Making the customer configure the storage class every time, but that seems terrible.

**Additional context**
This is a feature request for [eirini-persi-broker](https://github.com/SUSE/eirini-persi-broker).

The value is [parsed here](https://github.com/SUSE/eirini-persi-broker/blob/a182eac006237994734e02645c39fe84309fed5b/config/config.go#L45) and [used here](https://github.com/SUSE/eirini-persi-broker/blob/6e9a55465bd9efbc02e9d5831ab55866b342d31e/broker/broker.go#L142); the usage always takes the address of a string, so we cannot pass in null values.  According to the [documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1) we want to _not set_ the storage class name, which is distinct from setting it to the empty string.

**Comment by andreas-kupries** [comment]
Linked pull requests:
  - https://github.com/SUSE/eirinix-helm-release/pull/12
  - https://github.com/SUSE/eirini-persi-broker/pull/6

:warning: These two PRs are __drafts__ in need of testing.

@viovanov @jimmykarily I need information on how to build the eirini persi things locally, for testing locally. I managed to use `docker build .` in the broker repo to at least check that the changes compile. No idea yet how to go beyond that.

**Comment by andreas-kupries** [comment]
Main pipeline is https://concourse.suse.dev/teams/main/pipelines/eirinix
There does not seem to be a pipeline for building from PRs.

Going over the definition of the pipeline in `eirinix-helm-release/.concourse/` it seems to be locked to `master` branch of all input git repositories. Locked as in hardwired into the definition. The branch cannot be changed via the existing gomplating, at all. Not overall, not to speak of per-repository.

How is persi-broker built and tested before merging PRs ?

@mudler Having no response from @viovanov nor @jimmykarily yet (see previous comment), do you know the answers to these questions ?

**Comment by jimmykarily** [comment]
@andreas-kupries iirc all testing was manual for the eirini persi broker PRs. I didn't have to work on this extension so far but maybe my process on testing eirini-ssh can be useful:

1. I compile my new binary
2. I fetch the latest docker image which includes the (not yet modified version of the) binary.
3. I copy my modified binary in the image and commit the image with a new tag
4. I push the image to dockerhub
5. I edit the relevant deployment/statefulset/pod in my running kubernetes cluster to make use of my new image

This process is a bit slow but with kind you don't really need to push the image to dockerhub, you just have to do `kind load docker-image` so the whole cycle can be automated with a script and shouldn't take too long before you have an updated image running in your cluster.

I remember it's possible to run the extensions from outside the cluster and have them register themselves as webhooks but you will need to somehow make sure that kubernetes components can access your webhook server on the registered IP. I wish I could provide more specific instructions but I don't have a running cluster at hand. Give the above a try and if you can't figure it out we could arrange a pairing session.

**Comment by andreas-kupries** [comment]
Minikube has similar functionality to upload an image directly into it. ... I begin to see this looking to be very similar to testing braintests. Which means that I should be able to take guidance from that script on how to edit the pod to use the new image before I am running the cluster (ops file).

Thank you @jimmykarily this should unblock my brain ...

**Comment by andreas-kupries** [comment]
# Testing

Done locally using a minikube in SA/eirini configuration.

It requires __all__ the associated pull requests listed in the relevant section of the description, plus manual work.

Step by step:

  1. You should have a checkout of `kubecf` (already), for #1077 
  2. Get a checkout of  https://github.com/SUSE/eirinix-helm-release/pull/12
  3. Get a checkout of https://github.com/SUSE/eirini-persi-broker/pull/6
     In this checkout do:
       1. Run `docker build .` in the toplevel directory of the checkout.
       2. When done look for the line `Successfully built XXXXX` at the bottom of the build log.
       3. Run `docker tag XXXXX splatform/eirinix-persi-broker:YOUR_CHOSEN_TAG`

  4. Go to the kubecf checkout and do:
       1. Start a kube cluster using `minikube` (or `kind`).
       2. Upload the image tagged in step 3.3 into the cluster.
            - minikube: `docker save IMAGE | ( eval $(minikube docker-env) ; docker load )`
       	    - kind: `kind load IMAGE`
       3. Copy the file `charts/templates/persi-broker.yaml` in the
       	 https://github.com/SUSE/eirinix-helm-release/pull/12 checkout to
       	  `deploy/helm/kubecf/charts/eirini-extensions/templates/persi-broker.yaml`
       4. Edit `deploy/helm/kubecf/charts/eirini-extensions/values.yaml`.
       	  Change `persi-broker.image.tag` to `YOUR_CHOSEN_TAG` (See step 3.3).
	  Change `persi-broker.service-plans[*].kube_storage_class` to `~` (nil, undef).
       5. The steps __4.iii__ and __4.iv__ give us the modified helm chart needed to use the modified persi-broker image we created in step 3 and made available in step __4.ii__. By being in a checkout of #1077 we avoid having to edit the main chart to undo its setting of the persi broker storage class.

  5. Deploy the kubecf to the cluster and check that the `persi-broker` pod uses the new image. Further verify in both pod and controlling deployment that the `kube_storage_class` setting is gone from the `env.SERVICE_CONFIG` definition.

  6. Testing out the service broker and its services:
       1. Register the broker. This is __not__ done automatically.
            1. Retrieve the decoded password for the broker via
               > k get secret :persi-broker-auth-password -o json|jq .data.password|sed -e 's/"//g'|base64 -d
            2. Then register the broker via
               > cf create-service-broker YOUR_BROKER_NAME admin PASSWORD http://eirini-persi-broker:8999
            3. Lastly, enable the new broker's services via
               > cf enable-service-access eirini-persi

       2. Verify that the broker and its services are now known and accessible via
          ```
          cf service-brokers
          cf service-access
          cf marketplace
          cf marketplace -s eirini-persi
          ```

       3. Make a service:
          > cf create-service eirini-persi default mypersi

            1. Check success via `cf services`, and/or `cf service mypersi`.

            2. At this point the system has to give us a PVC for the disk. Check for that using
               > kubectl get pvc --all-namespaces`

               Under the default settings it should be found in the `eirini` namespace.

            3. We actually should get a PV as well, however if the chosen storage class does not exist the PVC will be stuck at state `Pending`. If it was created we can use

               > kubectl get pv

               to see the bound volume. For minikube this volume will have storage class `standard`.

**Comment by mook-as** [comment]
Reviewed https://github.com/SUSE/eirini-persi-broker/pull/6 & https://github.com/SUSE/eirinix-helm-release/pull/12 — #1077 is waiting on those to merge first (so we can update the subchart).

**Comment by andreas-kupries** [comment]
Merged https://github.com/SUSE/eirini-persi-broker/pull/6, after fixing `gofmt` issues.

**Comment by andreas-kupries** [comment]
The https://github.com/SUSE/eirinix-helm-release/pull/12 is merged. Move to step 3, updating #1077 with the chart.
