### ISSUE TITLE
how to use NodePort for kubecf-router-public replacing LB

### ISSUE THREAD

**Issue by rllzyy** [cloudfoundry-incubator/kubecf#831]
I was deploying kubecf in local Rancher,and I did NOT have a LB,
so after i did 
**helm install kubecf  --namespace kubecf  --set system_domain=abcdxxxxx.com  --set features.eirini.enabled=true  https://github.com/cloudfoundry-incubator/kubecf/releases/download/v1.0.1/kubecf-v1.0.1.tgz**
then
**kubectl get svc -n kubecf | grep -i load**
results:
kubecf-router-public           LoadBalancer   10.43.154.153   <**pending**> ...
kubecf-ssh-proxy-public        LoadBalancer   10.43.173.254   <**pending**> ...
kubecf-tcp-router-public       LoadBalancer   10.43.233.154   <**pending**>  ...

so I manually change the type to NodePort
**kubectl edit svc kubecf-router-public -n kubecf**
and find the nodeIP
**kubectl get po kubecf-router-0 -n kubecf -o wide**

then I mapping the NodeIP and api.<system_domain> (e.g. api.abcdxxxxx.com) to my windows hosts
then
 cf api --skip-ssl-validation "https://api.abcdxxxxx.com"
Results:
API endpoint not found at 'https://api.abcdxxxxx.com'

could anyone help me? thx a lot

**Comment by HartS** [comment]
Hi @rllzyy , 

You may want to try upgrading the chart to set externalIPs. First edit all services back to the `LoadBalancer` type (helm should remain consistent with the kubernetes deployment). Then run `helm upgrade -n kubecf --reuse-values --set=services.{router,ssh-proxy,tcp-router}.externalIPs="{1.1.1.1,1.1.1.2,1.1.1.3}" ${release_name} kubecf/` (where 1.1.1.1 etc. are the IPs of your kubernetes worker nodes)

Finally, in addition to `api.abcdxxxxx.com`, you'll also need to ensure `*.abcdxxxxx.com`, `tcp.abcdxxxxx.com`, and `ssh.abcdxxxxx.com` all point to the IP of your worker node as well

**Comment by rllzyy** [comment]
Hi @HartS thx for your help.  But I met another issue as following, could you please help me?
I just made type back to LB and did the following with my nodes IPs
**helm upgrade -n kubecf --reuse-values --set=services.{router,ssh-proxy,tcp-router}.externalIPs="{1.1.1.1,1.1.1.2,1.1.1.3...}" kubecf https://github.com/cloudfoundry-incubator/kubecf/releases/download/v1.0.1/kubecf-v1.0.1.tgz**
and check the external ports:
**kubectl get svc -n kubecf**

added all nodes ip mapping to api.abcdxxxxx.com ,tcp.abcdxxxxx.com and  ssh.abcdxxxxx.com in /etc/hosts **BUT I did NOT know how to add *.abcdxxxxx.com to /etc/hosts....**
1.1.1.1         api.kubecf.mindsphere.com
1.1.1.2         api.kubecf.mindsphere.com
1.1.1.3         api.kubecf.mindsphere.com
1.1.1.1         tcp.kubecf.mindsphere.com
1.1.1.2         tcp.kubecf.mindsphere.com
1.1.1.3         tcp.kubecf.mindsphere.com
1.1.1.1         ssh.kubecf.mindsphere.com
1.1.1.2         ssh.kubecf.mindsphere.com
1.1.1.3         ssh.kubecf.mindsphere.com


then I found if I did cf login with 
cf api --skip-ssl-validation "https://api.abcdxxxxx.com"      //Not work!

cf api --skip-ssl-validation "**https://api.abcdxxxxx.com:31393**"
Results:
Request error: Get https://api.kubecf.mindsphere.com:31393/v2/info: http: server gave HTTP response to HTTPS client
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

cf api --skip-ssl-validation "**http**://api.abcdxxxxx.com:31393"  //it works!
but after
admin_pass=$(kubectl get secret --namespace kubecf kubecf.var-cf-admin-password -o jsonpath='{.data.password}' | base64 --decode)
I did 
cf auth admin "${admin_pass}"
Results
Error Code: 404
Raw Response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

FAILED

**Comment by rllzyy** [comment]
@HartS 
after I added MetalLB for LB, and added the following to /etc/hosts
#kubecf-router-public ip   
134.xxxxxx.160           api.abcdxxxxx.com   
#kubecf-router-public ip   
134.xxxxxx.160           login.abcdxxxxx.com   
#kubecf-tcp-router-public ip   
134.xxxxxx.130           tcp.abcdxxxxx.com   
#kubecf-ssh-proxy-public ip    
134.xxxxxx.170           ssh.abcdxxxxx.com
it works for
cf api --skip-ssl-validation "https://api.abcdxxxxx.com"

one more question:
it seems the defaut cf market place is empty? **how can I add mysql,postgresql,redis,rabbitmq....to the cf marketplace?** 

thx a lot
