### ISSUE TITLE
cf marketplace is empty

### ISSUE THREAD

**Issue by rllzyy** [cloudfoundry-incubator/kubecf#837]
After I deployed the kubecf and created org and space, 
it seems the defaut **cf marketplace is empty**? could anyone help me for how can I add mysql,postgresql,redis,rabbitmq....to the cf marketplace?
thx a lot

**Comment by fargozhu** [comment]
@rllzyy this answer may help you https://github.com/cloudfoundry/cf-deployment/issues/437#issuecomment-372348567

**Comment by fargozhu** [comment]
you can also use the SUSE sandbox but we are still on 1.5.x there but with plans to upgrade to 2.x (with kubecf).
https://www.explore.suse.dev/capsandbox/

**Comment by fargozhu** [comment]
I am closing this issue, but feel free to reopen if needed.
