### ISSUE TITLE
Cleanup Eirini and Bits helm chart forks part #1

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#844]
- [ ] ~create https://github.com/cloudfoundry-incubator/bits-helm-release~
- [ ] ~move code to the new repos~
- [ ] remove all unused templates and code
- [ ] ~setup protected branches~
- [ ] ~create a story for part #2 (use proper versioning, update kubecf to use the new helm repo urls)~
- [x] call with the previous maintainers to let them know we've taken over
- [ ] move the templates to kubecf directly

~Use https://github.com/cloudfoundry-incubator/eirini-helm-release
and https://github.com/cloudfoundry-incubator/bits-helm-release~

**Comment by andreas-kupries** [comment]
@viovanov I suspect that all but
> remove all unused templates and code

require somebody with admin permissions for various places.
Do you know who can do what ?

**Comment by viovanov** [comment]
Superseded by #1179
