### ISSUE TITLE
Clean up BOSH releases

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#856]
**Is your feature request related to a problem? Please describe.**
Currently, we have [~100 lines of BOSH release configs](https://github.com/cloudfoundry-incubator/kubecf/blob/7ebdcce193f2e5563152923b8d5d1f65eb41606a/deploy/helm/kubecf/values.yaml#L42); I believe they're mostly there because not all images are at the default stemcell level.  We should clean up (do a mass rebuild and bump the default stemcell) to make this less haphazard.

I'm not quite sure why `cf-acceptance-tests` has its own useless stemcell entry that matches the default stemcell…

**Describe the solution you'd like**
* Do a mass rebuild to rebase everything onto the same stemcell
* Ideally, do this before every kubecf release (or at least close enough that we don't drift this much).
* Probably change our SUSE buildpacks pipeline to use the default stemcell instead of… whatever the heck it's doing.

**Describe alternatives you've considered**
Status quote, which makes things hard to read.

**Additional context**
Noticed this while doing #711 — it's unclear if we should mark all of them as hidden, since having a giant pile of essentially useless data is distracting and presents a bad administrator experience.

**Comment by jandubois** [comment]
This has been implemented as part of the configurable multistack work in #1086
