### ISSUE TITLE
secrets.CLUSTER_ADMIN_PASSWORD no longer considered

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry-incubator/kubecf#86]
I am running `v0.4.2%2B92.gd053b0ec` from https://cf-operators.s3.amazonaws.com/helm-charts/index.html as well as `3.0.0-6e03f97` from https://scf-v3.s3.amazonaws.com/index.html.

Previously, secrets.CLUSTER_ADMIN_PASSWORD could be used to set the CF admin password for a landscape. This doesn't seem to work anymore with the above versions. As a workaround, I am reading the current, generated value of the password via
```
kubectl -n scf get secret scf.var-cf-admin-password --template={{.data.password}} | base64 -D
```
but I was wondering if this change is intentional and documented anywhere?

**Comment by f0rmiga** [comment]
We don't have that implemented yet. A good reference for implementing it is looking at https://github.com/SUSE/scf/blob/develop/container-host-files/etc/scf/config/role-manifest.yml.

One thing to note is that maybe the key on values.yaml will change. Suggestion:

```
admin:
  password: ~
```

**Comment by viovanov** [comment]
Related to https://github.com/cloudfoundry-incubator/cf-operator/issues/895

**Comment by jandubois** [comment]
With KubeCF 2.2.0 and later you can set the admin password in `values.yaml` like this:

```
credentials:
  cf_admin_password: changeme
```

Or via `helm install ... --set credentials.cf_admin_password=changeme`.
