### ISSUE TITLE
Don't assume cluster domain is cluster.local

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#872]
The ops file for the eirini-helm instance group is full of URLs ending in `.svc.cluster.local`:

https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/assets/operations/instance_groups/eirini-helm.yaml

These URLs will only work if the cluster uses the default cluster domain name.

Not sure if there is a better solution, but at a minimum we need to make the cluster domain configurable.

**Comment by viovanov** [comment]
This should also work if the service domain suffix was removed.
Remember certs.

**Comment by mook-as** [comment]
Also see [bits](https://github.com/SUSE/bits-service-release/blob/b4b58c1f454c2e111027653a95a2f0f3c157b3fc/helm/bits/templates/bits-config.yaml#L11).

**Comment by mook-as** [comment]
https://github.com/SUSE/eirini-release/pull/5 for the einiri chart, to start.

**Comment by mook-as** [comment]
https://github.com/SUSE/bits-service-release/pull/8 is next up; I _think_ that works.  At least, I'm running a minikube with `MINIKUBE_EXTRA_OPTIONS` set to contain `--dns-domain=stuff --extra-config=kubelet.cluster-domain=stuff` plus operator deployed with `cluster.domain: stuff`.  Smoke tests seem to pass.
