### ISSUE TITLE
Tagging and versioning for the release process

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#876]
**Describe the bug**
The current way of releasing involves changing the source of the project:
https://github.com/cloudfoundry-incubator/kubecf/blob/master/doc/release/release-guidelines.md#files-to-change

**Expected behavior**
Should be able to release without altering the source.
The version of the build on the release pipeline is the version of the latest tag in its commit history.

The process should be:
- Major/Minor Release
  - Create version branch (`release-[MAJOR].[MINOR]`)
  - Create a new release pipeline for that branch
  - Unpause pipeline
  - Continue with "Minor Bump"
- Patch Release
  - Tag commit with new version
  - Push tag
  - Push commit on version branch
  - Wait for commit to pass release pipeline
  - Create release

**Comment by andreas-kupries** [comment]
@viovanov @gaktive @fargozhu ping.

Looking over the request, and then reading the [referenced documentation](https://github.com/cloudfoundry-incubator/kubecf/blob/master/doc/release/release-guidelines.md#files-to-change) I find that the referenced section does not exist in kubecf master (153b6600154886450cffde868c0cf2a9b1203e1a).

I found a [version](https://github.com/cloudfoundry-incubator/kubecf/blob/master/doc/release/release-guidelines.md#version) section instead, whose content implies that this ticket has already been implemented, IIUC. To quote:

> Version string is obtained from the last git tag present in parents.

That part of the documentation was changed by commit 98c138debc17f184bdfdb616c83fde433419beb7, July 28, 2020.
This was part of https://github.com/cloudfoundry-incubator/kubecf/pull/1162/commits, merged Aug 7.

Were there any file changes done in the recent set of releases, to fix/set/maintain release version numbers ?

**Comment by viovanov** [comment]
@andreas-kupries this has been implemented as described, yes

> Were there any file changes done in the recent set of releases, to fix/set/maintain release version numbers ?

Not sure what you mean - the old style of committing the version is no longer used, we use the script in kubecf-tools

**Comment by andreas-kupries** [comment]
> > Were there any file changes done in the recent set of releases, to fix/set/maintain release version numbers ?

> the old style of committing the version is no longer used, we use the script in kubecf-tools

The ticket implied that in the old-style it was necessary to edit files for the version number to be correct. My question referred to us creating a number of releases recently (2.53 to 2.58) and asking if the old style had to be used when that was done.

As you confirm that a script is now used I believe this also confirms that this ticket is out of date and can be closed, right ?
