### ISSUE TITLE
Warning in Helm if Eirini in HA is enabled

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#888]
**Describe the bug**
Based on Eirini's current state with services like bits that can't be made into HA, we need an ability in Helm to check a configuration's settings tied to HA and then fail if Eirini is enabled. For the Eirini tech preview, for now, we need to enforce non-HA for Eirini.

If a warning is possible, then we need to simply output that Eirini won't work in HA mode.

**Comment by troytop** [comment]
If possible, we should instead remove `sizing.eirini.instances` (or is it `sizing.bits.instances`?) and make it so that the admin is _unable_ to set it to more than one. Better to prevent the configuration than warn about it. I would expect `high_availability=true` to do the right thing as well.

**Comment by jandubois** [comment]
> make it so that the admin is _unable_ to set it to more than one.

This means throwing an error when it is set to any other value, right?

There is no way to make it _unable_ to be set to any value. You can either _ignore_ it, or throw an error, when set to an unacceptable value. I would prefer to throw an error than to silently ignore an explicit request by the user.

@troytop If this is expected to still make it into the 2.2.1 patch release, then it needs a `Priority: Critical` label.

**Comment by troytop** [comment]
I misunderstood. I'd be happy with either behavior: throw an error if it's set to more than one, or simply ignore it. Either way it would be good if we had a comment in the values.yaml which stated the limitation.

**Comment by jandubois** [comment]
@troytop Waiting to hear on results from #877. If the issue also happens in SA mode, then there is no point in adding this check to the chart.

**Comment by jandubois** [comment]
As far as I can tell the `sizing.bits.instances` and `sizing.eirini.instances` variables are not used for anything, and there is no way to scale up Eirini to HA to begin with. eirini-extensions is the only subchart that has configurable replica counts (via subchart properties).

Closing this issue because it is based on a false premise.
