### ISSUE TITLE
Track cf-deployment releases in branches

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#9]
We can track every major release of [cf-deployment](https://github.com/cloudfoundry/cf-deployment) in separate branches.

This should be done automatically by a pipeline.
The branches can follow this naming pattern: `cf-v12`.
The branch for version N can be based on the branch for N-1.
Test pipelines can then pick it up, and developers can start working on support for it.

**Comment by fargozhu** [comment]
related with #48

**Comment by fargozhu** [comment]
closing this issue since we have better description on the duplicated one #48
