### ISSUE TITLE
Provide readme and icon for Helm chart

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#915]
**Is your feature request related to a problem? Please describe.**
We need to provide a readme file and an icon for the KubeCF helm chart. 

We can use the project icon here and populate the readme with the variables. We can use cf-operator and quarks for reference.

**Comment by gaktive** [comment]
@troytop to provide a blurb on the readme.

**Comment by gaktive** [comment]
For the short term, instead of all values, grab the most important 5 values and we can figure out a way to automating this. There may be flux in variables going forward.

**Comment by jandubois** [comment]
Implemented in #918 and #924
