### ISSUE TITLE
CI — Artifact file name should be decoupled from chart version

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#930]
**Describe the bug**
Currently, in CI, the artifact file name (e.g. `kubecf-bundle-v2.2.2.tgz`) is directly derived from the helm chart version.  This is an issue as all of our release-branch charts have the same chart version (in the sample, `v2.2.2`), so that every build has the same file name.  Unfortunately, concourse parses out the resource version out of the file name, so every build uses the same artifact (as in, it doesn't attempt to re-download the changed artifact) so our CI can end up testing the wrong build.

**To Reproduce**
Examine the concourse pipeline for the 2.2 release branch.

**Expected behavior**
Multiple artifacts for the release branch, so they all get tested independently.

**Environment**
CI pipeline, for the release-2.2 branch.

**Additional context**
- Chart version is set in [`//deploy/helm/kubecf:kubecf`](https://github.com/cloudfoundry-incubator/kubecf/blob/40b13219f1f462cc51dfe1b12d3ec0e657d5c30d/deploy/helm/kubecf/BUILD.bazel#L118)
- We grab the chart version in [`//deploy/helm/kubecf:version`](https://github.com/cloudfoundry-incubator/kubecf/blob/40b13219f1f462cc51dfe1b12d3ec0e657d5c30d/deploy/helm/kubecf/BUILD.bazel#L138)
- We read it out in [`/dev/build.sh`](https://github.com/cloudfoundry-incubator/kubecf/blob/40b13219f1f462cc51dfe1b12d3ec0e657d5c30d/dev/build.sh#L38)
- We use the version in [`/dev/build.sh`](https://github.com/cloudfoundry-incubator/kubecf/blob/40b13219f1f462cc51dfe1b12d3ec0e657d5c30d/dev/build.sh#L52)
- Which is used in the [pipeline](https://github.com/cloudfoundry-incubator/kubecf/blob/40b13219f1f462cc51dfe1b12d3ec0e657d5c30d/.concourse/pipeline.yaml.gomplate#L351)

Adjacent issues:
- #876: Tagging and versioning for the release process
- #927: Helm chart version should be a pure semver

**Comment by jimmykarily** [comment]
We discussed that with @viovanov @mudler and @viccuad and decided to add a UUID to the filename to make sure every build is always using a new artifact. It will be the equivalent of a build number but not incrementing or sequential, just a random UUID.
