### ISSUE TITLE
Configurable prefix for diego cell IDs

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#934]
**Is your feature request related to a problem? Please describe.**
For multi-cluster support, we have to register cells to the control plane in a unique way, so we need a configurable prefix for cells.
At the moment, a cell looks like `diego-cell-0`, `diego-cell-1` ...
If a prefix is set, it would look like `cluster-0-cell-0`, `cluster-0-cell-1`, `cluster-1-cell-0` ...

**Describe the solution you'd like**
A patch similar to the one in the spike [1].
It has to be applied to both the `rep` [2] and the `route_emitter` [3].

**Describe alternatives you've considered**
Using placement tags for the prefix, but that can lead to problems with DNS if they're not sanitized properly, and it might restrict how many placement tags can be used.

**Additional context**
#822

- [1] https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f
- [2] https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f#diff-fd202d739f803de0a1cc391d1e629199R28
- [3] https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f#diff-c3a0172e6197100ebfcc5541f2239076R22

**Comment by qu1queee** [comment]
This is being worked by someone inside IBM

**Comment by SteveZhang-CDL** [comment]
Hi @viovanov , I have deployed only `diego-cell` in a k8s cluster, and use the branch of **vladi/multicluster/** ’s pre_render_scripts to this deployment. It seems that `rep.json` and `route_emitter.json` have already been applied with prefix `minions-1`  showing in below snapshots. However, the pod name and service name of diego-cell is still looks like the same as it’s generated. So this kind of modification in **vladi/multicluster/** is only at the level of the `*.json` files inside the diego-cell. In my opinion, source code of `quarks-operator` should be changed to support this feature properly.

<img width="675" alt="rep_json" src="https://user-images.githubusercontent.com/4101246/86442874-01dce880-bd41-11ea-8c12-59532ed1df8f.png">
<img width="689" alt="route_emiter_json" src="https://user-images.githubusercontent.com/4101246/86442895-073a3300-bd41-11ea-95d9-d953698f9525.png">
<img width="1377" alt="bosh_cell" src="https://user-images.githubusercontent.com/4101246/86442939-14572200-bd41-11ea-9f45-ef08b8bed397.png">

**Comment by viovanov** [comment]
@SteveZhang-CDL this is just about how the cell advertises itself to the world.
The operator can't do anything about this - the hostname could be `foo-cell-whatever-we-want`.
As long as we can control the cell's hostname, we can create a service in the control plane, so the auctioneer can reach it.
Ideally, this would be configurable in the upstream diego release, but I think we can live with a patch for now.

**Comment by SteveZhang-CDL** [comment]
@viovanov okay, got it, this issue is only focus on how the cell register itself to router, it does not matter with the name of qjob, qstatefullset and service, etc. Thank you for your feedback.
