### ISSUE TITLE
Ability to disable the database

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#935]
**Is your feature request related to a problem? Please describe.**
In KubeCF, one can use an external database, or the internal database.
There are flags for each, so in theory, one should be able to disable both, but that doesn't work.
For multi-cluster support, we need to disable and enable components of KubeCF, but the database can't currently be disabled.

**Describe the solution you'd like**
We need this condition: https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f#diff-361b17e68046e0c23bbd766d02a06c8eR120

**Describe alternatives you've considered**
n/a

**Additional context**
#822

**Comment by qu1queee** [comment]
Being worked by someone inside IBM

**Comment by viovanov** [comment]
@JimmyMa - any progress on this?

**Comment by gu-bin** [comment]
PR https://github.com/cloudfoundry-incubator/kubecf/pull/1096 submitted. Please review. Thanks.

**Comment by gu-bin** [comment]
@viovanov @qu1queee Would you please review the PR? Thanks.

**Comment by qu1queee** [comment]
@viovanov do you want to assign this to someone from kubecf team?

**Comment by viccuad** [comment]
With https://github.com/cloudfoundry-incubator/kubecf/pull/1096 closed, is this closed?

**Comment by viovanov** [comment]
Yes
