### ISSUE TITLE
Cluster worker feature

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#938]
**Is your feature request related to a problem? Please describe.**
A feature to enable `cluster-worker` mode.

**Describe the solution you'd like**
When the cluster worker feature is enabled, the `control-plane` cannot be enabled.
When the `cluster-worker` feature is enabled, the following ops files must be activated, to remove everything but the cells and to enable quarks entanglements for links consumed by diego-cell jobs:

https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f#diff-8fc2de7ef5a3d25ddfce0cd023890d0cR992-R1050

The entanglements are supported by the following services and secrets:
https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f#diff-b10566ab232ec1929fad999978012977
https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f#diff-fb18c8ade07a0cd5a29470633033ab14

**Describe alternatives you've considered**
n/a

**Additional context**
#822

**Comment by qu1queee** [comment]
Someone inside IBM is working on this

**Comment by jandubois** [comment]
I assume this is now called the `cell_segment` feature and has been implemented.
