### ISSUE TITLE
Script to generate a values.yaml for worker clusters

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#939]
**Is your feature request related to a problem? Please describe.**
Configuring a cluster worker is hard to do manually.
A script would help with this.

**Describe the solution you'd like**
A script that looks at the control plane and generates a values yaml to help with configuring a worker cluster.

See this commit for all the values that have to be set:
https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f

**Describe alternatives you've considered**
Support for cross-cluster secret copying in the quarks operator. 
https://www.pivotaltracker.com/story/show/173034786

**Additional context**
#822

**Comment by qu1queee** [comment]
This is being worked by someone inside IBM
