### ISSUE TITLE
spike: routers in cluster workers

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#940]
**Is your feature request related to a problem? Please describe.**
A multi-cluster deployment of kubecf could benefit from routers living in the worker clusters.

**Describe the solution you'd like**
Try to use routers in worker clusters for HA purposes and for optimizing traffic (routers can be isolation segment aware)

**Describe alternatives you've considered**
n/a

**Additional context**
#822

**Comment by jandubois** [comment]
There is currently no plan for any additional multi-cluster development.
