### ISSUE TITLE
CVE catchup: bump cflinuxfs3 to 0.189.0+

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#949]
**Describe the bug**
Currently in kubecf, it looks like have cflinuxfs3 `0.167.0` (2020 March). We normally build on sle15 but we should ensure we keep up-to-date since CVEs do keep rolling in. Once I get a moment, I'll scan for any scary ones.

Latest cflinuxfs3: 0.189.0 that addresses other CVEs though I haven't vetted them yet: https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.189.0
scf has already done its own test with it based on older automation so we should be able to repurpose existing code to have something similar for kubecf: SUSE/scf#3472

**Comment by gaktive** [comment]
Crosslinked for reference, the cf-deployment bump to `13.2` gets us to cflinuxfs3 `0.178.0` so we'd need to review higher than that once we do that bump.

**Comment by thardeck** [comment]
The latest cflinuxfs3 is already automatically built and uploaded to Dockerhub in the flintstone Concourse: https://ci.flintstone.cf.cloud.ibm.com/teams/quarks/pipelines/release-images/jobs/build-cflinuxfs3/builds/76

But it uses always the latest stemcell which is not part yet of kubecf unless we merge the current stemcell pr.

@gaktive 
Should we use this image or create an additional pipeline to build it?
Or is it only about overriding the cflinuxfs3 version (from cf-deployment) for kubecf - but then we could have different stemcells in the release.

**Comment by gaktive** [comment]
@thardeck upon discussion, the rule of thumb here is to look at the cflinuxfs3 versions as they become available and evaluate them based on CVEs. Whenever possible and avoiding breakage, we should bump cflinuxfs3 to the latest so long as we don't break cf-deployment.

Unfortunately, I don't have access to Flintstone to see the latest image but I can infer that we do build the latest. The proposal then is to use that image and put it into kubecf and ensure that tests pass. I'm not sure what the logic to use in case that there is breakage but when in doubt, use the cf-deployment bundled cflinuxfs3 instead (unless there's a downgrade).

Hope that helps.

**Comment by gaktive** [comment]
@viovanov & @troytop any further insight?

**Comment by troytop** [comment]
@gaktive I think that covers it.

**Comment by thardeck** [comment]
@gaktive 
If I understand you correctly you want one manual update like this https://github.com/cloudfoundry-incubator/kubecf/commit/d8394a09b5c44ff6e193404c220f09b7931c070f ?
And every time there is a new cve we update it again or remove it as soon as our cf-deployment catches up?

I think we also need the stemcell update #980 so kubecf does not rely on more then one stemcell.

Do you want any additional automation or follow up issues on top of this?

**Comment by andreas-kupries** [comment]
@gak @thardeck I see no pull request(s) which can be reviewed ?! May we have some links ?

**Comment by andreas-kupries** [comment]
Oh, is that #1002 ?

**Comment by andreas-kupries** [comment]
How does #980 come into that ? A separate merge ? A specific ordering ?

**Comment by gak** [comment]
@andreas-kupries you got the wrong @gak! 😄 I think you mean @gaktive.

**Comment by andreas-kupries** [comment]
Oops. Apologies

**Comment by thardeck** [comment]
I have created a simple automation which can be merged if the changes are relevant: https://github.com/SUSE/cloudfoundry/pull/174

The result looks like this:
https://github.com/cloudfoundry-incubator/kubecf/pull/1030

**Comment by gaktive** [comment]
Amongst the dozens of medium CVEs that were announced today, https://www.cloudfoundry.org/blog/usn-4396-1/ requires that we go to 0.194.0. (I won't link to the rest since they're the same prio and deal with now older versions.)

**Comment by gaktive** [comment]
Then again, based on #1002, perhaps this item can be closed if the mechanisms are in place to do updates.

**Comment by thardeck** [comment]
> Then again, based on #1002, perhaps this item can be closed if the mechanisms are in place to do updates.

It is: https://github.com/cloudfoundry-incubator/kubecf/pull/1068
