### ISSUE TITLE
klog.sh fails to write collected Resources and exits with an error

### ISSUE THREAD

**Issue by greygoo** [cloudfoundry-incubator/kubecf#954]
**Describe the bug**
When running klog.sh, I fails with an error message upon trying to write a file into a nonexisting directory:
```
> klog.sh 
Global information...
  Resources ...
/catapult/buildaks-ingress-eirini-ha-02/bin/klog.sh: line 115: /home/chullerlocal/klog/kubecf/resources.yaml: No such file or directory
```

**To Reproduce**
run `klog.sh`

**Expected behavior**
klog.sh should write the resources into a file

**Environment**
 - kubecf2.2
 - klog.sh
 - deployment of kubecf was done on aks

**Additional context**
It seems klog.sh first removes the dir and then tries to write into it.

**Comment by greygoo** [comment]
This only seems to happens wen you run klog.sh without an argument. When being run as `klog.sh scf` the error does not appear.

**Comment by gaktive** [comment]
@sroy to move this over to CAP.

**Comment by viccuad** [comment]
For the record, the `scf` on  `klog.sh scf` is just the namespace where we install kubecf in. This is in indeed a kubecf problem and not and scf one.

**Comment by viccuad** [comment]
This seems to have been fixed in https://github.com/cloudfoundry-incubator/kubecf/commit/9f879a17453c66a684895ac666d92b80b1ad6b43#diff-7984c33868a41b616c717585a0fae9e2R143, closing!

**Comment by andreas-kupries** [comment]
Agree that the diff looks to be sensible for a fix.
