### ISSUE TITLE
After helm upgrade to scale diego cell count from 3 to 4, 2 out of 3 diego-cell pods gets restarted

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/kubecf#981]
**Describe the bug**
When I use `helm upgrade` to scale up the diego cell count for 3 to 4. diego-cell-2 and diego-cell-1 get restarted consecutively, once new diego-cell-3 is up. 
diego-cell-0 never gets restarted

It takes 19 min approx for all pods to get in `running` state

**To Reproduce**

- HA deployment (3 diego cells)
- Deploy an app with 3 instances 
- run helm upgrade to bring the count of deigo cell to 4

**Expected behavior**
A new diego cell should appear, no pods should restart.

**What happens**
some of the old diego-cell pods (2 out of 3) get restarted

**Environment**

 kubecf-2.0-RC1                  2.0-RC1 
cf-operator-4.5.6+0.gffc6f942   4.5.6+0.gffc6f942

**Additional context**
```
diego-cell-0                             7/7     Running     2          3h6m
diego-cell-1                             7/7     Running     2          6m57s
diego-cell-2                             7/7     Running     2          10m
diego-cell-3                             7/7     Running     2          24m
```

**Comment by jimmykarily** [comment]
![Screenshot at 2020-06-09 17-22-58](https://user-images.githubusercontent.com/2794419/84159667-fe25b100-aa75-11ea-879d-ed66f1a3525c.png)

I reproduced it. It seems to be restarted because the readiness probe fails. I will investigate more.

**Comment by jimmykarily** [comment]
I verified that simply editing the StatefulSet and changing the value of `REPLICAS` restarts the pods. So we just need to decide wether this environment variable is needed in the spec. Some docs on where it's used here: https://github.com/cloudfoundry-incubator/quarks-operator/blob/master/docs/Features/rendering_templates.md#render-templates (look for `REPLICAS`).

**Comment by jandubois** [comment]
> Obviously the value of REPLICAS changes every time and that must be the reason all pods get restarted.

Yes, that is all expected (except, why did the bootstrap pod not restart? Does it not get the `REPLICAS` variable? (I know in SCF we had to handle this specially for the nats-0 pod too).

The question is though: *why* do we need that variable? Afaict there is no reference to is from KubeCF.

It also feels inconsistent that we provide `AZ_INDEX` and `REPLICAS`. Why does the pod need to know the total number of replicas, but not the total number of AZs?

@viovanov can you provide some background information?
