### ISSUE TITLE
Store subcharts inside the kubecf repo

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#987]
Right now we reference the bundled subcharts via `requirements.yaml`:

```yaml
dependencies:
- name: eirini
  version: 1.0.2
  repository: http://opensource.suse.com/eirini-release/
...
```

and we only fetch the actual charts via `helm dep up` when we build the kubecf helm chart.

I would like to propose that we run `helm dep up` every time we bump the dependency and check the downloaded subcharts into the kubecf repo. This has the following advantages (in decreasing order of importance to me):

* It becomes possible to quickly look up something in the subchart without having to fetch it manually, e.g. to see how something is configurable.

* When a chart is bumped, you can see the diff of what has changed, both on Github and locally with git. It can provide context to understand why some subchart settings are being changed in kubecf.

* We can now guarantee that the subchart doesn't change between rebuilds. `requirements.yaml` only uses a version number, not a shasum, so currently we rely on charts not being re-published to the external repo without version number updates.

* The build becomes slightly faster, although only trivially so.

Are there any reasons why we should **not** do this?

**Comment by mook-as** [comment]
> When a chart is bumped, you can see the diff of what has changed, both on Github and locally with git. It can provide context to understand why some subchart settings are being changed in kubecf.

I don't think that's actually true: I believe the charts are kept as `tgz`s, so you can't see the diff on GitHub. (If you have appropriate textconv filters, you _can_ see the diff locally.)

This isn't to say we _shouldn't_ do this; just that we should be aware that the files will be binary.

**Comment by jandubois** [comment]
> I believe the charts are kept as `tgz`s

Oops, you are right about that. That would not provide the advantages I am looking for.

So I would suggest that bumping subcharts should be done with:

```bash
cd deploy/helm/kubecf
vi requirements.yaml
rm -rf charts/*
helm dep up
for CHART in charts/*tgz; do tar xfz $CHART -C charts; rm $CHART; done
git add --all .
```
