### ISSUE TITLE
Bit pod  continuously in state ContainerCreating 

### ISSUE THREAD

**Issue by vijendergeek** [cloudfoundry-incubator/kubecf#989]
Took latest release of kubecf **v2.2.2** with cf-operator **cf-operator-4.5.6%2B0.gffc6f942.tgz**
**K8s version 1.18.3**
The Bit pod gives following error

Events:
  Type     Reason       Age                From                       Message
  ----     ------       ----               ----                       -------
  Normal   Scheduled    33m                default-scheduler          Successfully assigned kubecf/bits-74c466f964-rh7m4 to k8s-worker-0
  Warning  FailedMount  20m (x2 over 27m)  kubelet, k8s-worker-0  Unable to attach or mount volumes: unmounted volumes=[bits-cert], unattached volumes=[default-token-vmnw5 bits-config bits-cert]: timed out waiting for the condition
  Warning  FailedMount  13m (x6 over 31m)  kubelet, k8s-worker-0  Unable to attach or mount volumes: unmounted volumes=[bits-cert], unattached volumes=[bits-config bits-cert default-token-vmnw5]: timed out waiting for the condition
  Warning  FailedMount  11m (x2 over 24m)  kubelet, k8s-worker-0  Unable to attach or mount volumes: unmounted volumes=[bits-cert], unattached volumes=[bits-cert default-token-vmnw5 bits-config]: timed out waiting for the condition
  **Warning  FailedMount  3m (x23 over 33m)  kubelet, k8s-worker-0  MountVolume.SetUp failed for volume "bits-cert" : secret "bits-service-ssl" not found**

NAME                                         READY   STATUS              RESTARTS   AGE
adapter-0                                    4/4     Running             0          52m
api-0                                        15/15   Running             1          52m
**bits-74c466f964-rh7m4                        0/1     ContainerCreating   0          55m**
bosh-dns-6fbdfd6bf5-g46s5                    1/1     Running             0          52m
bosh-dns-6fbdfd6bf5-wm74j                    1/1     Running             0          52m
cc-worker-0                                  4/4     Running             0          52m
credhub-0                                    6/6     Running             0          52m
database-0                                   2/2     Running             0          53m
database-seeder-05520d28e02b5eb2-6s2nk       0/2     Completed           0          54m
diego-api-0                                  6/6     Running             3          52m
doppler-0                                    4/4     Running             0          52m
eirini-97d4bdb69-8wjk2                       1/1     Running             0          55m
eirini-events-54b5f6fbcd-qqxzs               1/1     Running             0          55m
eirini-metrics-6dc49bf77d-5whkf              1/1     Running             0          55m
eirini-routing-66c54cbd48-nj2lw              3/3     Running             15         55m
eirini-staging-reporter-8558fd6886-zxfp9     1/1     Running             0          55m
kubecf-loggregator-bridge-56c9879995-9n8wp   1/1     Running             0          55m
kubecf-persi-6869df55f4-7m825                1/1     Running             0          55m
kubecf-persi-broker-59c8f9cd74-6bxxh         1/1     Running             0          55m
kubecf-ssh-95b54f947-rx7mk                   1/1     Running             0          55m
kubecf-ssh-proxy-64bdfd78cd-mcrfd            1/1     Running             0          55m
log-api-0                                    7/7     Running             0          52m
log-cache-0                                  8/8     Running             0          52m
nats-0                                       4/4     Running             0          52m
router-0                                     5/5     Running             0          52m
routing-api-0                                4/4     Running             0          52m
scheduler-0                                  8/8     Running             0          52m
singleton-blobstore-0                        6/6     Running             0          52m
tcp-router-0                                 5/5     Running             0          52m
uaa-0                                        7/7     Running             2          52m

**Comment by mukulk2020** [comment]
I am getting this error on kubecf v2.3.0 with k8s 1.16.

**Comment by andreas-kupries** [comment]
Trying to reproduce using
  - minikube 1.9.2 - k8s `1.17.5`
  - cf-operator `5.2.0+0.g22cafc90`
  - kubecf commit (25ecfdf34d, current master) ~ Likely most related to `2.2.3`, plus dev work.
   (Note: release-2.3 (= 2.3.0) looks to be a month old. The 2.2.3 OTOH was tagged just a week ago).

I find myself unable to repro
Tried 10 times, bits pod came up just fine every time.

From reading the various logs here and #1057 it might have been an operator issue ?
Original report above mentions operator `4.5.6`, some for #1057 

@mukulk2020 What was the operator you used ?

My attempts to repo used operator `5.2.0+0.g22cafc90` instead, quite a bit ahead.

**Comment by viovanov** [comment]
@vijendergeek please let us know if this is still happening by reopening this ticket
